### ISSUE TITLE
Error trying to delete a branch using git

### ISSUE THREAD

**Issue by tardieu** [IBM/kui#1069]
```
git branch -d constructor
```
outputs:
```
Cannot read property 'route' of undefined
```

![Screen Shot 2019-04-05 at 9 09 01 AM](https://user-images.githubusercontent.com/13540792/55629943-7ada4280-5782-11e9-9174-e7958612830a.png)

**Comment by starpit** [comment]
so far, we haven't been able to replicate this. i suspect that you caught a brief window where we had a regression. i'll keep this open until we can cover git operations with tests

**Comment by starpit** [comment]
shoudl be resolved
