### ISSUE TITLE
feat: manage kubernetes port forwards

### ISSUE THREAD

**Issue by esnible** [IBM/kui#1109]
Developers like to use `kubectl port-forward` to test and debug running apps.  It would be very nice if this could be automated.

I imagine an "action" button on `kubectl get pods` similar to the one on `kiali get apps` that would offer port-forwarding.  It would be nice if Kui remembered port-forwards and displayed them on a page as a list with option to stop the forward.

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/plugin-kubeui/issues/190
