### ISSUE TITLE
high severity vulnerabilities warnings in npm install

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1131]
When I `npm install` on the top-level, I got `8 high severity vulnerabilities` warning, and with `npm audit`, I got: 
![Screen Shot 2019-04-11 at 4 00 47 PM](https://user-images.githubusercontent.com/21212160/55988968-31529180-5c73-11e9-9540-b4f7276ec9df.png)

`node-gyp` used `tar` version prior to 4.4.2, which is vulnerable to Arbitrary File Overwrite. 

For reference: `node-gyp` updated it's tar version to the latest in this commit: https://github.com/nodejs/node-gyp/commit/1456ef27c72cc4e49f9b1d82cbb047cb673156c8. Since we're using pining dependencies, we need to watch for new `lerna` release. (FYI: lerna 3.13.2 doesn't help.)

**Comment by starpit** [comment]
i have opened an issue against lerna: https://github.com/lerna/lerna/issues/2036

**Comment by starpit** [comment]
root cause: https://github.com/nodejs/node-gyp/issues/1717

**Comment by myan9** [comment]
Fixed
