### ISSUE TITLE
proxy+browser mode: some command not work

### ISSUE THREAD

**Issue by Xiaohua-Shen** [IBM/kui#1179]
* related command output
<img width="363" alt="屏幕快照 2019-04-19 上午9 35 10" src="https://user-images.githubusercontent.com/19463092/56400542-ffe75080-6286-11e9-97ae-d4e1977f016b.png">

* `ls` command has no debug log in proxy log.
* `pwd` command has no debug log in proxy log.

**Comment by starpit** [comment]
this is i believe due to websockets not being exposed by your proxy container. you could fix this in the short-term by ensuring that ports 8082-8088 are available from the proxy, but we will fix this more properly by having websocket communication piggy-back on the main proxy port

**Comment by starpit** [comment]
can you try again? #1187 should hopefully address this.

also, there is now a kube resource spec that deploys the proxy and webpack client: https://github.com/IBM/kui/blob/master/packages/proxy/deploy/kubernetes/client-proxy-combo.yaml

**Comment by Xiaohua-Shen** [comment]
I used latest package, and seems all commands not work now.
<img width="675" alt="屏幕快照 2019-04-24 上午9 30 02" src="https://user-images.githubusercontent.com/19463092/56626295-ba09fe00-6673-11e9-9e74-a553798c3bb3.png">
no log was shown in kui-proxy log.

**Comment by starpit** [comment]
closing as stale. we've made considerable progress since this issue was opened.
