### ISSUE TITLE
cannot switch kube contexts by click

### ISSUE THREAD

**Issue by Xiaohua-Shen** [IBM/kui#1180]
<img width="834" alt="屏幕快照 2019-04-19 下午3 40 32" src="https://user-images.githubusercontent.com/19463092/56413268-7f8e1300-62b9-11e9-9d6d-e17f6c470161.png">

it should be clickable to switch contexts. but now click no work, and no proxy related logs.

**Comment by starpit** [comment]
i think this affects electron clients as well. will fix and cover with tests. this is a regression.
