### ISSUE TITLE
clicking on green/red command status box makes shell unresponsive

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1204]
<img width="1273" alt="Screen Shot 2019-04-23 at 8 25 40 AM" src="https://user-images.githubusercontent.com/4959922/56580792-721aa680-65a1-11e9-960f-e5e298989ec1.png">

clicking on the green square you get the error message above and the shell requires a refresh to be responsive again (you can type but can't complete with a `return`).

same if the square was red.

**Comment by starpit** [comment]
is this with a webpack client?

**Comment by rabbah** [comment]
Yes.
