### ISSUE TITLE
bad hover in grid

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1205]
<img width="323" alt="Screen Shot 2019-04-18 at 3 18 45 PM" src="https://user-images.githubusercontent.com/4959922/56580864-b0b06100-65a1-11e9-931c-d3f27e438d70.png">

hovering over activations in the the top row of the grid ^^

**Comment by starpit** [comment]
thanks for the issue. we probably need to switch away from using CSS tooltips. but we can probably ameliorate this issue in the short term

**Comment by starpit** [comment]
closing in favor of #1444
