### ISSUE TITLE
xtermjs cursor sometimes remains visible after command execution terminates

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1210]
pty commands in webpack (no proxy) client will return empty xterm-helper block in the output.
Client: webpack without proxy
Env: safari
![Screen Shot 2019-04-23 at 12 58 28 PM](https://user-images.githubusercontent.com/21212160/56603067-e61e7400-65cc-11e9-85fb-63d905e88a4c.png)

**Comment by starpit** [comment]
thanks. yes this is a remaining quirky bug in the PTY. this is not specific to webpack clients.

**Comment by starpit** [comment]
should be fixed by #1272
