### ISSUE TITLE
applying HPA gives unexpected status

### ISSUE THREAD

**Issue by rvennam** [IBM/kui#1220]
![image](https://user-images.githubusercontent.com/5502967/56705208-0f7af500-66de-11e9-8f91-193a38aedc07.png)

**Comment by starpit** [comment]
thanks. will fix soon. this appears to be yet another example from the kubernetes world of a resource that doesn't have a proper notion of status.

**Comment by rvennam** [comment]
any update on this @starpit ? we need this for a demo recording

**Comment by starpit** [comment]
on it!
