### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by hyundotio** [IBM/kui#1242]
On the right side of KUI (the GUI portion) it would be nice to have a series of shortcuts that will allow the user to...

- [ ] Change panes (between CLI vs GUI; Maybe Ctrl + Tab)
- [x] Navigate items within sessions (tabbing through items)
- [ ] Select / Activate certain items (space bar to activate)
- [x] Switching tabs (Ctrl + 1, Ctrl + 2, etc)
- [x] New Window (Ctrl + N or Ctrl + T)

This would let me have the experience of being in a CLI constantly without using a mouse.

**Comment by hyundotio** [comment]
Interaction possibilities if we integrate keyboard shortcuts...
When the user types in "list" for example and an in-line graphical output is returned in KUI, would the user have to press the "up" key to focus on the inline graphical output of "list" or would the "list" be already in focus and the user press "down" to continue interacting with the CLI?

**Comment by starpit** [comment]
great, thanks for assmembling this list. new tab/new window has done for a while, so i have checked it off.

**Comment by maltron** [comment]
I would love to see more Keyboard shortcuts in it. It would be easier (and faster) to navigate through different Tabs

**Comment by starpit** [comment]
agreed with tab cycling. we should figure out how we shortcut tab cycling. e.g. 

- on macos Terminal it's Option+{ and Option+} to shift-left and shift-right
- on macos Firefox, it's Ctrl+PageUp and Ctrl+PageDown, respectively
- on ubuntu's Terminal, it's the same as on macos Firefox...

we could probably support both

**Comment by hyundotio** [comment]
Also support tab by index. Ctrl + 1, 2, etc

**Comment by starpit** [comment]
tab switching covered by #3587
