### ISSUE TITLE
show directory rather than just ">_"

### ISSUE THREAD

**Issue by hyundotio** [IBM/kui#1245]
When I navigate through directories, I'd like to know where I am constantly. I think it would be good to follow conventions of other terminals (Mac, Windows, and other linux distros) and show for example: `username@host:~/folderName >_ `rather than just `>_` Maybe this can be customized to show the username, host, and/or current directory.

**Comment by hyundotio** [comment]
Instead of the whole folder structure... we should put the last 2 folders (or since this is powered by HTML, we can show the last 2 folders and do a hover element that will reveal the entire thing when hovered)

**Comment by starpit** [comment]
done
