### ISSUE TITLE
Slow Response Time for PTY commands with expensive bash_profile load times

### ISSUE THREAD

**Issue by hyundotio** [IBM/kui#1247]
In Ubuntu 19.04 - a lot of non-native KUI functions (for example: echo, ll, pwd) take about 1.5-2 seconds to return something.

**Comment by starpit** [comment]
i believe that this is due in large part to having an expensive bash_profile or zshrc. thus, i believe the problem extends beyond linux. updating the issue title to reflect this.

issue triage: the PTY support right now launches a new bash process with login+interactive flags; thus we re-read the bash_profile on every command execution. one solution is to load a bash just once. this may require some care w.r.t. bash prompts and the like.

**Comment by starpit** [comment]
FYI: as a stopgap, users can now guard expensive parts of their bash_profile or zshrc with e.g.

```bash
if [ -z "$KUI" ]; then
       source ~/.git-completion.bash
fi
```

where in this example i am guarding the loading of bash completion scripts

**Comment by glensc** [comment]
or just:

```bash
test -n "${KUI:-}" && return
```

;)

**Comment by starpit** [comment]
<facepalm emoji> :)

👍
