### ISSUE TITLE
Nano Crash Issue

### ISSUE THREAD

**Issue by hyundotio** [IBM/kui#1254]
nano makes the application loop in some state, and crashes/lock out other sessions (tabs).

**Comment by starpit** [comment]
verified. weird. thanks!

**Comment by starpit** [comment]
i have triaged this issue. the kui pty code current triggers a resize when the application enters or exits "alt buffer mode" (usually this occurs when an editor enters or exits, respectively, full screen mode). 

in turn, `nano` for some reason sends an exit alt, then enter alt (in quick succession) whenever it receives a resize! this results in an infinite loop in kui: 

1) user launches nano
2) nano sends "enter alt"
3) kui receives enter alt, then asks the PTY to resize itself
5) nano sends exit alt
6) kui receives, then asks the PTY to resize itself
7) etc.

for the short term, we can add a hysteresis to avoid the infinite loop

**Comment by starpit** [comment]
btw, you can see this effect in a plain terminal: launch nano and resize the window. you will observe nano elements flashing; in essence, nano completely redraws itself on every screen resize. other editors, such as vim or emacs, do not completely redraw themselves on PTY resize
