### ISSUE TITLE
Default for API host when user doesn't set one and has no credentials

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [IBM/kui#1262]
Currently, a truly new user (with no OW credentials) doesn't have any API host until he sets one, which would require him to know what to set.  This makes sense if the ability to communicate with an OW controller is only in service of OW development (someone in that situation would presumably know how to get credentials).   However, having no API host initially is an obstacle to bootstrapping a new user into productivity.

So we propose giving every new user a useful default API host even if he has no OW credentials and does not set a host explicitly.

In a webpack build, the most useful API host is `window.location.origin` which points back to where the kui client webpack was loaded from.

In an electron build, the `window.location.origin` is pretty useless, but whoever provided the kui client binary for download probably knows what's a good value to use.  We can cover this with build-time configuration.

A PR is pending for this issue which will cover both kinds of builds.

**Comment by starpit** [comment]
sounds great, thanks!
