### ISSUE TITLE
ls -l does not show permissions

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1278]
<img width="436" alt="Screen Shot 2019-05-03 at 1 06 12 PM" src="https://user-images.githubusercontent.com/4959922/57153430-53d45800-6da4-11e9-90c6-09b1dd690cce.png">

i'm not sure why readme has an `*` next to it, tried `ls -l` by accident to see if it had more info.
it would be useful to know what file permissions are.

**Comment by rabbah** [comment]
(indeed the file has +x, now removed and `*` is gone.)

**Comment by starpit** [comment]
agreed, we should support `-l` as meaning "show me perms"

**Comment by rabbah** [comment]
<img width="513" alt="Screen Shot 2019-05-05 at 8 47 26 PM" src="https://user-images.githubusercontent.com/4959922/57234794-6d1d1480-6fef-11e9-87e2-7e65f1389188.png">
