### ISSUE TITLE
extra line on bad commands

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1280]
this is using latest kui webpack 

<img width="202" alt="Screen Shot 2019-05-03 at 3 51 46 PM" src="https://user-images.githubusercontent.com/4959922/57162161-67d78400-6dbb-11e9-80d5-015fe995f5a5.png">

**Comment by starpit** [comment]
version? i suspect that #1272 fixes this. prebuilt build 1803 should contain this PR.
