### ISSUE TITLE
consider auto-negotiating kubernetes credentials from cloud provider

### ISSUE THREAD

**Issue by starpit** [IBM/kui#1290]
examples here for ibm cloud, but we should do this for them all.

e.g. `ibmcloud ks cluster-config <clustername>` or even listing all clusters and constructing a KUBECONFIG that colon-concatenates them.

also, consider auto-refreshing on token expiration, e.g.

```
Unable to connect to the server: failed to refresh token: oauth2: cannot fetch token: 400 Bad Request
Response: {"context":{"errorCode":"BXNIM0408E","errorMessage":"Provided refresh token is expired"}
```

**Comment by starpit** [comment]
closing as stale

**Comment by krishna13052001** [comment]
How to resume the issue of :

Unable to connect to the server: failed to refresh token: oauth2: cannot fetch token: 400 Bad Request
Response: {
	"errorCode": "BXNIM0408E",
	"errorMessage": "Provided refresh token is expired"
}

**Comment by starpit** [comment]
hello! based on the error code, it looks like you are using IBM Cloud Container/Kubernetes Service? If so, this may help to refresh your kubernetes token:

```shell
ibmcloud ks cluster config --cluster <your cluster name>
```

You may also (first) need to re-authenticate with IBM Cloud:

```shell
ibmcloud login <options>
```

where `<options>` can be `--sso` (if your company uses an SSO; this is the case for IBMers)
