### ISSUE TITLE
add more types to plugins

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1291]
1. commandTree: CommandRegistrar
2. prequire: PluginRequire, and remove unnecessary prequire 
3. IEvaluatorArgs

- [x] grid
- [x] tutorial
- [x] k8s
- [ ] OpenWhisk
- [ ] composer
- [ ] bash-like
- [ ] core-support
- [ ] editor

**Comment by starpit** [comment]
i think we have this pretty well covered for now
