### ISSUE TITLE
show ".." in ls output

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1296]
`ls` output is convenient because you can click through to directories or files but you can't navigate backwards, only forward. it would be useful to have `..` in the `ls` output for that reason.

**Comment by starpit** [comment]
yup. also, should clicking on an `ls` directory row also do a `cd` into that directory?

**Comment by rabbah** [comment]
im not sure about `cd` - i found the current behavior of listing the contents of that directory to be in line with my intuition.
