### ISSUE TITLE
prompt is lost if opening new tab from active tab that has an active process in foreground

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1298]
to replicate: start emacs in one tab
then open a new tab
the new tab will not have a showing prompt

if you open two tabs first, and start emacs in one and nothing in the other, then you can create new tabs with a prompt by initiating new tabs from the tab without a running emacs.

git hash 056b1ba.

**Comment by rabbah** [comment]
git hash 056b1ba334cce48a55833fd386ca6de55218ed75.

**Comment by starpit** [comment]
confirmed
