### ISSUE TITLE
tab context is global - should be local?

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1299]
Command history and the working directory are not unique to a tab - if you open two tabs, the history of commands executed in one tab is available in the other. Further, changing the working directory in one tab also changes it in the other. I think this can get confusing and localizing the tab context might be more in line with user intuition.

per tab state feature list:
- [ ] history
- [x] cwd
- [x] env

**Comment by starpit** [comment]
yes, agree 100%

**Comment by starpit** [comment]
cwd and env handled by https://github.com/IBM/kui/pull/1382

**Comment by starpit** [comment]
cwd and env fixes merged; history (and any other state we need) still pending

**Comment by starpit** [comment]
split/tab-specific command history is addressed by #5226
