### ISSUE TITLE
stdout without newline does not print to console

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1301]
<img width="149" alt="Screen Shot 2019-05-05 at 5 23 30 PM" src="https://user-images.githubusercontent.com/4959922/57200472-9475d200-6f5a-11e9-80f8-dd5cb3ff2822.png">

this can also be observed for `cat file` where file doesn't end in a carriage return/newline.

**Comment by starpit** [comment]
hmm, i have yet to be able to reproduce this one

**Comment by rabbah** [comment]
me neither after updating to head.
