### ISSUE TITLE
Linux: npm test not working

### ISSUE THREAD

**Issue by jesusprubio** [IBM/kui#1305]
![image](https://user-images.githubusercontent.com/2753855/57210323-8bc5e000-6fdc-11e9-9081-352898211fd4.png)

- [ ] runMochaLayers.sh should tolerate its absence
- [ ] in the absence of such credentials, we should skip the openwhisk test layers.

**Comment by abdonrd** [comment]
I have the same issue on Mac!

**Comment by starpit** [comment]
i see. thanks for reporting this. we should modify a few things to tolerate the lack of openwhisk credentials more gracefully (this is the content of the .wskprops that is being accessed)

1) runMochaLayers.sh should tolerate its absence
2) in the absence of such credentials, we should skip the openwhisk test layers.

**Comment by jesusprubio** [comment]
WIP here: https://github.com/IBM/kui/pull/1363

**Comment by jesusprubio** [comment]
Closing this one in favor of the PR and this new one: https://github.com/IBM/kui/issues/1370

We've confirmed those ones don't fail in Mac OS X.
