### ISSUE TITLE
label collision in activation summary

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1309]
there are only three activations in this case, 1 for each of the actions
<img width="468" alt="Screen Shot 2019-05-06 at 11 11 09 AM" src="https://user-images.githubusercontent.com/4959922/57234916-b9685480-6fef-11e9-843d-248bc9d4b515.png">

here's one of the divs 
<img width="632" alt="Screen Shot 2019-05-06 at 11 12 26 AM" src="https://user-images.githubusercontent.com/4959922/57234988-e157b800-6fef-11e9-96e3-0818f823ecb1.png">

**Comment by rabbah** [comment]
after adding another activation <img width="376" alt="Screen Shot 2019-05-06 at 11 13 41 AM" src="https://user-images.githubusercontent.com/4959922/57235052-064c2b00-6ff0-11e9-8a14-b18a60856e2c.png">

**Comment by starpit** [comment]
this view no longer exists
