### ISSUE TITLE
git status doesn't render RENAME properly

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1312]
![image](https://user-images.githubusercontent.com/21212160/57235719-7effb700-6ff1-11e9-9a16-f725e058dcd2.png)
![image](https://user-images.githubusercontent.com/21212160/57235782-a5bded80-6ff1-11e9-9125-d60ee96e7f12.png)

**Comment by myan9** [comment]
Also, for `git commit`, it would be nice to show some large size of output in sidecar instead of repl.
![image](https://user-images.githubusercontent.com/21212160/57236016-2aa90700-6ff2-11e9-8b02-99ae6e64b1db.png)

**Comment by starpit** [comment]
also merge conflicts do not render properly

**Comment by starpit** [comment]
we have removed the old (and pretty junky) git support for now
