### ISSUE TITLE
new window every time you click the kui desktop app icon

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1316]
if you build the kui mac app and run it, every click of the icon in the task bar brings focus to the last opened kui window _and_ creates a new one --- i think the latter is undesirable.

**Comment by starpit** [comment]
yes, thanks for reporting this one. sometimes it happens, sometimes not. i hadn't had a chance to dig any further into why this is the case.

**Comment by starpit** [comment]
i see. this bug only occurs when you click on the dock icon after having closed at least one kui window. it will not occur until you close at least one kui window. fixing

**Comment by rabbah** [comment]
nice dig! confirmed on my end too.
