### ISSUE TITLE
esc does not close sidecar when viewing a local js file

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1317]
when viewing a local `.js` file, it opens in the sidecar in edit mode and `esc` does not close the side car. other files open in read only mode and `esc` closes the sidecar.

**Comment by starpit** [comment]
hmm, thanks. i think this is because the monaco-editor component is swallowing the escape key presses? i'll look.

**Comment by starpit** [comment]
this is actually due to a relative recent regression in the escape handling logic; kui attempts to ignore escapes when they come from e.g. a pty emacs; but was too aggressive in dropping events
