### ISSUE TITLE
optimize k8s tests

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1323]
We test all k8s test sequentially. Instead, we should parallel them by allocating namespaces to the tests.

**Comment by starpit** [comment]
when all is said and done, i am hoping that this saves us at least 10 minutes per travis run, which would give a 50% increase in test bandwidth

**Comment by starpit** [comment]
@myan9 i think this and https://github.com/IBM/kui/issues/362 are the same? we can close that one in favor of this issue?
