### ISSUE TITLE
cd to directory with spaces results in error

### ISSUE THREAD

**Issue by hyundotio** [IBM/kui#1330]
1. In Mac Terminal, you can use quotes to go into a directory with spaces "Folder Name". This causes an error in KUI when using "cd". "ls" works.

~2. When you "cd" and tab through folders with spaces, it will not inject / escapes. Thus it will not go into the folder rather show an error.~ [edit: see #1276]

**Comment by starpit** [comment]
folding the second under #1276 and repurposing this issue for the first
