### ISSUE TITLE
nudge vi/emacs a tad

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1331]
when using vi/emacs, the text is flush against the left tab column 
<img width="110" alt="Screen Shot 2019-05-07 at 1 27 59 PM" src="https://user-images.githubusercontent.com/4959922/57320038-fb66c880-70cb-11e9-8328-2b738b779435.png">

this is my mac terminal for contrast - a little teeny bit inset
<img width="71" alt="Screen Shot 2019-05-07 at 1 24 29 PM" src="https://user-images.githubusercontent.com/4959922/57320075-120d1f80-70cc-11e9-840f-a345c6661951.png">

**Comment by starpit** [comment]
interesting. it looks like, at least in the macOS Terminal, all content has a padding-left of a few pixels

**Comment by starpit** [comment]
it looks like macOS has a 2-pixel left pad
