### ISSUE TITLE
Sample plugin requires OpenWhisk

### ISSUE THREAD

**Issue by ydarias** [IBM/kui#1361]
The file `plugins.md` references the sample plugin which has its own documentation. All works fine but the execution of `sample create action` and `sample sidecar` because those commands require OpenWhisk.

Two possible fixes are:
* Add the OpenWhisk requirement at the documentation.
* Or much better, modify the sample plugin to not be dependent on OpenWhisk.

**Comment by starpit** [comment]
thanks for finding this. i think we should remove openwhisk from the sample plugin.
