### ISSUE TITLE
auto scroll console

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1364]
it's very easy to reach the bottom of the shell and find that i'm constantly clearing the console so be back at the top or near the middle. it might be convenient to have an auto scroll mode so that the cursor is generally at mid way... or something better than constantly having to clear (or using ctlr+L).

**Comment by starpit** [comment]
can you help me to understand what this would look like? you aren't suggesting that we have the REPL render half height, but i can't see what else the suggestion would mean?

we could support split screening the repl. would this address your needs?

**Comment by rabbah** [comment]
i admit it's not a great idea --- just wanted to put out the thought that maybe the console can support a mode where it auto-scrolls... other outrageous ideas: reverse scroll mode, or fixed position for command line with text scrolling below.

**Comment by starpit** [comment]
interesting thoughts! maybe we could have the current prompt and prompt output always at the top. and the history below it?!

**Comment by starpit** [comment]
i am going to consider this "kinda covered" by  #1955. with that PR, you can add `kui--bottom-input` to your client's `bodyCss`. this will give you a fixed input at the bottom; the main REPL section, in that mode, is treated as read-only history.

**Comment by rabbah** [comment]
> this will give you a fixed input at the bottom

is it possible to fix the prompt to the top instead of the bottom?

**Comment by starpit** [comment]
yes, i think this would be a straightforward css tweak
