### ISSUE TITLE
Need to rebuild after any test change

### ISSUE THREAD

**Issue by jesusprubio** [IBM/kui#1404]
I need to use this command after each change in the tests:

```rm -rf node_modules && rm -rf build && npm i```

**Comment by myan9** [comment]
Can `npm run compile` or `npm run watch` (compile in watch mode) in the top level solve this problem?

**Comment by jesusprubio** [comment]
Yes, solved with `npm run compile` :smile:

**Comment by myan9** [comment]
An observation from my experience: If I want to move the test files to other directories,  I need to `rm -rf node_modules && rm -rf build && npm install`. Otherwise, `npm run watch` should be good for development.
