### ISSUE TITLE
kubectl cluster-info returns color code in Kui 

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1420]
Terminal: 
![Screen Shot 2019-05-15 at 1 17 30 PM](https://user-images.githubusercontent.com/21212160/57796093-8b80bf80-7715-11e9-88a4-fc4cbf1f9a88.png)

Kui: 
![image](https://user-images.githubusercontent.com/21212160/57796107-92a7cd80-7715-11e9-877d-76410ee2fb92.png)

**Comment by starpit** [comment]
thanks. right now the kubectl kui command has a catchall for non-usage and non-tabular data, which just renders the raw string into the REPL. we need instead to pass this to pty/client somehow for rendering of the ANSI control codes

**Comment by starpit** [comment]
seems good now
