### ISSUE TITLE
kubectl get -w doesn't update MESSAGE

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1422]
Steps:
1. `k create ns yo`
2. `k get ns -w`
3. `k delete ns yo`
4. Saw Offline Badge and Message 'resource is offline' in the watch table
5. `k create ns yo`
6. Saw Active Badge and Message 'resource is offline' in the watch table

Expect no message in Step 6.

Local Kubernetes: Minikube

kubectl client version: Major 1, Minor 13
kubectl server version: Major 1, Minor 14

MacOS 10.14

**Comment by starpit** [comment]
this is no longer relevant; with #1455 kui watch tables for kubectl now have no message column (in line with the output from the underlying kubectl watch tables)
