### ISSUE TITLE
help output seems wrong

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1423]
![Screen Shot 2019-05-15 at 4 32 30 PM](https://user-images.githubusercontent.com/21212160/57807822-f5a65e00-772f-11e9-870c-9ba036143700.png)
![Screen Shot 2019-05-15 at 4 39 38 PM](https://user-images.githubusercontent.com/21212160/57807874-1373c300-7730-11e9-80a0-273bbc1cd1ef.png)

**Comment by starpit** [comment]
no longer relevant.
