### ISSUE TITLE
Problems in zsh (Linux)

### ISSUE THREAD

**Issue by jesusprubio** [IBM/kui#1425]
- Install Fedora 30
- Install zsh: `sudo dnf install zsh`
- Start and setup it: `zsh`
- Change the active shell: `chsh -s $(which zsh)`
- Restart the session
- Start the cloned repository: `npm start`
- Check the active shell: `echo $0`
- Run problematic commands: `pwd`, `echo hello` ...

![image](https://user-images.githubusercontent.com/2753855/57857715-fa324b80-77ef-11e9-8b09-09c6cb101987.png)

**Comment by starpit** [comment]
i wonder if this affects zsh more generally; @myan9 you are a zsh user on mac. thoughts?

**Comment by myan9** [comment]
@jesusprubio  do you still have this problem? It might have been solved.

**Comment by jesusprubio** [comment]
Same problem :(

![image](https://user-images.githubusercontent.com/2753855/59185052-cab4fb80-8b6f-11e9-9656-e30474a47424.png)

Is it working for you with zsh in Mac OS X?

**Comment by myan9** [comment]
> Same problem :(
> 
> ![image](https://user-images.githubusercontent.com/2753855/59185052-cab4fb80-8b6f-11e9-9656-e30474a47424.png)
> 
> Is it working for you with zsh in Mac OS X?

yes zsh always works for my Mac :(

**Comment by jesusprubio** [comment]
I'll check in a Mac OS X to confirm that it only happens on Linux.

**Comment by myan9** [comment]
Thanks!

**Comment by carlosedp** [comment]
I'm having some problems using zsh on Mac:

```
~❯
pwd
11:21:00 AM
error: Too many arguments. Expected only the shell type.
See 'kubectl completion -h' for help and examples
Error: Unsupported shell type: "/usr/local/bin/zsh"
```

Zsh is installed with homebrew.

**Comment by starpit** [comment]
thanks! we'll check this out again.
