### ISSUE TITLE
`k status --all` doesn't seem right

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1461]
According to the usage of `k status` command, I found the following behaviors unexpected. 

- `k status --all`
Expect: show all the resources across namespaces
Current: only show all the resources in the **default namespace** (the namespace set in the context) of the all cluster.

- `k status pods`(or other resources)
Current: When there's no such resource found, this returns an empty full-width table with a header. 
<img width="1196" alt="Screen Shot 2019-05-22 at 2 18 24 PM" src="https://user-images.githubusercontent.com/21212160/58198568-7d461c80-7c9c-11e9-9943-afab3b70957f.png">

For reference: 
```
 const usage = command => ({
  command,
  strict: command,
  docs: 'Check the deployment status of a set of resources',
  onlyEnforceOptions: true,
  optional: [
    { name: 'file|kind', file: true, positional: true, docs: 'A kubernetes resource file or kind' },
    { name: 'resourceName', positional: true, docs: 'The name of a kubernetes resource of the given kind' },
    { name: '--final-state', hidden: true }, // when do we stop polling for status updates?
    { name: '--namespace', alias: '-n', docs: 'Inspect a specified namespace' },
    { name: '--all', alias: '-a', docs: 'Show status across all namespaces' },
    { name: '--multi', alias: '-m', docs: 'Display multi-cluster views as a multiple tables' }
  ],
  example: `kubectl ${command} @seed/cloud-functions/function/echo.yaml`
})

```

**Comment by myan9** [comment]
Except from bugs, we have so few tests for `k status` command. Not only lacking functional tests, but also lacking electron tests. (We only test this command in headless mode.)

**Comment by starpit** [comment]
no longer relevant in the latest code base https://github.com/kui-shell/plugin-kubeui
