### ISSUE TITLE
Excessive spacing in CLI when "command not found" (webpack only)

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [IBM/kui#1494]
Typing an invalid command in the CLI in webpack will display the "Command not found" error but inserting a full screens worth of space above it.   This is accompanied by the console error
```
client.js:179 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at Function.getSize (client.js:179)
    at Resizer.resize (client.js:195)
    at eval (client.js:162)
```

**Comment by starpit** [comment]
thanks for the bug report. is this with or without the proxy?

**Comment by joshuaauerbachwatson** [comment]
In our case, there is no proxy.   I reproduced the problem with the standard kui build (in which there is a proxy but not necessarily properly configured).   In that case, "Command not found" turns into "Internal Error" but the excessive spacing occurs in the same way and the console contains the same uncaught error.

**Comment by joshuaauerbachwatson** [comment]
I guess you meant whether the proxy server is running.   So that would be "no" in both cases.   In the kui build the proxy support plugin is present, in ours not.

**Comment by starpit** [comment]
confirmed. this is a regression in the bash-like catchall registration. when in browser-no-proxy mode, the pty-based catchall should not be registered.

we should add a hasProxy attribute to the Capabilities model. the plugin-proxy-support will govern this capability, and the bash-like catchall registration code can use hasProxy as a guard.

thanks again for the bug report.
