### ISSUE TITLE
can't deploy actions in a recursive composition by compose

### ISSUE THREAD

**Issue by myan9** [IBM/kui#150]
Steps to reproduce the error:
1. REPL: compose comp5 -t @demos/try.js
2. EDITOR: click deploy button
3. comp5 was deployed but the action was not.

**Comment by myan9** [comment]
I looked at the debug info behind this issue for a while and I found that the deploy button actually triggered `app udpate -r`, and the problem seemed caused by a wrong require file path in edit-amd.ts.

**Comment by starpit** [comment]
superceded by #334
