### ISSUE TITLE
ascii-to-table is buggy

### ISSUE THREAD

**Issue by starpit** [IBM/kui#1572]
e.g.

```
ibmcloud ks cluster-get mycluster
```

the output is truncated

**Comment by myan9** [comment]
another example:
When I clicked a bash script, I got `run xxx.sh` command issued (maybe a separate bug?), and the partial output is in the following screenshot 
![Screen Shot 2019-06-04 at 11 36 03 AM](https://user-images.githubusercontent.com/21212160/58894396-eaf04080-86bf-11e9-8dd4-0a651e3645cb.png)
