### ISSUE TITLE
markdown file doesn't scale properly in sidecar

### ISSUE THREAD

**Issue by myan9** [IBM/kui#159]
e.g. README.md
![screen shot 2019-01-07 1 27 55 pm](https://user-images.githubusercontent.com/21212160/50785929-104b6080-1280-11e9-8b49-7ae842358708.png)

![screen shot 2019-01-07 1 28 24 pm](https://user-images.githubusercontent.com/21212160/50785960-26f1b780-1280-11e9-9180-c57fce3159fc.png)

**Comment by starpit** [comment]
the `marked` npm that we use to render markdown as HTML does not seem to support float:right images well.
