### ISSUE TITLE
pty application mode sizing issue

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1646]
The size of pty application mode is incorrect. 

case 1. typed git branch and got the following result: it should be full-sized rather than a slim column
![Screen Shot 2019-06-10 at 10 04 18 AM](https://user-images.githubusercontent.com/21212160/59200847-229b3480-8b67-11e9-8d95-c423fce04bc6.png)

case 2.  typed git log and got the following result: the error is like above, notice that the color is different on the right side. (it might be hard to tell due to the colors of two backgrounds are similar)
![Screen Shot 2019-06-10 at 10 03 12 AM](https://user-images.githubusercontent.com/21212160/59200816-1020fb00-8b67-11e9-99bf-4d2531a829e0.png)

**Comment by starpit** [comment]
the second screenshot isn't an alt buffer. also, is it buggy? i can't spot the bugs in the second screenshot.

for the first, can you provide some more context as to how you get to that state after a fresh reload of kui? thanks

**Comment by myan9** [comment]
> the second screenshot isn't an alt buffer. also, is it buggy? i can't spot the bugs in the second screenshot.
> 
> for the first, which command is this? it doesn't look like alt buffer mode, either. also, can you provide some more context as to how you get to that state after a fresh reload of kui? thanks

Thanks! Updated the description

**Comment by starpit** [comment]
thanks. interesting, i have yet to be able to replicate these.

**Comment by starpit** [comment]
i wonder if this is a bash (me) versus zsh (the filer of this bug) issue?

**Comment by myan9** [comment]
> i wonder if this is a bash (me) versus zsh (the filer of this bug) issue?

@jesusprubio have you seen the issue in your zsh?

**Comment by jesusprubio** [comment]
> > i wonder if this is a bash (me) versus zsh (the filer of this bug) issue?
> 
> @jesusprubio have you seen the issue with zsh?

My outputs:

![image](https://user-images.githubusercontent.com/2753855/59588800-bc735c00-90e8-11e9-8b2e-cdf32e4f85cc.png)

![image](https://user-images.githubusercontent.com/2753855/59588873-e0cf3880-90e8-11e9-8466-4c24c5be567e.png)

**Comment by myan9** [comment]
update: still see this issue
![Screen Shot 2019-07-30 at 4 09 46 PM](https://user-images.githubusercontent.com/21212160/62161551-7f53d980-b2e4-11e9-91db-e48e37f17809.png)

**Comment by myan9** [comment]
update: this issue has gone
<img width="1680" alt="Screen Shot 2019-07-31 at 2 36 06 PM" src="https://user-images.githubusercontent.com/21212160/62238225-8dffc680-b3a0-11e9-8822-1a39a719f3c8.png">
