### ISSUE TITLE
table pollers should stop polling, or reduce polling frequency more intelligently

### ISSUE THREAD

**Issue by starpit** [IBM/kui#1677]
- [x] no backoff over time
- [ ] when the repl table scrolls off viewport, it continues to poll
- [x] when the sidecar tab is switched away, or when the sidecar entity is entirely replaced, it continues to poll
- [ ] when the sidecar entity is entirely replaced

**Comment by myan9** [comment]
Update:  
- [x]  no backoff over time
- [ ]  when the repl table scrolls off viewport, it continues to poll
- [x]  when the sidecar tab is switched away, it continues to poll
- [ ]  when the sidecar entity is entirely replaced

_(marked solved issues)_
