### ISSUE TITLE
Browser version - Repeated sidecar tabs

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1678]
Steps to reproduce:

1.  Build KUI browser version
2. `kubectl get pods -n <namespace>`
3.  Click a pod, sidecar renders
4.  See multiple instances of `containers` and `conditions` tabs

<img width="1694" alt="Screen Shot 2019-06-12 at 3 15 05 PM" src="https://user-images.githubusercontent.com/26075187/59379595-07762380-8d25-11e9-8002-eec27469ffd1.png">

**Comment by myan9** [comment]
We might have seen the same issue, so I post it as a supportive material. I got a crazier number of repetitions, and all the sidecar button at the right corner (trash bin, screenshot, and sidecar close button) were hidden by the overflow.
![Screen Shot 2019-06-12 at 4 34 24 PM](https://user-images.githubusercontent.com/21212160/59384473-4198f280-8d30-11e9-8db9-854e2825347a.png)

**Comment by starpit** [comment]
this should be fixed now
