### ISSUE TITLE
Browser version - proxy reporting missing electron module

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1679]
<img width="982" alt="Screen Shot 2019-06-12 at 3 18 47 PM" src="https://user-images.githubusercontent.com/26075187/59380323-d696ee00-8d26-11e9-9b3a-ec6d790549e9.png">

**Comment by starpit** [comment]
i believe that this one has already been resolved by https://github.com/IBM/kui/pull/1658 (merged two days ago, so it is understandable that your testing did not capture this recent fix)
