### ISSUE TITLE
fsh remnants

### ISSUE THREAD

**Issue by myan9** [IBM/kui#168]
**1. outdated bin in the top-level package.json**
https://github.com/IBM/kui/blob/3ebbbad0a3e8797423328ce93299da9724d66ef7/package.json#L6-L8

**2. outdated dist/bin/kui**
https://github.com/IBM/kui/blob/3ebbbad0a3e8797423328ce93299da9724d66ef7/dist/bin/kui#L23-L32

**Comment by starpit** [comment]
i think dist/bin/kui is no longer in use. it was intended to provide a hidden shell script that could be used with a platform build (e.g. a macOS double-clickable binary)
