### ISSUE TITLE
Browser version - confusing UX with pod status in sidecar?

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1685]
Steps to reproduce:

1.  Launch browser version
2.  `kubectl get pods -n <namespace>`
3.  Select one of your pods, note the pod status in the table.  Click the pod.
4.  Sidecar loads, go to Status tab.
5.  The sidecar briefly shows `Pending` while KUI is figuring out the pod status.

`Pending` is a valid phase state in Kubernetes, using `Pending` as a loading state will be confusing to the user.  Suggest KUI design team use a different loading state behavior instead.

**Comment by starpit** [comment]
i think this one has been resolved, not ideally, but resolved for now: the sidecar tables are not watch tables. #2234
