### ISSUE TITLE
Browser version - new tabs show previous command label and tabs can't be closed?

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1686]
Steps to reproduce:

1. Launch web version
2. In initial tab, run a command like `kubectl get pods -n <namespace>`
3. Open a new tab
4.  The command from step 2 is injected as text under the `[2]` tab icon.  Is there a purpose for that?

<img width="199" alt="Screen Shot 2019-06-13 at 9 19 02 AM" src="https://user-images.githubusercontent.com/26075187/59435764-515e1880-8dbc-11e9-80b0-f1283660a0aa.png">

---

Is there a way to close tabs to clean up my environment? I don't see a button that closes the tab.

**Comment by myan9** [comment]
Thanks! We currently don't have the button to close tabs, but it's coming soon. In local app, you can use shortcuts `cmd(or ctrl)+w`  to close the tab, but in browser mode, the shortcut will probably close your browser tab instead.
The first part of your issue should have been solved in our new version. Thank you!

**Comment by starpit** [comment]
this should be resolved now, with the updated tab UI.
