### ISSUE TITLE
Browser version - 'kubectl help' returns a dom object

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1687]
<img width="709" alt="Screen Shot 2019-06-13 at 9 21 31 AM" src="https://user-images.githubusercontent.com/26075187/59435939-ac900b00-8dbc-11e9-80c4-0b9456e45141.png">

**Comment by myan9** [comment]
Thanks for reporting the issue! 
The first thing I noticed here is that `kubectl help` should return the same kui usage UI as `kubectl --help`. However, the local app shows the plain result from kubectl instead. 
The second thing is that, we shouldn't return dom element in proxy server side.

**Comment by myan9** [comment]
Thanks! This should be fixed by https://github.com/IBM/kui/pull/1746. 

![Screen Shot 2019-06-18 at 4 38 10 PM](https://user-images.githubusercontent.com/21212160/59718213-a8faea80-91e7-11e9-80c7-d7d6adb58382.png)
