### ISSUE TITLE
Browser version - tabs share command history

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1688]
Steps to reproduce:

1.  Launch web version
2.  Initial tab - enter a command
3.  Open a new tab, press up on command line.  The command from tab 1 is returned.
4.  Enter a different command in tab 2.
5.  Go back to tab 1, press up.  The command from tab 2 is returned.

---

I think the user will expect that command history is isolated per tab, similar to how a terminal would work.

**Comment by myan9** [comment]
Thanks! @ruanxianzhi has a draft PR https://github.com/IBM/kui/pull/1508 trying to solve this issue.

**Comment by showeimer** [comment]
@myan9 awesome!  I'll close this issue as a duplicate then.
