### ISSUE TITLE
Browser version - result is displayed as column header when using grep

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1689]
<img width="508" alt="Screen Shot 2019-06-13 at 9 25 44 AM" src="https://user-images.githubusercontent.com/26075187/59436280-52437a00-8dbd-11e9-8124-48e6f78ad4d7.png">

**Comment by starpit** [comment]
i think we can roll this one into the fix for #2163

**Comment by starpit** [comment]
fixed by #2163
