### ISSUE TITLE
Browser version - pod table status does not match sidecar

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1690]
Sidecar should say the pod status is `Running` in this instance.

<img width="1147" alt="Screen Shot 2019-06-13 at 9 27 33 AM" src="https://user-images.githubusercontent.com/26075187/59436429-98004280-8dbd-11e9-9b69-0aad5aafb8d3.png">

**Comment by myan9** [comment]
I think this is because we are currently using 2 table watching mechanism. We'll try to solve this by enhancing the table watcher. Thank you!

**Comment by starpit** [comment]
fixed by https://github.com/kui-shell/plugin-kubeui/pull/207
