### ISSUE TITLE
Browser version - responsiveness issues with tables

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1694]
<img width="874" alt="Screen Shot 2019-06-13 at 9 37 18 AM" src="https://user-images.githubusercontent.com/26075187/59437105-e95d0180-8dbe-11e9-978b-c46cfd43fd0a.png">

**Comment by myan9** [comment]
This issue might have been fixed. Could you confirm this with the latest version? Thank you!

**Comment by starpit** [comment]
oh, nevermind! the fix is on one of my WIP branches, not yet merged. i'll merge it in shortly.
