### ISSUE TITLE
Browser version - browser console has lots of logging and errors

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1695]
Many errors are shown in the browser console, but I won't make separate issues for each.  

I'm not able to reproduce today, but previously I would see a lot of `....... skipping` type messages in the browser.  

It would be nice to resolve the errors and reduce or eliminate the logging, many times we ask our users to investigate the browser console for errors when troubleshooting problems, and reducing all of this will help us find and resolve issues for our customers more quickly.

<img width="463" alt="Screen Shot 2019-06-13 at 9 38 48 AM" src="https://user-images.githubusercontent.com/26075187/59437392-85870880-8dbf-11e9-96cb-1f8ab92d364c.png">

**Comment by myan9** [comment]
Thanks! We use Debug as our debug logging mechanism, you can see them by enabling `localStorage.debug=*` The console errors you see are real errors. We'll work on this. Thanks!

**Comment by starpit** [comment]
i believe that most of these have been resolved. i'll close this one. if you find specific errors in the latest code, can you open one for each class of error log you are seeing?
