### ISSUE TITLE
G11N support

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1696]
Globalization support needed to allow for non-English users to be able to fully use KUI.  Currently strings are hard-coded in English.  Need a solution to externalize strings into separate files or allow product teams to override string values.

**Comment by myan9** [comment]
Actually...So far I only found electron menu text and some sidecar tab titles are hardcoded in English... I tried a Chinese kubectl and it worked pretty well in Kui...

![image](https://user-images.githubusercontent.com/21212160/61488792-1892ff80-a977-11e9-8d1d-7b7df90e8882.png)

**Comment by starpit** [comment]
i think we have a pretty good handle on this now. i'll close this issue, and we can open more specific issues for gaps as we find them.
