### ISSUE TITLE
Need help - Sample plugin fails to install

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1712]
Following the directions here:  https://github.com/IBM/kui/tree/master/packages/kui-builder/examples/plugin-sample

I copied the `plugin-sample` directory from that location and placed it in the top level `plugins` directory, and then ran `npm run compile` in the root directory as indicated by directions.

Aftewards, I `cd clients/default` and tried rebuilding the proxy and webpack `npm run build:proxy` and `npm run build:webpack`.

I noticed that one of the steps fails in the `link-universe.sh` script in regards to the `plugin-sample`:

<img width="902" alt="Screen Shot 2019-06-14 at 8 53 49 AM" src="https://user-images.githubusercontent.com/26075187/59510586-132b2c80-8e82-11e9-92f5-b8e67433b170.png">

At some point during the proxy build, the `plugin-sample` in the top level `plugins` directory gets cleared out, and just leaves behind the `.gitignore` file.

<img width="325" alt="Screen Shot 2019-06-14 at 8 55 48 AM" src="https://user-images.githubusercontent.com/26075187/59510649-3e158080-8e82-11e9-901c-4a973a2c5b0b.png">

Which then requires recopying the directory back in, in order to run the `npm run build:webpack` script. Started both containers, and loaded the web UI.  The sample commands failed with `Command not found`.

<img width="314" alt="Screen Shot 2019-06-14 at 8 57 07 AM" src="https://user-images.githubusercontent.com/26075187/59510714-6bfac500-8e82-11e9-838d-9b31904ee01a.png">

**Comment by myan9** [comment]
Thanks! This is caused by we forgot to update the plugin-sample for a while. Sorry about that!
