### ISSUE TITLE
tab bug with pexec command

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1715]
Steps to reproduce this issue:
1. type command: k get pods
2. click a pod name in the table row, expect the sidecar open, and `kubectl get pods xxxxxx -o yaml` command  shown in the next repl block
3. open a new tab
4. I saw my last `kubectl get pods xxxxxx -o yaml` command carried over to the new tab, and there's no text in the first tab

Screenshot of step 1 - 3:
![Screen Shot 2019-06-14 at 10 22 03 AM](https://user-images.githubusercontent.com/21212160/59515941-470c4f00-8e8e-11e9-8569-ea22129b25aa.png)

Screenshot of my second tab:
![Screen Shot 2019-06-14 at 10 21 58 AM](https://user-images.githubusercontent.com/21212160/59515949-496ea900-8e8e-11e9-88aa-edbcca6fc75c.png)

**Comment by starpit** [comment]
we conferred, not an issue i think
