### ISSUE TITLE
Browser and Local - Command "helm list" doesn't render correctly

### ISSUE THREAD

**Issue by jlpadilla** [IBM/kui#1721]
The command `helm list --tls` renders incorrectly.
KUI version: 2.33.0-dev.2540.20190613215140

![image](https://user-images.githubusercontent.com/4671325/59528578-aed19280-8eac-11e9-9e34-16ac645b13c9.png)

**Comment by myan9** [comment]
Thanks! Confirmed the local version has the same issue. 

![Screen Shot 2019-06-14 at 2 12 28 PM](https://user-images.githubusercontent.com/21212160/59529232-78951280-8eae-11e9-8770-ef781063103b.png)

**Comment by starpit** [comment]
thanks for the bug report! i believe that this is due to tabs showing up (sometimes) in the helm output. on it.
