### ISSUE TITLE
bash-like catchall is not registered in webpack with proxy

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1724]
It's because plugin-proxy-support preload happened after plugin-bash-like preload

**Comment by starpit** [comment]
some background for the future: kui plugins can register a preload handler which is invoked while kui initializes itself; in the preload, plugins are doing several things:

1) registering keyboard shortcuts
2) asserting capabilities to the Capabilities subsystem
3) registering views to the View subsystem

if a plugin only establishes a View if a certain Capability exists... there is a race between views; that is what you are seeing here. we will fix this by registering capabilities first; i.e. doing two passes
