### ISSUE TITLE
`kubectl get pod -w` cannot be stopped

### ISSUE THREAD

**Issue by hanqiuzh** [IBM/kui#1747]
It's nice that `kubectl get pods -w` can start a watch mode. However, currently I cannot find a way to stop the watch mode. 

- KUI keeps sending requests for watching even when I'm on a new tab (where the component for watch is not displayed).

- I tried `CTRL+c`, and it makes the watch component disappeared, but KUI is still sending requests on the back.

- I also tried on the latest KUI where I can close tabs, but even closing tabs cannot stop the watch mode.

**Comment by myan9** [comment]
Related Issue:  https://github.com/IBM/kui/issues/1456

**Comment by starpit** [comment]
this falls under the general issue of job control. there are indeed a few bits of plumbing needed to get this right, but it's on our short list!

**Comment by starpit** [comment]
also #1677

**Comment by mark-nc** [comment]
And if by "new signifier to stop the watching process" you mean some visual button or something for the user to click, that should be displayed conditionally only on result tables that are actively polling as often a user may forget as they scroll through the pane which result tables were initiated with an implied watch poll with stopping to study each command in the history.  It should be easy to tell at a glance that a results table is polling and have the ability to stop that or pause that.

I expect the designers have standard idiom to use for this kind of thing.
