### ISSUE TITLE
is there a way to clear history?

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#179]
the `history` command doesn't have a way to clear itself (eg `history -c`)

```
> history -h
List current history, optionally filtering by a given string.

Examples:
   history              list the most recent 20 commands
   history <N>          list the most recent N commands
   history <N> <str>    filter the most recent N commands, showing only those that contain the given string
   history <str>        ibid, but using the default of N=20
```

**Comment by starpit** [comment]
`history purge` should work for this. we should change this to be `history -c` as you have suggested!

**Comment by rabbah** [comment]
Thx. Would be useful to have in the help. Happy to send a Pr.

**Comment by starpit** [comment]
should be done with #184 

![image](https://user-images.githubusercontent.com/4741620/50975084-b387ba00-14ba-11e9-9368-4c89031690d2.png)
