### ISSUE TITLE
feat: `export FOO=bar` should modify the shell process's env

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#180]
this doesn't work - should it?
```
> export MSG=hello
> echo $MSG
```

**Comment by starpit** [comment]
this is a good feature request. the bash-like plugin uses the ![https://github.com/shelljs/shelljs](shelljs) to exec the subprocess. this is done in an isolated sub-shell, hence env vars do not persist as you would expect.

we could add support for this, i think it's a reasonable request!

**Comment by starpit** [comment]
if we add this support, we'd have to be careful to make sure things like `export FOO="$BAR baz"` work, so maybe doing the assignment using shell.exec (as we do now), but add an `echo $FOO` and use that output value in the process.env.FOO=xxx assignment. anyway, it's not a trivial work item, but also not a huge one

**Comment by starpit** [comment]
also, we should consider if we can support this in browser mode; that might be kinda neat.

**Comment by rabbah** [comment]
ran into this again - also tried `source .env` which doesn't work because `source` is a composer command. I'll open a separate issue for that?

**Comment by starpit** [comment]
yes thanks for catching that. we should eliminate all such collisions in favor of their bash interpretation.
