### ISSUE TITLE
npm install fails 

### ISSUE THREAD

**Issue by objectiveous** [IBM/kui#1800]
✓ plugin	plugin-wskflow
error scanning for client-required plugins { Error: Cannot find module '@kui-shell/core/package.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/Users/kenpo/Projects/revans2/kui/build/packages/app/src/core/plugins.js:287:61)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kenpo/Projects/revans2/kui/build/packages/app/src/core/plugins.js:19:58)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
TypeError: Cannot read property 'plugins' of undefined
    at Object.<anonymous> (/Users/kenpo/Projects/revans2/kui/build/packages/app/src/core/plugins.js:296:76)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kenpo/Projects/revans2/kui/build/packages/app/src/core/plugins.js:19:58)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kui-shell@2.0.5 compile: `MONOREPO_MODE=true CLIENT_HOME=./clients/default ./packages/kui-builder/bin/compile.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kui-shell@2.0.5 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by myan9** [comment]
Thanks for the bug report! Could you give us some context about your platform?

**Comment by dove-young** [comment]
I got similar error on RHEL 7.6 

```
[root@agentavtone-masterone ~]# git clone git@github.com:IBM/kui.git
Cloning into 'kui'...
remote: Enumerating objects: 205, done.
remote: Counting objects: 100% (205/205), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 47484 (delta 89), reused 106 (delta 67), pack-reused 47279
Receiving objects: 100% (47484/47484), 15.03 MiB | 21.03 MiB/s, done.
Resolving deltas: 100% (35261/35261), done.
[root@agentavtone-masterone ~]# cd kui                                                                           [root@agentavtone-masterone kui]# ls
bin           clients          docs        LICENSE       package-lock.json  plugins    tools                     CHANGELOG.md  CONTRIBUTING.md  lerna.json  package.json  packages           README.md  tsconfig.json
[root@agentavtone-masterone kui]# ls bin
kubectl-kui  kubectl-wsk  kui  pack.sh  watch-webpack.sh
[root@agentavtone-masterone kui]# export PATH=$PWD/bin:$PATH
[root@agentavtone-masterone kui]# npm install
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the
 number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN lifecycle @kui-shell/builder@5.1.0~preinstall: cannot run in wd %s %s (wd=%s) @kui-shell/builder@5.1.0 i
f [ ! -d build ]; then mkdir build; fi && touch ./build/kui-dist-init.js /root/kui/node_modules/.staging/@kui-she
ll/builder-4849bd60
kui-shell@5.1.0 /root/kui
├─┬ @kui-shell/core@5.1.0

... ... 

├── tmp@0.1.0
├── typescript@3.6.4
└── uuid@3.3.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arc
h":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.10.0-957.12.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! path /root/kui/node_modules/@kui-shell/builder/build/kui-dist-init.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/root/kui/node_modules/@kui-shell/builder/build/kui-dis
t-init.js'
npm ERR! enoent ENOENT: no such file or directory, chmod '/root/kui/node_modules/@kui-shell/builder/build/kui-dis
t-init.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /root/kui/npm-debug.log
[root@agentavtone-masterone kui]#
```

**Comment by starpit** [comment]
hello @dove-young thanks for the bug report!

i see two potential issues:

1) a permissions issue, which may be the result of running as root?
> cannot run in wd %s %s (wd=%s)

2) i see from your error log that you may be using node v6.17.1. there is currently a node version 8 or higher minimum requirement for building kui. we attempted (apparently without success) to express this dependence in the `engine` spec in the top-level package.json. we will investigate that.

**Comment by dove-young** [comment]
@starpit there is nothing been mentioned in your repo documents.

**Comment by starpit** [comment]
closing, as we now enforce minimum node/npm requirements #3321
