### ISSUE TITLE
console error after openwhisk invoke

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#181]
steps to reproduce: create a hello world actions and invoke it.

<img width="1545" alt="image" src="https://user-images.githubusercontent.com/4959922/50949127-03429300-1473-11e9-9410-ad0c2f534f4d.png">

```
openwhisk-core.ts:540 TypeError: Cannot read property 'name' of undefined
    at Object.invoke (openwhisk-core.ts:965)
    at entity (openwhisk-core.ts:537)
    at process._tickCallback (internal/process/next_tick.js:68)
```

**Comment by starpit** [comment]
thanks for the bug report! i don't see this, either with the currently released build (2.0.3-dev.207.20190109195814) or with master. hmm...

**Comment by rabbah** [comment]
i git cloned fresh last night - will wipe and retry at the next opportunity.

**Comment by starpit** [comment]
hopefully addressed?
