### ISSUE TITLE
feat: extend `ls` to use the editor for more file types

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#182]
is it possible to use the built-in editor to edit a local file? 

(if you run `vi` it hangs the shell and `emacs` fails with `emacs: standard input is not a tty`)

**Comment by starpit** [comment]
indeed vi and emacs will require some sort of TTY support

`edit /path/to/file` should work.

the output of `ls` has some rules as to which files should open read-only and which should open in the editor; currently e.g. YAML and JSON files will open in the editor when clicked on, whereas markdown will open in read-only mode using `marked` to render the markdown; and other random files also open read-only.

we can adjust these rules; they are implemented by the `open` command, which is hosted in the bash-like plugin; the current location is: https://github.com/IBM/kui/blob/master/app/plugins/modules/bash-like/src/lib/cmds/open.ts

**Comment by rabbah** [comment]
edit will work - thanks. i noticed though that you can't use the command to edit a file unless it exists, so one has to touch the file then edit it... maybe `edit -n` to create a new file?

**Comment by starpit** [comment]
this should be mostly covered now that we have vi/emacs support
