### ISSUE TITLE
feat: support for removing an openwhisk auth + host

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#183]
auth and host allow you to set new values but not remove old values to clean up; is there a way to remove either within the shell?

**Comment by starpit** [comment]
not yet! we should add a `wsk auth delete` command

**Comment by rabbah** [comment]
a little `x` on each available auth or host to click (when viewing a list) and delete would be nice too.

**Comment by starpit** [comment]
yes, we have this for the `contexts` command (part of the k8s plugin); we should do the same for openwhisk contexts

**Comment by starpit** [comment]
![image](https://user-images.githubusercontent.com/4741620/50989206-b693a200-14dc-11e9-91a1-867a6687a507.png)

**Comment by rabbah** [comment]
as an extension of this issue, when an auth becomes invalid, should it be removed automatically?

@starpit i didn't follow your comment above about k8s contexts --- does this mean you can delete a kube context from a list by clicking an icon in the list? or using a command like `"kube delete context"`?

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/oui/issues/57
