### ISSUE TITLE
Switch between pod view and logs view ?

### ISSUE THREAD

**Issue by lemaral** [IBM/kui#1857]
Really nice work again :)
I cannot seem to find a way to switch to logs view directly from pod view (instead of using kubectl logs). Is it planned, can it be done (maybe I could contribute) ?
Thanks

**Comment by myan9** [comment]
Thanks @lemaral! 
The current way of switching between pod and logs view in Kui's Sidecar is by clicking the Container Tab (located in the bottom-strip of sidecar), and clicking the Image in the Containers table. 
Are you suggesting an easier way to switch to logs view? 🤔

**Comment by lemaral** [comment]
Thanks ! I missed it, I was looking for something more obvious (to me!) e.g. a Logs entry in the bottom-strip of the sidecar but now that I know how to get to it that's ok :)
Maybe I'll submit a PR later to show what I would expect.
