### ISSUE TITLE
Show kubectl config current-context in prompt ?

### ISSUE THREAD

**Issue by lemaral** [IBM/kui#1859]
Is it planned to show $(kubectl config current-context) instead of kui> prompt ? Maybe add a prompt callback to the plugin interface ?
This is very useful to show evidence of the kubeconfig and avoid mistakes.
Thanks!

**Comment by myan9** [comment]
Thanks @lemaral ! It's a nice feature!

**Comment by starpit** [comment]
agreed, thanks for the suggestion!

**Comment by starpit** [comment]
we should have this very soon. moving here: https://github.com/kui-shell/plugin-kubeui/issues/231
