### ISSUE TITLE
In default kui tables, multi-line text is returned in multiple rows

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1864]
<img width="640" alt="Screen Shot 2019-07-02 at 9 37 56 AM" src="https://user-images.githubusercontent.com/26075187/60517200-4147a380-9cad-11e9-9245-8a999692f19b.png">

^- should render as a single row

**Comment by starpit** [comment]
thanks! can you provide an example command? even if it's `cat somefile.txt` that exhibits the problem that would be helpful!

**Comment by ydarias** [comment]
Hello @showeimer, could you give us some hint about how to reproduce the error?

**Comment by starpit** [comment]
should no longer be an issue, as we have deprecated any attempt to auto-table PTY output, for now.
