### ISSUE TITLE
Default kui tables - truncated cell text cannot be hovered on to see full text

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1866]
<img width="144" alt="Screen Shot 2019-07-02 at 11 43 04 AM" src="https://user-images.githubusercontent.com/26075187/60526614-af489680-9cbe-11e9-97da-47ae6ae40130.png">

Can be easily solved by adding a HTML `title` attribute:

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title

**Comment by starpit** [comment]
nice, thanks!
