### ISSUE TITLE
KUI auto-focus issues

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#1909]
We are generating interactive tables that have overflow menus and carbon pagination.  Whenever something is clicked KUI is forcing focus back to the command prompt so we aren't able to use the custom interactions.

Also this behavior basically makes KUI almost non-accessible for keyboard users.

**Comment by starpit** [comment]
thanks for reporting this. kui currently uses plain HTML `<input>` elements for its terminal input. as a result, its focus behavior diverges from what one would expect from a normal terminal, and in a few ways.

for example, text selection grabs focus; this is the way browsers behave, but not the way terminals behave
 
or: clicking outside of the current input element also removes focus from that element; even if there is nothing else (from the perspective of a terminal) that should receive focus. this is just the default behavior of browsers.

kui attempts to work around some of these. i'm not sure how to fix this, without further diverging from the expected terminal focus behaviors. @ydarias ?
