### ISSUE TITLE
activation list with package name and entry point

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#1937]
Activation list currently shows only the action name and not if an action is inside a package. It would be helpful to see `package-name/action-name`.

Additionally, it might be useful to also show the function's entry point (or "main"). An activation may have the `entry` annotation on the activation record which can be used for this purpose, if present.

For example for an action `a` in a package `p` with entry `m` the activation list could show `p/a.m` instead of just `a` as it does now.

**Comment by starpit** [comment]
thanks! yes, this has been a long-standing gap. i think the newer designs have the space for this information.

i think we can remove the "$ per million"? then, we could shift the "started on" to sit in place of the $ per million text; then, we could move the activation ID to where the started on texts its. and then place the package name in the place the activation ID sits... thoughts?

![image](https://user-images.githubusercontent.com/4741620/61178012-229cb300-a5b1-11e9-9292-d537d98f6451.png)
