### ISSUE TITLE
we should remove @typescript-eslint/no-parameter-properties

### ISSUE THREAD

**Issue by myan9** [IBM/kui#1986]
It's a nice feature. We shouldn't enforce developers not to use it. 

Reference: https://www.typescriptlang.org/docs/handbook/classes.html#parameter-properties

**Comment by starpit** [comment]
yes, i think we're probably ok enabling this part of typescript. the docs for this eslint rule state:

> Parameter properties can be confusing to those new to TypeScript as they are less explicit than other ways of declaring and initializing class members.

typescript follows other modern languages (such as scala and go) in allowing code to express class attributes within the constructor, to avoid the silly repetitions of field definition, variable declaration, and the copy code from one to the other in the constructor.

**Comment by starpit** [comment]
thougths @abdonrd ?

**Comment by abdonrd** [comment]
Reference to the [`@typescript-eslint/no-parameter-properties` rule documentation](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-parameter-properties.md).

My thought is to avoid personalizing the config, and try to keep the recommended config.
But it is up to you!
