### ISSUE TITLE
UI bug when closing the sidecar

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2044]
**Describe the bug**
When the sidecar is closed, NAMESPACE on the right bar seems incorrect. 

**Video**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/21212160/61461846-91766500-a93f-11e9-8717-e235e36fec23.gif)

**System**

- Kui version: 2.34.0
- Operating system: MacOS

**Comment by starpit** [comment]
should be fixed by #2062
