### ISSUE TITLE
Specifying bodyCss value in theme.json is not injected into webpack generated index.html

### ISSUE THREAD

**Issue by mark-nc** [IBM/kui#2047]
**Describe the bug**
The new style, `kui--bottom-input`, can be specified as the value for `bodyCss` in the theme.json file for a custom client using webpack. (See this PR https://github.com/IBM/kui/pull/1956) There is code that looks for that style class when rendering the main KUI panel, but that value is not injected into the style list on the <body> tag when the webpack build generates the index.html file.

**Steps to reproduce the behavior**

1. Follow the steps listed here for building a custom client using webpack
2. Go to the client theme/theme.json file and add `"bodyCss": "kui--bottom-input",` to the theme file
3. Build the webpack
4. Display the KUI UI and notice there is no input area at the bottom of the UI panel (and inspect the index.html source to see the `kui--bottom-input` style is not on the <body> tag.
5. If you add that style class to the <body> tag once the page is loaded (via the browser Developer Tools editor), the bottom input area will display, but it does not recognize the user hitting the Enter key after typing a command (probably because that DOM element is not listening for the Enter event if it gets created after the page loads).

**Expected behavior**
The `cssBody` theme.json value should be injected into the generation of index.html by the webpack build.

**System**

- Kui version: latest @dev version
- Operating system: Webpack built on MacOS Mohave

**Comment by myan9** [comment]
Confirmed: bodyCss theme.json injection also doesn't work for electron custom client.

**Comment by starpit** [comment]
@myan9 is working on a solution to this today.
