### ISSUE TITLE
shouldn't use 3s for the initial table polling rate for resource creation and deletion

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2079]
**Describe the bug**
shouldn't use 3s for the initial table polling rate for resource creation and deletion

**Steps to reproduce the behavior**

1. Type `k delete pods [pod name]`
2. See the status changing very slow

**Expected behavior**
The initial table polling rate for resource creation and deletion should be very fast

**Code snippets**
regression from https://github.com/IBM/kui/pull/1922. I shouldn't change the watcher to use default table polling rate everywhere.

**System**

- Kui version: latest dev
- Operating system: macOS

**Comment by starpit** [comment]
3s seems ok, but the time for the very first poll call should be much lower. maybe use a step something like

500, 750, 1000, 1000, 3000, 3000, 5000

so that in the steady state we poll once every 5s?

**Comment by starpit** [comment]
maybe the final poll interval should be a theme setting, so that clients can adjust the steady state polling frequency?

**Comment by myan9** [comment]
> maybe the final poll interval should be a theme setting, so that clients can adjust the steady state polling frequency?

We've already had `theme.tablePollingInterva`l. We just need to make sure to use this as steady state polling interval. https://github.com/IBM/kui/blob/master/packages/app/src/webapp/views/table.ts#L42
