### ISSUE TITLE
delete button for kube resource in sidecar looks ambiguous 

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2150]
**Describe the topic**
The Delete button for Kubernetes resource in Sidecar looks ambiguous to me. 
1. The text is `Delete` only and it's not clear what would be deleted.
2. The delete button makes me feel like it's a button used to remove the notification: You're in read-only view mode, since, in general, a notification can be closed or removed.
3. The delete operation should ask user for confirmation

**Your suggestions for this topic**
- We could use `Delete this resource` as the text of the delete button
- We could use the new notification widget to ask for confirmation
- We could show the command of deleting the resource in REPL and close the sidecar, waiting users to hit Enter to execute the deletion command
 

**Screenshots**
![image](https://user-images.githubusercontent.com/21212160/62057367-8815b400-b1ed-11e9-9125-e171f4325d74.png)

**Comment by ydarias** [comment]
I thought we were going to use the bin icon at the header, like this design?

![image](https://user-images.githubusercontent.com/948946/62282399-c90d0300-b44f-11e9-910e-a80bc19d91a5.png)

**Comment by starpit** [comment]
we could! first, we decided to place it in the "toolbar stripe" rather than the top "window header" stripe. once there, we need to decide i think whether we want to be consistent with the toolbar buttons or not: always text? always icons? is a mix ok?

e.g. we have, in other views,
```
Save | Restore
```
