### ISSUE TITLE
Electron build for external clients fails to include client plugins

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [IBM/kui#2178]
**Describe the bug**
We are attempting to use the latest `kui` after previously using commit  c53a093.   We consume `kui` as an external client.  With the latest `kui`, the build goes into monorepo mode during the pre-scan phase and does not pick up the plugins contributed by the external client.

**Steps to reproduce the behavior**

Create an external client as per kui instructions.  Add a plugin in the `plugins` directory.  Build it with
```
npx kui-build-electron
```
in the client directory.

**Expected behavior**
The plugin should be included.   The message 
```
compiling plugin registry (monorepo mode)
```
should _not_ be appearing.

**Comment by starpit** [comment]
hi! thanks for the bug report. since your last rebase, we have split out the webpack builder into `@kui-shell/webpack`. you may have seen this, but i thought i'd check just in case.

**Comment by joshuaauerbachwatson** [comment]
Thanks for helping with the webpack build (which was, indeed, another one of my questions about things that appeared to be blocking our rebase effort).  

To avoid confusion for anyone else reading the issue, though, I want to clarify that the issue is about the electron build, not the webpack build.   I hope you are able to reproduce from my instructions (which were a little vague).  When I get a chance I'll create a stripped down external client which will be easier to experiment with.   Who knows, I may find the error myself while doing that :).

**Comment by joshuaauerbachwatson** [comment]
The original "steps to reproduce" are misleading because if you get `@kui-shell/builder` from the production `npm` repo it will work fine.   If you use
```
npm install --save-dev @kui-shell/builder@dev
```
instead (in an otherwise minimal example with one plugin) you will see the error.   That is, the error is in github committed code but not in what is published for general use.   This is important to us because we `npm pack` kui components from our fork for use by the external client in order to control the exact content.

**Comment by starpit** [comment]
i just tried these steps on a mac, with success. could you try these steps, so at least we can verify that the baseline works for you? thanks!

```bash
cd /tmp && mkdir yo && cd yo
npm init
npm install --save-dev @kui-shell/builder@dev ; npm install --save @kui-shell/core@dev @kui-shell/plugin-k8s@dev @kui-shell/plugin-openwhisk@dev @kui-shell/plugin-editor@dev @kui-shell/plugin-core-support@dev @kui-shell/plugin-bash-like@dev @kui-shell/plugin-grid@dev @kui-shell/plugin-apache-composer@dev @kui-shell/plugin-wskflow@dev @kui-shell/plugin-tutorials@dev
npx kui-init
NO_INSTALLER=true npx kui-build-electron -- mac
open dist/electron/Kui-darwin-x64/Kui.app
```

**Comment by joshuaauerbachwatson** [comment]
It did not work for me; rather, it fails in exactly the way I am complaining about.   Notice that the `npx kui-init` step adds `plugin-sample` to the client.   It is, in fact, present in the `plugins` directory of the client.

But, the build output includes the following sequence, showing that `plugin-sample` was not picked up by the build.
```
compiling plugin registry /Users/joshuaauerbach/kui-electron-tmp
  ✓ plugin	plugin-apache-composer
  ✓ preload	plugin-apache-composer
  ✓ plugin	plugin-bash-like
  ✓ preload	plugin-bash-like
  ✓ plugin	plugin-core-support
  ✓ preload	plugin-core-support
  ✓ plugin	plugin-editor
  ✓ preload	plugin-editor
  ✓ plugin	plugin-grid
  ✓ plugin	plugin-k8s
  ✓ preload	plugin-k8s
  ✓ plugin	plugin-openwhisk
  ✓ plugin	plugin-tutorials
  ✓ preload	plugin-tutorials
  ✓ plugin	plugin-wskflow
```
On the other hand, if I use `@kui-shell/builder` (without the `@dev`) I get the correct behavior.
