### ISSUE TITLE
finish up proxy tests for k8s layer

### ISSUE THREAD

**Issue by starpit** [IBM/kui#2184]
@starpit will help

**Comment by myan9** [comment]
Webpack context switching test doesn't work in travis: https://travis.ibm.com/composer/kui/jobs/19345569#L2455

Locally it's good

**Comment by myan9** [comment]
helm is a bit weird in webpack too

![Screen Shot 2019-08-01 at 5 13 20 PM](https://user-images.githubusercontent.com/21212160/62329081-e27b7280-b482-11e9-99b7-9ab172dabab3.png)
