### ISSUE TITLE
weird deletion status for alpine

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2216]
**Describe the bug**
When I type to `k delete pod alpine` in kui, the table status shows **Ready** for a while and then went to **Offline**. However, if I type `k get pod  alpine` during deletion, I can see the pod in a **Terminating** status. Then, I found that `k status pod alpine` shows different result than `k get pod alpine` in the meantime of deletion.  Table watcher uses `k status`, so the weird status came from the k status command.

**Screenshots**
<img width="1125" alt="Screen Shot 2019-08-02 at 3 23 55 PM" src="https://user-images.githubusercontent.com/21212160/62394753-1e264300-b53c-11e9-9e03-9e746721017f.png">

**System**

- Kui version: latest
- Operating system:  macOS

**Comment by starpit** [comment]
this one is a bit of a mystery to me. nothing in the response from `kubectl get pod alpine -o yaml` gives any indication that the pod termination process is underway. despite this, `kubectl get pod ---watch-only` indeed shows something like

```
alpine   1/1   Terminating   0     44s
alpine   0/1   Terminating   0     75s
alpine   0/1   Terminating   0     76s
alpine   0/1   Terminating   0     76s
```

interestingly, --watch-only only ever shows "Terminating"; in contrast, the conditions for deleting nginx are more nuanced (and also reflected in the output of `k get pod nginx -o yaml`.

weird. this seems like a kube issue. i wonder if it would be resolved with a newer version of kubernetes. i'm on 1.13 server, 1.12 client. i'll try updating at least the client

**Comment by starpit** [comment]
maybe we should be using --watch-only to the stream of status updates?

**Comment by myan9** [comment]
> this one is a bit of a mystery to me. nothing in the response from `kubectl get pod alpine -o yaml` gives any indication that the pod termination process is underway. despite this, `kubectl get pod ---watch-only` indeed shows something like
> 
> ```
> alpine   1/1   Terminating   0     44s
> alpine   0/1   Terminating   0     75s
> alpine   0/1   Terminating   0     76s
> alpine   0/1   Terminating   0     76s
> ```
> 
> interestingly, --watch-only only ever shows "Terminating"; in contrast, the conditions for deleting nginx are more nuanced (and also reflected in the output of `k get pod nginx -o yaml`.
> 
> weird. this seems like a kube issue. i wonder if it would be resolved with a newer version of kubernetes. i'm on 1.13 server, 1.12 client. i'll try updating at least the client

Thanks! I'm on 1.14 server and 1.14 client, and I see the same result.

**Comment by starpit** [comment]
let's fold this under #2231
