### ISSUE TITLE
use `kubectl get --watch-only` for kui watcher

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2231]
**Describe the topic**
Currently, Kui watches the kubernetes resources deletion & creation status by polling the YAML. 
Maybe we should switch to `kubectl get --watch-only`, which may potentially help with the following issues:
1. solve issue https://github.com/IBM/kui/issues/2216, where we can't get the `Terminating` status from YAML
2. we should poll table instead of YAML, consolidating Kui's watch mechanism and boosting performance
3. avoid inventing terminology and sync with strings that kubectl provides
4. get push notification (maybe) instead of polling

Couple of things we need to solve if we want to use `kubectl get --watch-only` for Kui watcher:
1. `kubectl get --watch-only` doesn't offer the `Offline` or `Deleted` status. Users won't know the resource is deleted. However, Kui's watcher gets it for free by polling the resource. 
To help sovle this, maybe we could try launching 2 processes for kubectl deletion: `kubectl delete` and `kubectl get --watch-only`. Kui gets the `Deleted` from the first process exit and status from the second process.
2. we need to avoid losing message column of the table (maybe jsonpath could help)
3. we need to figure out if this could work with proxy

**Comment by starpit** [comment]
nicely summarized!

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/plugin-kubeui/issues/204
