### ISSUE TITLE
K8s plugin - fetching from a namespace that doesn't have any resources returns internal error

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2244]
I have a namespace called default in my cluster, whenever I try to get any kind of k8s resource from the namespace with kubectl, the `Internal Error` message is returned.  Kubectl normally returns `No resources found.`

<img width="348" alt="Screen Shot 2019-08-06 at 10 16 31 AM" src="https://user-images.githubusercontent.com/26075187/62547566-65aa1900-b833-11e9-833b-87aa37402684.png">

<img width="561" alt="Screen Shot 2019-08-06 at 10 18 45 AM" src="https://user-images.githubusercontent.com/26075187/62547708-a86bf100-b833-11e9-8974-f5951b9fd306.png">

**Comment by myan9** [comment]
Thanks for the bug report! Could you provide the kui version you're on? This issue should be covered by https://github.com/IBM/kui/pull/2238

**Comment by myan9** [comment]
You should see the following result with the latest build:
![Screen Shot 2019-08-06 at 10 23 27 AM](https://user-images.githubusercontent.com/21212160/62548080-3fd14400-b834-11e9-8374-a34ceb7441e5.png)

**Comment by showeimer** [comment]
@myan9 
    "@kui-shell/core": "^2.35.0-dev.3553.49",
    "@kui-shell/plugin-bash-like": "^0.24.0-dev.3553.49",
    "@kui-shell/plugin-k8s": "^0.35.0-dev.3553.49",

**Comment by starpit** [comment]
fixed in build 3574. can you confirm? thanks!
