### ISSUE TITLE
How extensible is kui?

### ISSUE THREAD

**Issue by abetkin** [IBM/kui#2253]
Hi you, brilliant authors of kui!

As I understand, kui is some kind of rich cli, that allows interlinked data. I like the idea very much.
Since making cli apps is quite a general need, how consumable is kui/parts of it to use from Python for example ?

**Comment by starpit** [comment]
hello, thanks for the feedback!

kui is indeed extensible in a variety of ways. the docs/dev covers e.g. the way you can build custom clients, with your own plugins (offering new commands, new views), and also your own theming.

re: python... we hadn't thought about this! do you have any particular ideas in mind? are you thinking jupyter notebooks? or from within a python REPL?

**Comment by abetkin** [comment]
Hi again, thanks for your answer!

I see that kui has some docs, but the fact that it's kind of split into plugins is even better. I think it would be useful to read code of "bash-like" plugin.

It would be nice if write some words about the architecture. Apart from the fact that it's an electron app, it looks like a regular web app, but I see that it doesn't use any major web framework. I also see that there are "models" and "views". Is it something like backbone (a web framework before react)? Does it use something for templating ([example](https://mozilla.github.io/nunjucks/). react kind of uses jsx for this)

About python: it's not related to jupyter, it is more like a cli app, I can share more details if you want. It's a single app (not client and the server. Though technically it will be a python server and a web client running on the same machine, probably communicating by rpc over websockets. But conceptually - a single app). Conceptually I imagine there will be html+css components, and I will just feed json data to them. Or maybe components defined by some template (think django/jinja2 templates or ERB templates), and I will feed objects to them
