### ISSUE TITLE
 if you click on some (not all) executable files in kui, kui executes it 

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#2254]
**Describe the topic**
clicking a file called `build.sh` causes the file to execute instead of opening the file in the sidecar for viewing as with other files.

**Your suggestions for this topic**
executable files that are not called `build.sh` will open in the sidecar for viewing as expected, but a `build.sh` will cause the file to execute. The behavior should be consistent and I suggest a (text) file should always open in the sidecar for viewing/editing.

**Screenshots**
I can provide a screenshot but this this is easy to replicate.

**Comment by starpit** [comment]
agreed. this was done for an early demo. i think we could easily just remove these two lines:

https://github.com/IBM/kui/blob/master/plugins/plugin-bash-like/src/lib/cmds/ls.ts#L122-L123
