### ISSUE TITLE
improve view for zipped openwhisk actions 

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#2255]
**Describe the topic**
if you create an openwhisk action from a zip file and click on the action in action list, you get a sidecar message which says the action can't be opened because it's a zip file.

**Your suggestions for this topic**
i think this can be improved, with possible suggestions being: kui could unzip the files locally and allow you to navigate through the archive; or it could show you a manifest of what is in the action; or perhaps there's a way to record where on the local file system the action was deployed from and navigate you there...

**Comment by starpit** [comment]
kui does have some support for zip actions. or at least it did. has the openwhisk specification changed at all? we have tests for at least one case, and kui, for this scenario, displays the main action source on "action get"

**Comment by rabbah** [comment]
action code is an attachment by default (in Apache) - so action get may not get the "zip" contents unless you request it. Otherwise the schema is the same.

**Comment by starpit** [comment]
is it possible that create and get are different? because we do have a test
https://github.com/IBM/kui/blob/master/plugins/plugin-openwhisk/src/test/openwhisk4/zip.ts

that creates a zip action, and expects to see the source in the sidecar. but, looking at that test, it doesn't ever do a get.

**Comment by rabbah** [comment]
I'd have to check the test setup - and the runtimes manifest. I will investigate a bit more and post relevant details about the kui req/res traffic.

**Comment by rabbah** [comment]
I've investigated this a bit further. If the action is created from within `kui`, then kui will show you `index.js` (or comparable for other languages). But if you create the same action from outside of `kui`, then you get a message that the action cannot be displayed because it's a binary action.

The action created from within `kui` has these annotations (which evidently won't exist for actions created outside of `kui`).

```json
{
  "binary": true,
  "wskng.combinators": [{
    "badge": "zip",
    "role": "replacement",
    "type": "action.kind"
  }],
  "file": "/path/to/f.zip",
  "exec": "nodejs:10"
}
```

**Comment by rabbah** [comment]
Is it always the "index" file that's shown? For node.js it's possible to have a different entry file (whether via a `--main somefile.somefunction` declaration or changing the `package.json` file entry for the index).

Is the sidecar view limit to just one file (namely the "index" file)? It would be nice to allow more general navigation if so of the contents.

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/oui/issues/61
