### ISSUE TITLE
Relationship with fsh shell?

### ISSUE THREAD

**Issue by epatters** [IBM/kui#226]
Thanks for starting this interesting project. I'm curious how it relates to the [fsh shell](https://github.com/ibm-functions/shell). Is it supposed to subsume and replace the shell?

**Comment by starpit** [comment]
Howdy there. Yes this repo supplants the previous one. We will indicate this better on the old repo!

**Comment by epatters** [comment]
Great, thanks. That will help people understand where you're headed.

**Comment by starpit** [comment]
i have added a deprecation notice to the ibm-functions/shell project. thanks!
