### ISSUE TITLE
output of printenv is weird in KUI

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2260]
found this output in Kui electron
![Screen Shot 2019-08-07 at 5 11 50 PM](https://user-images.githubusercontent.com/21212160/62658305-798a7380-b936-11e9-88a4-60c7b7cacd5c.png)

Build: Latest
Platform : MacOS

**Comment by myan9** [comment]
webpack mode seems good
![Screen Shot 2019-08-07 at 5 44 03 PM](https://user-images.githubusercontent.com/21212160/62660061-059e9a00-b93b-11e9-98d8-9ec4c0986824.png)

**Comment by starpit** [comment]
are you running with a DEBUG environment variable set somewhere?

**Comment by myan9** [comment]
> are you running with a DEBUG environment variable set somewhere?

I have `DEBUG=*` set in electron localStorage. I tried removing `DEBUG`, and I still got the same result. Same with @ruanxianzhi

**Comment by starpit** [comment]
i have yet to be able to reproduce this one. help wanted!

**Comment by myan9** [comment]
I tried opening Kui by `./bin/kui shell` directly, and saw no mess in my env.

I guess the mess is from npm script, since I originally opened Kui by `npm start`. Using `npm start`  to open Kui is a nice feature, but we should eliminate these npm configs and keys in package.json from `printenv`. Maybe @jesusprubio could help with us! npm master!

**Comment by starpit** [comment]
i don't think this is an issue worth fixing right now. kui isn't adding the fields, npm is. and it will only affect kui developers, not kui users.
