### ISSUE TITLE
travis test: webpack test is not waiting for electron WAIT_LAYER tests to finish

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2280]

**Comment by starpit** [comment]
but the k8s WAIT_LAYER currently only has one test, and it is a localDescribe. how can this be a problem?

**Comment by myan9** [comment]
The test in k8s WAIT_LAYER will do context switching. It writes a a new namespace into kubeconfig, and sets the current context to be the new namespace. I think it's problematic that we have such context switching test run in parallel with other tests.
