### ISSUE TITLE
Linux electron build from source produces kui with broken pty

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [IBM/kui#2283]
**Describe the bug**

Using `kui` at commit b150546, I followed the instructions to build all electron clients.   Testing `Kui-linux-x64.zip`, lots of things work but not things that cut through to the underlying shell, like `pwd`.  They hang `kui`.   The devtools console shows
```
Uncaught (in promise) Error: Cannot find module '../build/Debug/pty.node'
```
Using the downloaded pre-built linux zip (linked from the kui README), it works fine.   No pty problems.   That seems to date from about 7/23.   Perhaps it was built differently, but I followed the instructions.

**Steps to reproduce the behavior**

1.  Clone `IBM/kui`.
2.  `npm install`
3.  `cd` to the default client directory
4.  `npm run build:electron`
5.  Unzip the resulting `Kui-linux-x64.zip` on Ubuntu 18.04
6.  Execute the `Kui` binary found therein.
7.  Type `pwd`.

**Expected behavior**

As in the pre-built download: the current working directory should be displayed.

**Comment by joshuaauerbachwatson** [comment]
```
starpit 2:43 PM
for the time being you need to build each platform on its respective host. this is due to
the node-pty-prebuilt being out of date. there is a newer node-pty-multiarch-prebuilt 
that we could probably switch to, but i haven’t had time to investigate, yet

```
So, there's a way forward for the moment.  I'm setting up a Jenkins job to do linux builds for us.

In the long run, it would be nice if we could cross-compile all three platforms in a single build on a single machine and have that work on both macs and linux.   Looks like that might be coming with the `node-pty-multiarch-prebuilt` that Nick mentions.

**Comment by starpit** [comment]
i think we are good here?

**Comment by joshuaauerbachwatson** [comment]
Yes.   This has been fine for a while now.
