### ISSUE TITLE
Sidecar truncates tables and creates excess space

### ISSUE THREAD

**Issue by mark-nc** [IBM/kui#2320]
**Describe the bug**
When the sidecar is open, tables become chopped and not very useful. Weird space and scrolling is happening as well.

**Steps to reproduce the behavior**

1. Run command `kubectl get pods --all-namespaces`
2. Click on a pod to get the details sidecar
3. See behavior mentioned above.

**Screenshots**

![Screen Shot 2019-08-13 at 4 28 01 PM](https://user-images.githubusercontent.com/51764173/62975129-bac3cd00-bde7-11e9-9797-6b0cd15f326f.png)

- Kui version: latest @dev
- Operating system: any

**Comment by starpit** [comment]
which browser were you using? thanks

**Comment by starpit** [comment]
probably: the namespace column should have a not-a-name attribute
