### ISSUE TITLE
Helm sidecar status tables don't label the associated k8s resource type

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2337]
Perform a `helm get ____`, sidecar will open.

Click the status tab.

There will be various tables that correlate with the associated k8s resources in the helm release.  The tables are however not labeled, so it is confusing what type of resource each table is.

Also, some spacing would be nice between the tables.

What is this version?

<img width="61" alt="Screen Shot 2019-08-14 at 4 56 57 PM" src="https://user-images.githubusercontent.com/26075187/63055756-9e419680-beb4-11e9-8daf-2b42263585bf.png">

**Comment by showeimer** [comment]
Issue also happens with `helm status ____`

**Comment by myan9** [comment]
> The tables are however not labeled, so it is confusing what type of resource each table is.

I'm not sure I understand this ^^^.  Kui keeps and decorates the original helm output. In the following screenshot, each table has a clear title, which I think showing the resource type pretty well?  Thanks!

REPL:
![Screen Shot 2019-08-14 at 6 03 54 PM](https://user-images.githubusercontent.com/21212160/63059631-f16c1700-bebd-11e9-9e25-da9ad061e743.png)

Sidecar:
![image](https://user-images.githubusercontent.com/21212160/63059826-748d6d00-bebe-11e9-8181-b2b86dce3f81.png)

**Comment by showeimer** [comment]
@myan9 

<img width="746" alt="Screen Shot 2019-08-14 at 6 19 38 PM" src="https://user-images.githubusercontent.com/26075187/63060415-2da07700-bec0-11e9-9642-9729ac9ec4fe.png">

**Comment by showeimer** [comment]
<img width="636" alt="Screen Shot 2019-08-15 at 6 26 15 PM" src="https://user-images.githubusercontent.com/26075187/63131000-41181480-bf8a-11e9-972c-03f1bcc24b90.png">

**Comment by starpit** [comment]
agreed, for multi-tables, we should always show table titles

**Comment by rtonev** [comment]
I agree, yeah. For multiple tables in the result set we should show table titles.
