### ISSUE TITLE
Design - explore better empty states for sidecar tabs?

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2338]
Currently sidecar tabs with no data will look like this:

<img width="488" alt="Screen Shot 2019-08-14 at 5 01 15 PM" src="https://user-images.githubusercontent.com/26075187/63056090-50795e00-beb5-11e9-9973-2063e63dcdc3.png">

Maybe we can improve the design to show some kind of empty state message.

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/plugin-kubeui/issues/189
