### ISSUE TITLE
CLI help menus

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2339]
Investigate getting some design feedback on the default output styling for cli help menus.

Some issues noticed:

Table row padding
Font size seems a bit large
Output feels scattered
Tables get cut off at a weird point vertically, there's like a quarter inch of the next row showing.
Table borders only rely on the row border, so if the table is scrollable the bottom or top border will be missing.
Tables are created where not appropriate, for example:

<img width="457" alt="Screen Shot 2019-08-14 at 5 09 48 PM" src="https://user-images.githubusercontent.com/26075187/63056614-6a677080-beb6-11e9-8814-25b66a447d13.png">
<img width="862" alt="Screen Shot 2019-08-14 at 5 09 41 PM" src="https://user-images.githubusercontent.com/26075187/63056615-6a677080-beb6-11e9-8c64-27c8859f27c7.png">

**Comment by starpit** [comment]
this should be resolved now. 

1) no auto-tabularization or PTY output
2) kubectl and helm help go to sidecar
