### ISSUE TITLE
Helm command error messages are not consistent with helm cli when argument is missing

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2340]
<img width="420" alt="Screen Shot 2019-08-14 at 5 20 56 PM" src="https://user-images.githubusercontent.com/26075187/63057317-f75ef980-beb7-11e9-8696-2c2e3ea5e09e.png">
<img width="390" alt="Screen Shot 2019-08-14 at 5 20 18 PM" src="https://user-images.githubusercontent.com/26075187/63057318-f75ef980-beb7-11e9-8bc1-9414ea631d62.png">

**Comment by myan9** [comment]
This should be regression from the error handler of proxy server side. 

Electron is good.
![Screen Shot 2019-08-14 at 5 53 50 PM](https://user-images.githubusercontent.com/21212160/63059172-b0bfce00-bebc-11e9-9230-57f70d964776.png)
