### ISSUE TITLE
Helm history doesn't generate a kui table

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2341]
<img width="942" alt="Screen Shot 2019-08-14 at 5 22 28 PM" src="https://user-images.githubusercontent.com/26075187/63057435-35f4b400-beb8-11e9-8934-b47731fea43a.png">

**Comment by starpit** [comment]
thanks! i also notice that we have been conjoining the "REVISION" and "UPDATED" columns; even in the `helm list` output. will add this to the fix.

**Comment by showeimer** [comment]
@starpit I see a similar issue with App/Version/Namespace columns
