### ISSUE TITLE
Firefox- bashlike plugin error parsing as a table

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2358]
The behavior of bash-like seems to not be consistent with Chrome, here is an example of one problem that I see when using a cli that routes through bash-like and adopts the same visualizations as kubectl:

<img width="775" alt="Screen Shot 2019-08-15 at 9 51 09 AM" src="https://user-images.githubusercontent.com/26075187/63099091-579a7d80-bf42-11e9-973c-d4813e8acec0.png">

The cli being used returns raw text as the output with the errors above, in Chrome the output is formatted in the Carbon styling.

**Comment by starpit** [comment]
what command did you issue here? thanks!

**Comment by starpit** [comment]
we probably should remove, for now, the use of the (awesome) `flatMap`. i do see that firefox 62 clais support for `flatMap`. you must be using an older version of firefox?

and the latest (chrome-based) Edge also supports flatMap. i think the only gaps are older Firefox, and the pre-chrome Edge.

**Comment by showeimer** [comment]
@starpit 

Looks like I'm on the Firefox Extended Support Release channel, so that is only on 60.8.0.  I think I can be agnostic on this one.  There might be government customers that don't allow for regularly updating their work approved browsers on their office computers, that might also apply to Edge.

**Comment by starpit** [comment]
yes, i think this one is important. it should be a straightforward matter either to use a flatMap polyfill npm, or just to edit the 3 or so places that call flatMap by hand.

**Comment by showeimer** [comment]
@starpit in these cases where a JavaScript feature is not supported by a particular browser, I've fallen back on `lodash`.  I see that they have a `flatMap` function:  https://lodash.com/docs/4.17.15#flatMap
