### ISSUE TITLE
Webpack hang in Safari

### ISSUE THREAD

**Issue by hanqiuzh** [IBM/kui#2359]
**Describe the bug**
In Safari, webpack version will hang at the `Please wait while we connect to your cloud` step. Although if you check the development took, websocket is actually connected.

**Steps to reproduce the behavior**

1. Run KUI proxy `npx kui-run-proxy`
2. Run webpack `npm run watch:webpack`
3. open safari with url `http://localhost:9080`

**Expected behavior**
Should show `ready`

**Screenshots**
<img width="1315" alt="Screen Shot 2019-08-15 at 10 07 57 AM" src="https://user-images.githubusercontent.com/31426239/63102031-50766e00-bf48-11e9-9090-c3aa72613348.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version: latest
- Operating system: Mac OS

**Comment by showeimer** [comment]
Seems like this problem also happens on Microsoft Edge

**Comment by starpit** [comment]
```
TypeError: ws.on is not a function. (In 'ws.on('message', onMessage)', 'ws.on' is undefined)
```

**Comment by showeimer** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

Is it because the websocket constructor is not supported ?  ^^^ see the bottom table in link above

**Comment by starpit** [comment]
apparently safari (and edge, too?) do not allow subclassing the native WebSocket. the subclass overrides are silently ignored. firefox and chrome seem ok with this.
