### ISSUE TITLE
Microsoft Edge - tab styling has scrollbars

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2371]
<img width="295" alt="Screen Shot 2019-08-15 at 2 40 45 PM" src="https://user-images.githubusercontent.com/26075187/63117972-d7d4d900-bf6a-11e9-8ec9-7cf204adc8bc.png">

**Comment by starpit** [comment]
hmm, i don't see this on the open repo, at least on this mac build of Edge:
Version 78.0.244.0 (Official build) Dev (64-bit)

could it be a conflict in your client's CSS layer?
