### ISSUE TITLE
activation poll

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#2398]
A common set of commands when developing is:
1. `activation list`
2. click an activation (`activation get`)
3. do some out of band activation which causes new activations
4. go to 1

What if there was an `activation poll` instead (which the `wsk` cli offers) which continuously updates the `activation list` view with new activations, with support for specific action names to keep the focus on activations of interest.

It would avoid steps `1` and `4` above because a developer could iterate between do stuff and click new activation.

A possible nuance is the rate of the poll and ingesting too many activations at once... perhaps a slider or command line argument could control the rate.

**Comment by starpit** [comment]
the table view indeed now supports watching, so this should be possible

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/oui/issues/64
