### ISSUE TITLE
fixed prompt at top instead of bottom

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#2401]
Enhancements related to https://github.com/IBM/kui/issues/1364 lead to the ability to add a fixed prompt at the bottom of the console.

Is there a configuration to fix the prompt to the _top instead of the bottom_. I don't believe there is yet, and personally I find locating the input _and_ search bars at the top more convenient particularly for tutorials and demos.

**Comment by starpit** [comment]
if you provide a custom css with your client, you can inject this css rule:

```css
body.kui--bottom-input .kui--input-stripe {
order: -1;
}
```

though you would have to plan out how this interacts with your tab UI.
