### ISSUE TITLE
usability issues with bodyCss with kui--bottom-input?

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#2402]
**Describe the bug**
Enabled `kui--bottom-input`. 
- [x] Can enter commands by typing but cannot paste text into the input area once you start typing.
- [ ] Tab completion does not work.
- [ ] Some help does not properly scroll.
- [x] reverse-i-search

**Steps to reproduce the behavior**
For the past bug, add `kui--bottom-input` to `bodyCss`, start kui, start typing a command then try to paste some text into the input area to complete the command.

For the tab completion bug, start typing a known command and hit `tab` - the focus will cycle through windows.

For the scrolling bug, see gif.
![Aug-17-2019 00-37-17](https://user-images.githubusercontent.com/4959922/63206693-68a0d700-c087-11e9-89f4-6cb298d579da.gif)

**Expected behavior**
Expect paste and tab completion to work, and proper scrolling.

**Comment by starpit** [comment]
thanks. yes, the bottom input should be considered a demonstration prototype at this point.

**Comment by starpit** [comment]
adding reverse-i-search to the list

**Comment by starpit** [comment]
paste in #2493
reverse-i-search in #2495

**Comment by starpit** [comment]
tab completion seems ok to me?

**Comment by starpit** [comment]
should be all good now
