### ISSUE TITLE
switching openwhisk namespaces does not emit confirmation of switch

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#2406]
If you are working with multiple openwhisk namespaces, when you switch between them via `auth list` then select, there is confirmation emitted of the change.

I believe this used to emit something like "ok you're not using ...". I think a positive and explicit confirmation would be helpful. Note that when you swtich kui themes, say from light to dark, the visual confirmation is the theme change itself.

I think it's quite confusing to switch namespaces without telling the user it was actually successful.

**Comment by rabbah** [comment]
in fact the radio selection can be misleading:

1. add auth A
2. add auth B
3. auth list, and select B
3. revoke auth A
4. wait appropriate amount of time for A to be revoked in the backend (~5 minutes)
5. auth list and select A

the console will show that A is no longer valid, the namespace does not actually switch but the radio button is still on A.

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/oui/issues/65
