### ISSUE TITLE
Dark mode - delete resource modal text is unreadable

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2437]
Carbon Design:

<img width="552" alt="Screen Shot 2019-08-19 at 2 36 07 PM (1)" src="https://user-images.githubusercontent.com/26075187/63354852-2bf90800-c333-11e9-940e-8ad1e5704ed2.png">

Kui:

<img width="534" alt="Screen Shot 2019-08-20 at 10 11 54 AM" src="https://user-images.githubusercontent.com/26075187/63354787-184da180-c333-11e9-8e50-a8e858726ea4.png">

---

background is #3D3D3D

button is #6F6F6F

**Comment by starpit** [comment]
thanks for the bug report!
