### ISSUE TITLE
improve log presentation for kubernetes resources

### ISSUE THREAD

**Issue by starpit** [IBM/kui#2439]
1) there's a tree of resources; e.g. Deploy -> Pod -> Container -> logs; currenlty, navigation to leaf logs requires many clicks; plus kui sidecar back button only supports one hop of history

2) optimize for common case of singleton paths; e.g. one container in a pod

3) formatting issues; in this screenshot
a) kui didn't recognize the log format
b) wasted screen space

![image](https://user-images.githubusercontent.com/4741620/63355968-010fb380-c335-11e9-9571-ef93d1a6f3dd.png)

**Comment by hanqiuzh** [comment]
This enhancement will be great.

I also found that the logs in sidecar doesn't support ansi color. Left is using `kubectl logs -f`, Right is the log in sidecar. You can see some `[0m`, `[32m` are printed. 
<img width="1247" alt="Screen Shot 2019-10-22 at 3 44 03 PM" src="https://user-images.githubusercontent.com/31426239/67327208-9110db80-f4e5-11e9-8636-b85694e24d1c.png">

**Comment by starpit** [comment]
i think these have been addressed in the latest code base https://github.com/kui-shell/plugin-kubeui
