### ISSUE TITLE
tab switching is buggy

### ISSUE THREAD

**Issue by hanqiuzh** [IBM/kui#2458]
**Describe the bug**
In webpack/proxy mode, if user frequently open/close the tab, the page will crash.
It seems to be related to the `ready` message because desktop version doesn't have this problem.

**Steps to reproduce the behavior**

1. open a new tab
2. close the old tab
3. repeat 1 & 2 until fail

**Expected behavior**
Page should not crash

**Screenshots**
![kui-tab-bug](https://user-images.githubusercontent.com/31426239/63446186-bdd24500-c407-11e9-9129-1a64f822417f.gif)

Error messages:
<img width="755" alt="Screen Shot 2019-08-21 at 11 38 13 AM" src="https://user-images.githubusercontent.com/31426239/63446424-30dbbb80-c408-11e9-8079-648746caf3e7.png">

**System**

- Kui version: latest
- Operating system: mac os

**Comment by starpit** [comment]
thanks for finding this. there are actually a couple of related bugs in the way tab are indexed. these bugs affect electron apps, too.
