### ISSUE TITLE
Multi-table layout issues

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2483]
Examples of issues:

1.  The layout of the output is scattered and is not organized
2.  Because the tables are in a flow layout, the data in the tables is getting truncated making it very hard to read.
3.  The notes section is forced into the flow layout, so it collides with the resource tables.

<img width="857" alt="Screen Shot 2019-08-22 at 9 43 06 AM" src="https://user-images.githubusercontent.com/26075187/63540332-e7fc3380-c4e9-11e9-821b-6d10945f5b12.png">

---

Here are suggested changes to improve the layout:

Option 1:

<img width="699" alt="Screen Shot 2019-08-21 at 4 58 12 PM" src="https://user-images.githubusercontent.com/26075187/63540616-5f31c780-c4ea-11e9-9090-a36c083190d0.png">

Option 2:
<img width="384" alt="Screen Shot 2019-08-21 at 4 54 39 PM" src="https://user-images.githubusercontent.com/26075187/63540619-60fb8b00-c4ea-11e9-87e3-56d4ac07a36b.png">

**Comment by starpit** [comment]
re: the sections, i personally would be happier routing `helm status` to `helm get` which uses the sidecar to format the data.

re: the multi-table wrapping, i agree that we should for now render these vertically.
