### ISSUE TITLE
format error for openwhisk package listing 

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#2487]
**Describe the bug**
The action name blends right into the action's kind.

**Steps to reproduce the behavior**

1. package create p
2. let p/a = () => {msg: 3}
3. package get p

**Expected behavior**
A clear separation between action name and kind.

**Screenshots**
Uploading results from multiple builtin kui themes (randomly picked 3).
<img width="447" alt="Screen Shot 2019-08-22 at 5 46 39 PM" src="https://user-images.githubusercontent.com/4959922/63552188-06235d00-c505-11e9-9c12-6eae71b61c0d.png">
<img width="304" alt="Screen Shot 2019-08-22 at 5 49 11 PM" src="https://user-images.githubusercontent.com/4959922/63552251-2e12c080-c505-11e9-9c3d-1831e1ffaeeb.png">
<img width="425" alt="Screen Shot 2019-08-22 at 5 49 03 PM" src="https://user-images.githubusercontent.com/4959922/63552255-2f43ed80-c505-11e9-8c8a-b7f6b4c90ca0.png">

**Comment by starpit** [comment]
thanks for the bug report. @myan9 a table that wasn't ported to the new table model
