### ISSUE TITLE
activation list does not distinguish activations between packages 

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#2490]
these two activations of `a` are not the same - one is from a package `p` and another is not in a package... they can't be distinguished until you click on each one.

<img width="299" alt="Screen Shot 2019-08-22 at 6 34 11 PM" src="https://user-images.githubusercontent.com/4959922/63554476-8d73cf00-c50b-11e9-92b3-fe4f7239194c.png">

**Comment by starpit** [comment]
a design question. the original intent was to devote more space to the activation id and to the timing bars. package names can possibly be long. we could stack the package name and action name, but this results in a non-uniform look for not-packaged actions. not to mention that if there are a mix of default-package actions and packaged actions... what should we do?

**Comment by rabbah** [comment]
Thoughtful question. My initial take: activation ids are sufficiently unique that displaying 6-8 characters is enough (instead of 17). That creates more spaces for character names.

For non-packages actions, what if the string `default package` is displayed, in which case tacking the package name on top of the action might work out well in terms of uniformity?
