### ISSUE TITLE
open vs edit

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#2515]
`open x` opens the file `x` in read only mode whereas `edit x` makes the file editable... i think the file should always be editable when opened, or at least the `edit` option should be available on `open` in the menu bar.

**Comment by starpit** [comment]
i am in total agreement. we also still can't even open a new file for editing.

**Comment by joshuaauerbachwatson** [comment]
>  we also still can't even open a new file for editing.

We happen to have a fix for that.  It’s the PR I mentioned would be coming “real soon now.”  I’ll make a different issue to submit that (unless you can point me to an existing one) so it doesn’t get confused with the main point of this issue.   Might take a few more days to get to it.

**Comment by starpit** [comment]
wow, awesome, thanks for the help @joshuaauerbachwatson !

**Comment by starpit** [comment]
i think this is resolved now
