### ISSUE TITLE
Blocking invocation hangs forever when action times out (webpack)

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [IBM/kui#2552]
**Describe the bug**
This only appears to happen in a webpack build.  If an action is invoked with `wsk action invoke <name> -b`, and that action exceeds its time limit, the kui shell command never returns.

**Steps to reproduce the behavior**

1. Build the latest kui for webpack using the instructions in the repo.
2. Bring it up in the cloud and set host and auth appropriately for the experiment.
3. Create an action that is guaranteed to time out.  Example shown below.
4. Invoke that action with the `-b` flag from the kui shell.

**Expected behavior**
The action should eventually return with an activation record showing that it timed out.  This is what happens when you issue `wsk action invoke <name> -b` from an ordinary shell or using the electron version of kui.

**Code snippets**
An action (`timesout.js`) that will time out if given a short enough limit:
```
function main(args) {
    let name = args.name || 'stranger'
    let greeting = 'Hello ' + name + '!'
    console.log(greeting)
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            message = `hello, I'm back`
            console.log(message)
            resolve({
                message: message
            });
        }, 6000)
    })
}
```
Create with `wsk action create timesout timesout.js -t 4000`.   Verify using `wsk action get` that the time limit is short enough to cause the action to time out.

**Comment by starpit** [comment]
hmm, this works for me, with a webpack+proxy setup at least:

```
let long = () => new Promise(resolve => setTimeout(resolve, 6000)) -t 4000
wsk action update long -t 4000
wsk action invoke long -b
```

i'll try it without a proxy next

**Comment by joshuaauerbachwatson** [comment]
We don't use a proxy, so that would be the case we are experiencing.
