### ISSUE TITLE
kui is not supporting kubectl plugins (other than itself)

### ISSUE THREAD

**Issue by fredleger** [IBM/kui#2569]
using kui shell app i would expect that my usual plugins (most of them installed with krew) are working the same way than in my traditional shell. bit this is not the case :

![image](https://user-images.githubusercontent.com/2778741/63807642-6c9de600-c91e-11e9-9f34-3518461f26a9.png)

**Comment by starpit** [comment]
thanks for the bug report! we will look into this. i agree that this is an important use case.

**Comment by myan9** [comment]
Hi @fredleger , I just verified this bug no longer exist on my MacOS Kui. This should be fixed if you re-download the latest Kui. We definitely fixed a bug on this a while back, but please let us know if it continues to be a problem. Thanks!
