### ISSUE TITLE
theme table doesn't indicate the current theme

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2590]
The issue is only shown in `CLIENT=alternate`
![Screen Shot 2019-08-28 at 4 23 14 PM](https://user-images.githubusercontent.com/21212160/63890044-26916280-c9b0-11e9-880d-d0790f9f3f7f.png)

In normal Kui, the theme table has the indicator of the current theme
![image](https://user-images.githubusercontent.com/21212160/63890223-7c660a80-c9b0-11e9-9ea0-f460ebac5791.png)

**Comment by starpit** [comment]
this is a bug, for sure, but only comes when, as a kui developer, you switch from CLIENT=default to CLIENT=alternate
