### ISSUE TITLE
helm help --tls returns {} in webpack+proxy clients

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2610]
<img width="241" alt="Screen Shot 2019-08-30 at 11 54 14 AM" src="https://user-images.githubusercontent.com/26075187/64034624-08954080-cb1d-11e9-8b50-4c33437c0ef6.png">

**Comment by showeimer** [comment]
console error:
<img width="776" alt="Screen Shot 2019-08-30 at 11 59 07 AM" src="https://user-images.githubusercontent.com/26075187/64035008-b6085400-cb1d-11e9-9fa5-1a042d5e5ba8.png">

**Comment by starpit** [comment]
i don't see this. can you determine what the error is more precisely, e.g. by clicking on that `19715` link to see where in the source the error emanates for you?

**Comment by showeimer** [comment]
<img width="842" alt="Screen Shot 2019-08-30 at 12 26 05 PM" src="https://user-images.githubusercontent.com/26075187/64036556-70e62100-cb21-11e9-9881-b510ec2f175c.png">

**Comment by showeimer** [comment]
<img width="803" alt="Screen Shot 2019-08-30 at 12 27 02 PM" src="https://user-images.githubusercontent.com/26075187/64036599-970bc100-cb21-11e9-9418-01b71b991d32.png">

**Comment by starpit** [comment]
i still need more information. there had to have been a preceding error, because `helm` should not be emitting "random JSON" (as the comment in the code says)

**Comment by starpit** [comment]
`helm version` would also help.

**Comment by starpit** [comment]
fwiw, `helm help` works for me with both 2.10 and 2.14.3; i just tested a webpack+proxy build of master

**Comment by showeimer** [comment]
We are using helm 2.12.3.

Why does a helm version matter for a highlighting error?

<img width="735" alt="Screen Shot 2019-08-30 at 12 46 42 PM" src="https://user-images.githubusercontent.com/26075187/64037719-5792a400-cb24-11e9-897f-4fd7510a9b12.png">

^-- `{}` is being returned.  We have not modified k8s-plugin.

**Comment by starpit** [comment]
i don't think it matters, i'm just trying to eliminate the possibilities.

**Comment by starpit** [comment]
retitling this. this is an error handling bug. if the helm client script injects `--tls`, then `helm help` fails, but kui does not gracefully transmit that error to the user

**Comment by starpit** [comment]
it also only seems to affect webpack+proxy clients. electron shows the correct
> Error: unknown flag: --tls
