### ISSUE TITLE
tutorials command emits json

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#2618]
**Describe the bug**
Tutorials command emits `json`.

**Steps to reproduce the behavior**

1. type `tutorials`

**Expected behavior**
A list of tutorials or tutorial commands to try.

**Screenshots**
<img width="721" alt="Screen Shot 2019-08-30 at 9 57 30 PM" src="https://user-images.githubusercontent.com/4959922/64057902-56d42f00-cb71-11e9-9d1a-19ffa028e0ca.png">

**Comment by starpit** [comment]
thanks for the bug report! hmm, i don't see this with the latest master, in either webpack or electron clients?

**Comment by rabbah** [comment]
After updating to latest master 9b5ba11296df8a4fc86b8213ae58cb157339f67f, i get the expected output. Sorry I should have made sure I was up to date first.
