### ISSUE TITLE
xterm scrollbar makes the output of certain command invisible

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2638]
1. use any not-light theme (If you're in client alternate, you could also see the issue in light theme)
2. execute `while true; do echo hi; sleep 1; done`
3. should see a white background color of output, which makes the text of the output invisible

![ezgif com-video-to-gif-11](https://user-images.githubusercontent.com/21212160/64179821-c6784180-ce31-11e9-8246-084cbde565a2.gif)

**Comment by myan9** [comment]
After I tried `while true; do echo hi hi hi hi hi hi; sleep 1; done`, I realized that the white vertical bar is the xterm scrollbar (I guess? maybe it's something else from xterm, but it's not from Kui).

**Comment by starpit** [comment]
hmm, i don't see this. weird.

**Comment by starpit** [comment]
should be resolved by https://github.com/IBM/kui/pull/2668
