### ISSUE TITLE
Cannot show `oc help` content on Firefox/Safari (invalid regex)

### ISSUE THREAD

**Issue by hanqiuzh** [IBM/kui#2640]
**Describe the bug**
In browser mode with Firefox/Safari, content will be missing for many commands

**Steps to reproduce the behavior**

1. In Firefox/Safari, type `oc help`
2. See error

**Expected behavior**
Content should show.

**Screenshots**
Firefox (content is missing):
<img width="1296" alt="Screen Shot 2019-09-03 at 10 49 48 AM" src="https://user-images.githubusercontent.com/31426239/64184109-f840d680-ce38-11e9-9b63-3230bab0b101.png">

BTW, use Chrome:
<img width="923" alt="Screen Shot 2019-09-03 at 10 54 36 AM" src="https://user-images.githubusercontent.com/31426239/64184301-45bd4380-ce39-11e9-85cc-0cb429d6510b.png">

**Code snippets**
The console points me to this line of code:
https://github.com/IBM/kui/blob/master/packages/app/src/webapp/util/ascii-to-usage.ts#L142
```
commandPrefix: command.replace(new RegExp('(?<=\\s)--?\\w+'), ''),
```

Regex with lookbehind group seems not supported on Firefox and Safari?

<img width="278" alt="Screen Shot 2019-09-03 at 10 52 23 AM" src="https://user-images.githubusercontent.com/31426239/64184143-03940200-ce39-11e9-903f-a8b65749e688.png">

**System**

- Kui version: Latest
- Operating system: Mac OS

**Comment by showeimer** [comment]
In Safari, oc help does not format into nice kui help menu format.  Also, observe this behavior with istioctl in Safari.
