### ISSUE TITLE
Sidecar logging title does not always reflect current resource

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2646]
<img width="1595" alt="Screen Shot 2019-09-03 at 下午2 51 41" src="https://user-images.githubusercontent.com/26075187/64201512-e2dda380-ce5c-11e9-8be2-190934b60537.png">

**Comment by starpit** [comment]
thanks for reporting this. do you see any errors on the developer console?

**Comment by starpit** [comment]
nvm, trivial bug, fixing

**Comment by showeimer** [comment]
@starpit I started seeing the title missing while checking for you when I got home.

<img width="1251" alt="Screen Shot 2019-09-03 at 6 54 10 PM" src="https://user-images.githubusercontent.com/26075187/64213911-7c687d80-ce7c-11e9-974b-b1add4e3e14f.png">
