### ISSUE TITLE
we should remove Sidecar Status Tab for kubernetes resources

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2651]
This is the short-term fix for the related issues below:
https://github.com/IBM/kui/issues/2647
https://github.com/IBM/kui/issues/2365

**Comment by starpit** [comment]
it's not just a short-term fix, we should remove this tab, so that we can spend the screen real estate on more valuable tabs, such as Events

**Comment by starpit** [comment]
i.e. #2438
