### ISSUE TITLE
Back button on logs sidecar disappears after viewing second time from pod sidecar

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2659]
1.  Kubectl get pods
2.  Click a pod
3.  Containers tab
4.  Click a container, logs view gets presented
5.  Back button is available, click it
6.  Click the container again, logs view gets presented.
7.  Back button disappeared.

<img width="165" alt="Screen Shot 2019-09-05 at 3 27 47 PM" src="https://user-images.githubusercontent.com/26075187/64374414-d3439380-cff1-11e9-83ae-563ef96bf313.png">

**Comment by starpit** [comment]
excellent find, thanks
