### ISSUE TITLE
After clicking Previous Log Tab, back button disappears and Latest Log Tab locks up

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2662]
1. type `k get pods`
2. click a pod to open the sidecar
3. click `Containers` sidecar tab
4. click an image to open the log view
5. click `Previous` Sidecar Tab
6. Back button disappeared
7. Couldn't click the `Latest` Tab

Note: Step 7 only exists when clicking `Previous` Tab doesn't throw exception in the Repl, e.g. Error from server (BadRequest): previous terminated container in pod not found.

**Comment by showeimer** [comment]
Also see this problem.

**Comment by starpit** [comment]
this should be resolved with the latest treatment of logs in https://github.com/kui-shell/plugin-kubeui
