### ISSUE TITLE
reimplement `ls` using filesystem API

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2702]
A couple of benefits of implementing `ls` using filesystem API
1. we can have `ls` running on Windows (related issue: https://github.com/IBM/kui/issues/1304)
2. we can remove `shelljs` dependency and cleanup the code

**Comment by starpit** [comment]
we should also be able to avoid an `exec` call, which will both make `ls` in kui faster, and also avoid having to worry about enclosing that `exec` within any isolation policies (since, for both, the directory read will happen within the kui process)
