### ISSUE TITLE
doc/dev/sample-plugin and plugin.md are outdated

### ISSUE THREAD

**Issue by myan9** [IBM/kui#273]

**Comment by myan9** [comment]
@joshuaauerbachwatson Thanks for pointing this out!

**Comment by joshuaauerbachwatson** [comment]
Noticing that the PR is in a change-requested state.    I have meanwhile selectively copied stuff from the PR and can verify that it substantially unblocks my progress, so good news and thanks for that. 
 Hoping to see the actual merge soon.
