### ISSUE TITLE
External client electron build produces broken result

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [IBM/kui#2738]
**Describe the bug**
In an external, client using the latest `@dev` releases for builder, core, plugin-core-support, and plugin-openwhisk, the electron artifact produced behaves as in the screenshot below.

**Steps to reproduce the behavior**
1.  Unzip the supplied attachment (it is a minimal external client constructed as per kui instructions).  [testClient.zip](https://github.com/IBM/kui/files/3607261/testClient.zip)
2.  In the testClient directory
```
npm install
NO_INSTALLER=true npx kui-build-electron /tmp mac
open dist/electron/Kui-darwin-x64/Kui.app
```
3.  In the resulting open shell type `wsk`.

**Expected behavior**
The usage for `wsk` should display as in a monorepo build.

**Screenshots**
![Screen Shot 2019-09-12 at 4 11 35 PM](https://user-images.githubusercontent.com/19649275/64817526-149aec80-d578-11e9-8f18-c467f876bd26.png)

**Comment by starpit** [comment]
would you be able to try again? i think you caught a brief but bad window. i just tried this, with success:

```bash
npm init -y
npm install --save-dev @kui-shell/builder@dev
npm install --save @kui-shell/core@dev @kui-shell/plugin-k8s@dev @kui-shell/plugin-core-support@dev @kui-shell/plugin-editor@dev @kui-shell/plugin-bash-like@dev
npx kui-init
npx kui-build-electron
open dist/electron/Kui-darwin-x64/Kui.app/
```

**Comment by joshuaauerbachwatson** [comment]
I tried again and I agree that (1) your example works (2) the original example I submitted using the OW plugin also works, and (3) most importantly, the rebase is no longer failing with the problem either.   So, thanks for looking into it and I am back on the air.   Closing this now.

**Comment by joshuaauerbachwatson** [comment]
Unfortunately, in continuing to work on the rebase, I find this is only fixed for mac.
- When I build for Linux _on_ Linux, I continue to see the `Cannot find module 'yargs-parser'` error on many commands of the resulting executable.
- When I build for Linux on _mac_ (something I thought I was now going to be able to do), I do _not_ see the `yargs-parser` error and all non-pty commands work.   However, contrary to my expectations, the pty commands are still broken in the same way as before the rebase.

Reopening on a preliminary basis as a heads-up.   I will try the smaller examples on Linux and see if I can pin the problem down further.

**Comment by joshuaauerbachwatson** [comment]
I have not been able to make a smaller example that would be easy for you to reproduce.   But, the fact is, that we will have no way to build for Linux after the rebase so I'm leaving the rebase on indefinite hold.   I want to keep this issue open since it's still an issue for us.  I'm hoping for some advice on how to pin down the problem.

Specifically, is the symptom "Can't find module 'yargs-parser'" just as mysterious to you as it is to us or do you have a clue about what might be going on?

**Comment by starpit** [comment]
possibly this? https://github.com/IBM/kui/pull/2790

**Comment by joshuaauerbachwatson** [comment]
Plausibly.   Is that PR about to merge?   If so, I'll wait for it and then just advance the rebase and retry.    Thanks.   If the PR will be pending for a while, I may try patching it in this PM (will be out much of the morning).

**Comment by starpit** [comment]
merged

**Comment by joshuaauerbachwatson** [comment]
Yes, that seemed to fix the problem.   I now have a solid build for LInux (when built on Linux).   There is the separate question of whether the cross-platform building scenarios are really working but that was never part of this issue so closing again.
