### ISSUE TITLE
packaging script for webpack in a simple filesystem deployment

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [IBM/kui#274]
There is a script for deploying the webpack on s3.  It isn't blackbox to those working on clouds other than IBM's (that could be the subject of another issue but it's not the request here).   As a way of getting into the system with least pain, there should be a script that is more certain to work for everyone, deploying into a tarball or docker image that can just be unpacked or hosted in a VM and run with a typical web server.

**Comment by starpit** [comment]
i have made a Dockerfile for the webpack builds, coming in this PR: #280 

this PR also enriches the documentation
