### ISSUE TITLE
Helm release sidecar notes tab is unresponsive

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2787]
Seen in Chrome and Firefox:

1.  Helm list
2.  Click a release, sidecar opens
3.  Click `Notes` tab
4.  Sidecar view stays on whatever tab is open
5.  Check web socket and a request was sent to get the notes but a response is not sent back

I don't see any console errors.

<img width="1249" alt="Screen Shot 2019-09-16 at 3 33 43 PM" src="https://user-images.githubusercontent.com/26075187/64987633-97cd8280-d897-11e9-829e-d08c6b016f66.png">

**Comment by starpit** [comment]
thanks, what verison of helm are you using? helm notes is only supported after a certain version of helm.

**Comment by showeimer** [comment]
@starpit hi, I don't think helm cli version is the issue.  The request never receives a response, if the command does not exist in helm cli I would expect and error to get returned.  But, to answer your question I am using v2.12.3, it appears to support the notes feature:

<img width="1040" alt="Screen Shot 2019-09-17 at 9 30 59 AM" src="https://user-images.githubusercontent.com/26075187/65046263-458b7080-d92e-11e9-9813-b9514cce6776.png">

**Comment by starpit** [comment]
great, thanks for the info!
