### ISSUE TITLE
Maximize sidecar Issue

### ISSUE THREAD

**Issue by cwyckoff3** [IBM/kui#2788]
**Describe the bug**
Maximizing the sidecar will not populate the "Summary" Tab

**Steps to reproduce the behavior**

1. Kubectl get pods -n kube-system
2. select item in table
3. expand sidecar
4. exit sidecar
5. select item in table -> summary tab doesn't load

It seems like clicking on another tab(ex: Containers), and then back to summary will work. But not all the time

**Screenshots**
<img width="841" alt="Screen Shot 2019-09-16 at 4 41 48 PM" src="https://user-images.githubusercontent.com/9663734/64992687-6c03ca00-d8a2-11e9-8a83-89b31d974bb8.png">

Problem also causes this greybox to appear on Firefox:
<img width="841" alt="Screen Shot 2019-09-16 at 4 40 03 PM" src="https://user-images.githubusercontent.com/9663734/64992822-b2f1bf80-d8a2-11e9-993a-cb15fb6153be.png">

**Comment by starpit** [comment]
confirmed, thanks!!
