### ISSUE TITLE
improve events table in Sidecar

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2800]
1. The `Object` information in the `Sidecar Events` table is redundant and unnecessary, since user knows the pod name from e.g. sidecar header and drilldown purpose. 
2. The information shown in the `Sidecar Events` table should be closer to the events information in  `kubectl describe` output. For example,  `kubectl describe` shows events `Source` and `Count`, but these are not in the `Sidecar Events` table.

**Comment by starpit** [comment]
nice catch!
