### ISSUE TITLE
Sidecar behavior with cloudctl commands

### ISSUE THREAD

**Issue by cwyckoff3** [IBM/kui#2809]
**Describe the bug**
Input is being placed into the sidecar causing some unexpected layout errors.

**Steps to reproduce the behavior**

1. Kubectl or helm command that produces table output
2. select item in table
3. Certain cloudctl commands generate tables (ex: cloudctl metering)
4. Select an item
5. Hit the "previous page" button on sidecar
6. Hitting a table output in the sidecar makes all tabs unclickable 

**Screenshots**
<img width="1652" alt="Screen Shot 2019-09-18 at 4 02 01 PM" src="https://user-images.githubusercontent.com/9663734/65181780-d09f6000-da2d-11e9-9354-7ebb05f63319.png">
<img width="1652" alt="Screen Shot 2019-09-18 at 4 02 31 PM" src="https://user-images.githubusercontent.com/9663734/65181788-d7c66e00-da2d-11e9-8b68-8110478e2b2f.png">
<img width="1652" alt="Screen Shot 2019-09-18 at 4 02 49 PM" src="https://user-images.githubusercontent.com/9663734/65181795-db59f500-da2d-11e9-915e-4a2f75238f94.png">

Clicking on another tab and back generally shows the Summary correctly.
However, if a user clicks on something in the table in the sidecar, the sidecar becomes unresponsive.

**Comment by showeimer** [comment]
This issue is still seen in v6.0.12

@myan9 @starpit

**Comment by mark-nc** [comment]
i am unable to reproduce this in v8.10.x so it seems fixed at that level.

**Comment by starpit** [comment]
yes, we no longer auto-table raw pty output.
