### ISSUE TITLE
sidecar summary tab is confusing for 'k get pods -o json' 

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2815]
When I type `k get pods -o json` or `-o yaml`, I saw sidecar opened with the Summary Tab showing the summary for only 1 pod. This is confusing because I was expecting a list of pods.

**Comment by starpit** [comment]
nice catch. should we skip the summary tab for this corner case?

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/plugin-kubeui/issues/173
