### ISSUE TITLE
kubectl empty watch table updates the table content incorrectly

### ISSUE THREAD

**Issue by myan9** [IBM/kui#2824]
If a watch command initially issues an empty table, the updated table will have a reversed body and header

Steps to reproduce this issue:
1. Create a new namespace
2. Watch pods in the new namespace by: ```k get pods -n ns -w```
3. Create a pod in this namespace
4. See the table in Step 2 has reversed body and header

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/plugin-kubeui/issues/219
