### ISSUE TITLE
host behavior different between local and webpack/dockerized

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#284]
type `host` in the desktop shell and you get a helpful tip for commands available.
repeat the same in the dockerized webpacked version and you get an error:

<img width="424" alt="screen shot 2019-01-27 at 9 57 55 am" src="https://user-images.githubusercontent.com/4959922/51802640-13e85c80-221a-11e9-8c1f-b95fb9254124.png">

it looks to be systemic since all built-in commands report an XHR error.
also notice the help is rendered different than desktop - i can file separate issue for that.

**Comment by starpit** [comment]
should be resolved now
