### ISSUE TITLE
Webpack build broken (blank screen, hard error in console) for external client

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [IBM/kui#2849]
Note: since the original filing I have come up with a simplified way to reproduce the problem.

**Describe the bug**
We rely on an external client that includes the majority of `kui` plugins.

In attempting to rebase our `kui` fork to commit 72ad63a3d, we get a broken result (browser screen is blank).

Console: `Uncaught SyntaxError: Unexpected token .`
Associated Source: `main.02dd8eb1e816f9c8a7b4.bundle.js:408506`
```
module.exports = ./es6/crc17_ccitt;
```
Also nearby are:
```
module.exports = ./es6/crc17_kermit;
module.exports = ./es6/crc17_modbus;
module.exports = ./es6/crc17_xmodem;
module.exports = ./es6/crc9_1wire;
```
I don't know if those others would be about to fail also, but I suspect so.  I notice that these five exports are explicitly mentioned in `webpack.config.js` but I don't know the motivation or the connection to the bug.

**Steps to reproduce the behavior**

Unfortunately, these steps are laborious because we rely on `npm pack` of the `kui` repo components and I can't reproduce the problem using published `kui` components (if I substitute `@dev` components, the result works).   

Here is the `package.json` of a test that produces the problem (after building the client, including `npx kui-init`)
```
{
  "name": "test-client",
  "version": "0.0.1",
  "description": "Test External Client Support",
  "main": "node_modules/@kui-shell/core/main/main.js",
  "keywords": [],
  "author": "Joshua Auerbach",
  "license": "UNLICENSED",
  "devDependencies": {
    "@kui-shell/builder": "file:../kui-shell-builder-4.0.0.tgz",
    "@kui-shell/webpack": "file:../kui-shell-webpack-4.0.0.tgz",
    "mocha": "6.1.4",
    "@types/mocha": "5.2.7",
    "@types/node": "12.0.10",
    "electron": "5.0.6",
    "spectron": "7.0.0",
    "typescript": "3.5.2"
  },
  "dependencies": {
    "@kui-shell/core": "file:../kui-shell-core-4.0.0.tgz",
    "@kui-shell/plugin-core-support": "file:../kui-shell-plugin-core-support-4.0.0.tgz",
    "@kui-shell/plugin-openwhisk": "file:../kui-shell-plugin-openwhisk-4.0.0.tgz",
    "@kui-shell/plugin-apache-composer": "file:../kui-shell-plugin-apache-composer-4.0.0.tgz",
    "@kui-shell/plugin-bash-like": "file:../kui-shell-plugin-bash-like-4.0.0.tgz",
    "@kui-shell/plugin-editor": "file:../kui-shell-plugin-editor-4.0.0.tgz",
    "@kui-shell/plugin-grid": "file:../kui-shell-plugin-grid-4.0.0.tgz",
    "@kui-shell/plugin-k8s": "file:../kui-shell-plugin-k8s-4.0.0.tgz",
    "@kui-shell/plugin-manager": "file:../kui-shell-plugin-manager-4.0.0.tgz",
    "@kui-shell/plugin-openwhisk-editor-extensions": "file:../kui-shell-plugin-openwhisk-editor-extensions-4.0.0.tgz",
    "@kui-shell/plugin-tutorials": "file:../kui-shell-plugin-tutorials-4.0.0.tgz",
    "@kui-shell/plugin-wskflow": "file:../kui-shell-plugin-wskflow-4.0.0.tgz"
  }
}
```
Each of the referenced tarballs was produced from `kui` at the above commit via
```
npm pack $PACKAGES/app \
         $PACKAGES/kui-builder \
         $PACKAGES/webpack \
         $PLUGINS/plugin-apache-composer \
         $PLUGINS/plugin-core-support \
         $PLUGINS/plugin-grid \
         $PLUGINS/plugin-k8s \
         $PLUGINS/plugin-manager \
         $PLUGINS/plugin-openwhisk \
         $PLUGINS/plugin-wskflow \
         $PLUGINS/plugin-editor \
         $PLUGINS/plugin-openwhisk-editor-extensions \
         $PLUGINS/plugin-tutorials \
         $PLUGINS/plugin-bash-like \
```
where the symbols refer to the `packages` and `plugins` directories of a `kui` repo checked out at commit 72ad63a3d.

I am not necessarily expecting you to go through the full process of reproducing the error but if my exposition of the problem gives some clues to what might be wrong, I'm hoping for some help.

**Comment by joshuaauerbachwatson** [comment]
There is a simpler way to reproduce the problem now that we are attempting to use stable releases of kui instead building from the repo.   The following `package.json` is from a test external client built in (nearly) the standard way:
```
{
  "name": "test-client",
  "version": "0.1.19",
  "description": "Test Workbench Client",
  "main": "node_modules/@kui-shell/core/main/main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "Joshua Auerbach",
  "license": "UNLICENSED",
  "devDependencies": {
    "@kui-shell/builder": "4.5.0",
    "@kui-shell/webpack": "4.5.0",
    "mocha": "6.1.4",
    "@types/mocha": "5.2.7",
    "@types/node": "12.0.10",
    "electron": "5.0.6",
    "spectron": "7.0.0",
    "typescript": "3.5.2"
  },
  "dependencies": {
    "@kui-shell/core": "4.5.0",
    "@kui-shell/plugin-core-support": "4.5.0",
    "@kui-shell/plugin-editor": "4.5.0",
    "marked": "^0.7.0"
  }
}
```
Concerning the dependencies:
- the editor plugin is now required by the core
- the "marked" dependency is needed in this minimal config because it is dynamically imported by the core and webpack will barf on its absence.

Non-standard aspects:
- I started with the usual `kui-init` but found I had to delete the `test` directory in the sample plugin, otherwise I got an error when test support was not found in the core.

Symptom:
The same as reported originally.  It builds, but when uploaded and visited I get a blank screen with the console error as shown above.

**Comment by starpit** [comment]
re: the editor dependence for external clients. this should be fixed in the 5-series, which now offers a way for plugins to offer an editor API to the core.

**Comment by joshuaauerbachwatson** [comment]
> re: the editor dependence for external clients. this should be fixed in the 5-series, which now offers a way for plugins to offer an editor API to the core.

Good to know.   Any progress on the main problem?   We are blocked from upgrading our `kui` dependency because of it.

**Comment by starpit** [comment]
this should be resolved now
