### ISSUE TITLE
unexpected behavior using host command

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#285]
i expected `host <string>` where string other than `set/get/-h` to give me the help page but this is what i see on the desktop (built from https://github.com/IBM/kui/commit/cf85ba23f16cb4b764e74f15ddbb915de6bb7740).

<img width="685" alt="screen shot 2019-01-27 at 10 00 01 am" src="https://user-images.githubusercontent.com/4959922/51802713-a983ec00-221a-11e9-81b8-2c294cfb72bb.png">

i'd think these commands should be rejected... although it's nice to have shorthand `host xyz` for `host set xyz`, that's not the observed behavior though.

**Comment by starpit** [comment]
there is a deeper bug here, but: if the bash-like plugin has been loaded, then its catch-all resolver kicks in.

this results in execution of the platform `host` command, which yields the errors you see. i don't yet understand why sometimes it sends to the bash-like catch-all and sometimes it does not.

there are two deeper issues here

1) that the bash-like catch-all is not registered until the first use of some bash-like command
2) what is the desired behavior here? if there is a command subtree (`host/...` *is* a valid command subtree), then never dispatch to the catch-all handlers? probably?

**Comment by rabbah** [comment]
The description in the first comment is specific to the desktop kui. The screenshot below is from the webpackaged kui on commit 5a31f8d7c80bba559851764a622516f84a29dcc2

<img width="835" alt="screen shot 2019-01-28 at 8 58 56 am" src="https://user-images.githubusercontent.com/4959922/51840806-1363ca80-22db-11e9-8afc-fdb1c94a261f.png">

note that `host set localhost` lock up the ui and i have to ctrl+c break out of it.

**Comment by starpit** [comment]
with the upcoming PR, the bashlike plugin will always register its catchall, rather than after execution of the first bash-like command. this should resolve the issue, as it deals with the inconsistency problem.
