### ISSUE TITLE
How do I get off the homepage in electron and back to terminal?

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2881]
1.  Getting Started
2.  Click homepage button
3.  Home page opens
4.  I can't get back to my terminal

**Comment by starpit** [comment]
Usually, this is a symptom of code that uses `window.location=`. We should add a handler for the [`will-navigate` event](https://www.electronjs.org/docs/api/web-contents#event-will-navigate) in main/spawn-electron.ts
