### ISSUE TITLE
Hovering over sidecar expand button does not show tooltip message

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2883]
Screenshot, minimize, and close buttons in sidecar all display a tooltip message.  For some reason the expand button does not show a message, the design behavior is not consistent.

**Comment by starpit** [comment]
thanks for the bug report. the issue here is a conflict with the carbon-components css. we have the tooltip classes on an <a>, which carbon-components dresses up in a way that conflicts with the balloons.

c.f. https://github.com/IBM/kui/issues/1444
