### ISSUE TITLE
"helm get" always fails if helm service used requires `--tls` flag

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2884]
<img width="519" alt="Screen Shot 2019-09-30 at 10 48 09 AM" src="https://user-images.githubusercontent.com/26075187/65889842-ed159380-e36f-11e9-9271-86909fd9a078.png">
<img width="386" alt="Screen Shot 2019-09-30 at 10 48 02 AM" src="https://user-images.githubusercontent.com/26075187/65889843-edae2a00-e36f-11e9-8509-d8f5e82e7d73.png">

**Comment by starpit** [comment]
i suspect this might be resolved with the new repo. i'll close this here. let us know, in the new repo if the problem still exists. https://github.com/kui-shell/plugin-kubeui
