### ISSUE TITLE
bash-like - broken clickable resource names for clis that don't have a kui plugin

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2888]
1.  Run a command for a cli that doesn't have a kui plugin and returns a table output
2.  Bash-like is allowing the row names to be clickable and execute a new command
3.  The CLI doesn't support the command execution that KUI is assuming.
4.  Command fails and the UX is not good.

Example:

1. `foobar iam roles`
2.  Table is returned, click a resource name.
3.  KUI executes something like `foobar iam role-get Administrator`

KUI is dropping the plural resource type and and appending `-get` and the resource name.

**Comment by showeimer** [comment]
I think this will be higher priority because it will confuse users.

**Comment by starpit** [comment]
if we disable the onclick handlers, would this be a sufficient fix?

**Comment by showeimer** [comment]
@starpit yeah; and not make it appear clickable as well
