### ISSUE TITLE
What are KUI's contributing guidelines?

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2896]
KUI has a link on the main readme for this page under a `Contributing` section: https://github.com/IBM/kui/blob/master/docs/dev/README.md.

But that page just talks about how to develop with KUI.  Are there more formal instructions on how to contribute to this open source project similar to how IBM's Carbon has here:  https://github.com/carbon-design-system/carbon-components-react/blob/master/.github/CONTRIBUTING.md?

**Comment by starpit** [comment]
https://github.com/IBM/kui/blob/master/CONTRIBUTING.md ?

**Comment by showeimer** [comment]
@starpit can that link be added to the README.md under `Contributing`?   There is only a developer guide there.
