### ISSUE TITLE
introduce higher level view APIs, staring with: MultiModalResponse

### ISSUE THREAD

**Issue by starpit** [IBM/kui#2899]
the current kui view apis are fairly low level. let's introduce some new ones. this issue covers `MultiModalResponse` which lets plugins provide sidecar-oriented, multi-tab, views without having to worry about the more complex inner workings of kui.

**Comment by showeimer** [comment]
@starpit will these new APIs include documentation to inform users how to consume them?

**Comment by starpit** [comment]
absolutely. we are working on a sample that uses this, too.

**Comment by showeimer** [comment]
@starpit awesome!  I think that will start helping decrease the friction in writing custom plugins.

**Comment by starpit** [comment]
returning this UI.MultiModalResponse:

```json
{
    kind: 'kindpart',
    metadata: {
      name: 'this is the name part',
      namespace: 'this is the namespace part'
    },  
    modes: [
      { mode: 'html', label: 'HTML Text', content: htmlTextContent(), contentType: 'text/html' },
      { mode: 'dom', label: 'HTML DOM', content: domContent() },
      { mode: 'text', label: 'Plain Text', content: plainTextContent() },
      { mode: 'image', content: imageContent() },
      { mode: 'markdown', content: markdownTextContent(), contentType: 'text/markdown' },
      { mode: 'table', content: tableContent() }
    ]
  }
```

will produce this output:

![image (13)](https://user-images.githubusercontent.com/4741620/66072267-bfbd1700-e522-11e9-8ec6-edcb4ba77b16.png)
