### ISSUE TITLE
Webpack (KUI 4.5.0) build is broken when trying to compile node-pty in bash-like plugin

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2901]
When trying to build a custom client for the web, the build for KUI 4.5.0 breaks when compiling the bash-like plugin.  A failure to resolve the `node-pty` package error is presented, it appears that the bash-like 4.5.0 npm package does not include an update that is currently in the 4_5_x branch:  https://github.com/IBM/kui/blob/4_5_x/plugins/plugin-bash-like/src/pty/server.ts#L212.

#### Bash-like
<img width="1742" alt="Screen Shot 2019-10-02 at 10 04 34 AM" src="https://user-images.githubusercontent.com/26075187/66051117-62ae6a80-e4fc-11e9-91dc-438d0e7d5f4d.png">

#### Webpack
<img width="1700" alt="Screen Shot 2019-10-02 at 10 05 04 AM" src="https://user-images.githubusercontent.com/26075187/66051128-63df9780-e4fc-11e9-99a8-2e6ca7cb38f6.png">

---

@starpit @myan9

**Comment by showeimer** [comment]
low priority

**Comment by starpit** [comment]
i think we need to consider 4.5.0 as deprecated at this point.
