### ISSUE TITLE
feat: plugins should be able to declare that they want sidecar to occupy the full screen

### ISSUE THREAD

**Issue by starpit** [IBM/kui#294]
right now, a plugin can return an entity which will be rendered in the sidecar. but there is no way for it to specify that the sidecar should open full screen.

**Comment by 0ZT** [comment]
I am against financial debt without income checking account only op. but near future give back my confidence and my future 25.5 (:

**Comment by starpit** [comment]
coming soon [Presentation](packages/app/src/webapp/views/presentation.ts)
