### ISSUE TITLE
Hybrid raw text/UI visualization is occasionally possible

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#2951]
Not easy to reproduce but sometimes, we get raw text, a full table, or this:

<img width="839" alt="Screen Shot 2019-10-08 at 11 43 30 AM" src="https://user-images.githubusercontent.com/26075187/66497619-c13e9000-ea8a-11e9-8033-17425a1645f2.png">

**Comment by hanqiuzh** [comment]
also seeing this happened at 6.0.20, when get logs, the first line like a table...
<img width="617" alt="Screen Shot 2020-04-02 at 5 28 53 PM" src="https://user-images.githubusercontent.com/31426239/78302119-32c23d00-7508-11ea-859e-f470da80b08f.png">

**Comment by mark-nc** [comment]
Logs are now displayed in the sidecar in v8.10.x so this may no longer be an issue.

**Comment by starpit** [comment]
thanks for poking on this. i concur, and for even more reasons: the PTY now is "dumber" in that it does not attempt to cleverly auto-parse raw PTY output into tables without careful assent of the originating command.
