### ISSUE TITLE
KUI webpack UI fails to display on Microsoft Edge browser with v5.1.7

### ISSUE THREAD

**Issue by mark-nc** [IBM/kui#3014]
**Describe the bug**
When displaying our webpack version of KUI served up from a proxy running in a Kubernetes pod container on a Microsoft Edge browser, the UI fails to display due to an error.

`SCRIPT1028: SCRIPT1028: Expected identifier, string or number      main.f5ff389ec0d128f0e162.bundle.js (216282,3)`

**Expected behavior**
The UI should display on the Edge browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/51764173/66931876-c3fa3180-f004-11e9-9270-dceb2fc041a0.png)

**System**

- Kui version: 5.1.7
- Operating system:  Windows 10 Professional

**Comment by starpit** [comment]
thanks for the bug report. this seems to come about due to an upgrade of a dependence (electron-context-menu) that itself upgrade one of its dependences; that transitive dependence (cli-truncate v2.0.0) included a change that is incompatible with edge. this dependence isn't needed for webpack builds, so we will find a way to remove it. if not, we can always downgrade the version of that dependence.

**Comment by showeimer** [comment]
Problem still persists on v5.1.9

<img width="551" alt="Screen Shot 2019-10-21 at 11 47 58 AM" src="https://user-images.githubusercontent.com/26075187/67220947-ad831a00-f3f8-11e9-8bad-12eec3a10130.png">
<img width="918" alt="Screen Shot 2019-10-21 at 11 48 05 AM" src="https://user-images.githubusercontent.com/26075187/67220948-ae1bb080-f3f8-11e9-8fa7-9bfe5fefc147.png">

**Comment by starpit** [comment]
thanks! can you try to figure out the call stack that leads to this error?

**Comment by mark-nc** [comment]
Can you point a browser against your webpack sample?  That might make it easier to find in your own test environment?

**Comment by starpit** [comment]
i'm still trying to figure out how to get a windows vm to talk to a web server running on the enclosing host.

i did experiment with a webpack build to see if the offending code would ever load. on firefox, i have yet to see this happen.

**Comment by showeimer** [comment]
KUI 5.1.11 still broken with same syntax issue somewhere else; I think KUI will need to modify the compiler to support these more modern JS features.

<img width="550" alt="Screen Shot 2019-10-22 at 9 59 26 AM" src="https://user-images.githubusercontent.com/26075187/67294258-97865f80-f4b3-11e9-8019-9dcca08c9ca0.png">
<img width="1109" alt="Screen Shot 2019-10-22 at 9 59 37 AM" src="https://user-images.githubusercontent.com/26075187/67294262-97865f80-f4b3-11e9-845f-36e4d086a387.png">

**Comment by mark-nc** [comment]
This might be helpful to find these issues during dev/test time.
https://github.com/Microsoft/TypeScript/issues/19183#issuecomment-450440200

**Comment by starpit** [comment]
seems good now. we should figure out how to lock this down.
