### ISSUE TITLE
Tab completion should handle left/right arrow keys

### ISSUE THREAD

**Issue by hanqiuzh** [IBM/kui#3087]
**Describe the bug**
Press left/right arrow keys in tab completion will insert completion to a wrong place.

**Steps to reproduce the behavior**

1. Type in `kubectl get po` 
2. Press Tab
3. When tab-completion selection table shows, press left/right arrow key to move the cursor
4. Select one item; completion text will be insert into the cursor's place

**Expected behavior**
left/right arrow should not affect the insert place. 

**Screenshots**
![Oct-23-2019 13-57-27](https://user-images.githubusercontent.com/31426239/67421138-e0b2de00-f59d-11e9-92ee-6544d71167cf.gif)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version: Latest
- Operating system: Mac OS

**Comment by starpit** [comment]
agreed! thanks for reporting this issue
