### ISSUE TITLE
Microsoft Edge - double empty input generated after each command input

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#3097]
KUI v5.1.12 on Microsoft Edge:

1.  Use Edge
2. Enter any command; even clear works
3.  Two empty input bars get displayed

<img width="454" alt="Screen Shot 2019-10-24 at 12 15 11 PM" src="https://user-images.githubusercontent.com/26075187/67509383-dad20100-f660-11e9-9b59-c74affbdf54f.png">

I do not see any associated console errors when this happens.  I do not see this issue on Chrome, Firefox, or Safari.

**Comment by mark-nc** [comment]
Note, this is without any plugins that extend, modify or override the command input area.  Seems likely it could be different event processing of a user `Enter` on Edge.

**Comment by showeimer** [comment]
Closing this because this is not an issue in the newer Chromium-based Edge.
