### ISSUE TITLE
new session message and inputbar block bypassed when new tab is clicked.

### ISSUE THREAD

**Issue by RobDolares** [IBM/kui#3173]
### Issue
REPL input message `'Please wait while we connect to your cloud'` message as well as REPL block can be clicked through when a new session tab is opened.

### Expectation
similar behavior to when initial kui page is rendered - blocked input until cloud connection resolves.

### Example:
Search commands are being completed and executed in below GIF.  Nothing is returned until the successful connection to cloud.  Commands entered before cloud connection are not stacking or placed in queue, so no issue there.
<kbd>![Nov-08-2019 15-16-39.gif](https://zenhub.ibm.com/images/5cab661bbf359f5e5bef04c6/896aad94-cffa-413f-9763-0855f4497e0a)</kbd>

**Comment by hanqiuzh** [comment]
I also found another similar issue that if you run `vi a.txt` in one tab, the other tabs will be locked

**Comment by starpit** [comment]
interesting. i thought we made the bottom input readonly until the session was established? i'll look into that to see.

**Comment by starpit** [comment]
unless you can confirm that the bottom input is made not-read-only but your own scss?

**Comment by RobDolares** [comment]
Revisiting original issue with latest core and no longer able to replicate, though I can replicate issue @hanqiuzh references.
