### ISSUE TITLE
installing Kui by `npm install` fails with node v12

### ISSUE THREAD

**Issue by myan9** [IBM/kui#3187]
> There seems to be a rather blatant bug in the npm included with node 12.12 and 12.13. a dependence is explicitly stated (the openwhisk npm is mentioned explicitly in plugins/plugin-openwhisk/package.json, but this dependence is not resolved by npm install; this results in the error that you quoted above.
> 
> using npm ci forces npm to use the "bottled up" dependences from package-lock.json.
> 
> we will update the docs to suggest npm ci, and warn about node 12 until we can figure out how to work around the node 12 issue. thanks again for the bug report

Covered https://github.com/IBM/kui/issues/3177#issuecomment-552460322

**Comment by starpit** [comment]
we've pulled plugin-openwhisk to https://github.com/kui-shell/oui
