### ISSUE TITLE
Kui says command not in path that really seems to be in my path

### ISSUE THREAD

**Issue by Bachmann1234** [IBM/kui#3262]
**Describe the bug**
When I try to run a basic command `kubectl get pods` for example I get the following error

`Unable to connect to the server: getting credentials: exec: exec: "aws-iam-authenticator": executable file not found in $PATH`

However, the command sure seems to be in my path

**Please let me know if there is more info that can help.**

**Steps to reproduce the behavior**

I worry this is very environment specific...
Open kui
run `kubectl get pods`

**Expected behavior**
I would expand the command to execute properly

**Screenshots**
![Screen Shot 2019-11-20 at 11 22 17 AM](https://user-images.githubusercontent.com/1521093/69256794-04ab1480-0b88-11ea-8b11-e50f6102b36d.png)

**Code snippets**
Here is a text version of the above screenshot

```
❯
kubectl get pods
9:53:55 AM
Unable to connect to the server: getting credentials: exec: exec: "aws-iam-authenticator": executable file not found in $PATH
~
❯
aws-iam-authenticator
9:54:05 AM
A tool to authenticate to Kubernetes using AWS IAM credentials
Usage:
  aws-iam-authenticator [command]
Available Commands:
  help        Help about any command
  init        Pre-generate certificate, private key, and kubeconfig files for the server.
  server      Run a webhook validation server suitable that validates tokens using AWS IAM
  token       Authenticate using AWS IAM and get token for Kubernetes
  verify      Verify a token for debugging purpose
  version     Version will output the current build information
Flags:
  -i, --cluster-id ID       Specify the cluster ID, a unique-per-cluster identifier for your aws-iam-authenticator installation.
  -c, --config filename     Load configuration from filename
  -h, --help                help for aws-iam-authenticator
  -l, --log-format string   Specify log format to use when logging to stderr [text or json] (default "text")
Use "aws-iam-authenticator [command] --help" for more information about a command.
```

**System**

- Kui version: 

Component | Version
```
-- | --
Kui | 5.1.0-dev.5173.20191030201257
electron | 6.0.12
chrome | 76.0.3809.146
node | 12.4.0
v8 | 7.6.303.31-electron.0
```

- Operating system:
OSX 10.15.1 (19B88)

**Comment by myan9** [comment]
@Bachmann1234 Thanks for the bug report!
Could your provide the following information to help us solve the issue?

1. The error `Unable to connect to the server: ...` is issued from `kubectl` ,so could you check if `kubectl get pods` work in your terminal?
2. Your Kui version is not the latest one.  Did you try the latest Kui? 
2. How did you launch Kui? Did you double-click the app icon or launch it from terminal?

**Comment by Bachmann1234** [comment]
yep, kubectl works fine from iterm2 (My typical setup is ZSH, I dont know if thats relevant)

Typically launched via quicklook. I think its the same as launching the app. Just to check I tried that and I had the same effect.

I tried launching from a terminal and that works!

**Comment by Bachmann1234** [comment]
My guess is kui is using osx's gui "path" which I dont think I have set on this machine. I think I can set that with `launchctl setenv PATH $PATH` but im not 100% confident I wanna mess with that toooo much. 

But I think I can work around for now. Not sure if there is something to do in the app itself or not

**Comment by myan9** [comment]
Hi @Bachmann1234 , where is your `kubectl` located? If it's a common place, we can add it to the dock-launched PATH heuristic.

**Comment by Bachmann1234** [comment]
So kubectl is in a common place `/usr/local/bin/kubectl` 

But I think the problem is that we use `aws-iam-authenticator` to auth. That is not in a common place. But after our back and forth here I just tried adding a symlink to throw it in `/usr/local/bin` and now its all good!

Thank you for your help on this!
