### ISSUE TITLE
shift-home

### ISSUE THREAD

**Issue by carljmosca** [IBM/kui#3267]
Is it the intent that shift-home should move the cursor to the start of the line on MacOS?  This behavior seems to be gone from zsh as opposed to bash so perhaps it's no longer expected.

Wondering if there's some key definition I have missed.

**Comment by myan9** [comment]
@carljmosca Thanks for the feedback! We could add the support for this.

**Comment by starpit** [comment]
Also, Kui always interprets Home and End to be history navigation. This is consistent with macOS Terminal, but not with Linux or Windows, or these keys navigate the command line.
