### ISSUE TITLE
Using Kui as a kubectl plugin does not work on macOS X 

### ISSUE THREAD

**Issue by dove-young** [IBM/kui#3298]
**Describe the bug**

```
kubectl kui get po --ui
Error: unknown command "kui" for "kubectl"

Did you mean this?
	run

Run 'kubectl --help' for usage.
```

**Steps to reproduce the behavior**

1. Download `Kui.dmg`
2. Install
3. Click Kui from launchpad
4. type `kubectl kui po --ui` at terminal window
5. see error

Similar steps 

1. Download `Kui-darwin-x64.tar.bz2`
2. Unpack
3. Click Kui.app
4. type `kubectl kui po --ui` at terminal window
5. see error

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version:
- Operating system:

**Comment by starpit** [comment]
hi @dove-young 

indeed. this repo is not set up for use as a kubectl plugin. we will remove the script from this repo. please refer to this repo, which is the home of the kubectl-focused kui efforts: https://github.com/kui-shell/plugin-kubeui (this repo being the home of the kui-core framework).

we hope to use the plugin-kubeui repo as the basis for a krew plugin in the near future.

**Comment by starpit** [comment]
this should be resolved now. we have integrated kubernetes functionality into this repo, updated the top-level README to describe usage as a kubectl plugin, and also updated the way we package this plugin functionality into the pre-built images of Kui.
