### ISSUE TITLE
Clear, History and About Menu

### ISSUE THREAD

**Issue by razilevin** [IBM/kui#3374]
Commands like "clear" and "history -c" fail with the following stacktrace

Cannot find module '@kui-shell/plugin-core-support/dist/plugin.js'
Require stack:
- /Applications/Kui.app/Contents/Resources/app.asar/node_modules/@kui-shell/core/plugins/resolver.js
- /Applications/Kui.app/Contents/Resources/app.asar/node_modules/@kui-shell/core/plugins/plugins.js
- /Applications/Kui.app/Contents/Resources/app.asar/node_modules/@kui-shell/core/webapp/bootstrap/boot.js
- /Applications/Kui.app/Contents/Resources/app.asar/node_modules/@kui-shell/build/index.html

**Comment by starpit** [comment]
hello, and thanks for the bug report. well, that is embarrassing. the prior builds were buggy. i believe that the latest should fix this. much obliged for letting us know.
