### ISSUE TITLE
Very slow download

### ISSUE THREAD

**Issue by strowk** [IBM/kui#3434]
**Describe the bug**
I'm trying to download "prebuilt release" from https://win32-zip.kui-shell.org/ (link is given in readme https://github.com/IBM/kui ), Chrome estimates download as an hour, after some time download fails with network error. 

**Steps to reproduce the behavior**

1. Go to https://github.com/IBM/kui
2. Click `Kui-Win32-x64.zip`
3. Wait for download to finish

**Expected behavior**
Download should be finished in 5 minutes, 

actual: download hangs for some time and eventually fails

**Screenshots**
![image](https://user-images.githubusercontent.com/25692644/71674066-9e1a3880-2d7a-11ea-9ab9-0651604b0c68.png)
![image](https://user-images.githubusercontent.com/25692644/71674114-b722e980-2d7a-11ea-9c98-bbf3a941857f.png)

**System**

- Kui version: not applicable
- Operating system: Windows 10

**Comment by starpit** [comment]
thanks for the bug report! we will run some experiments to see if we can verify. if you don't mind sharing, what geo are you in? thanks!

**Comment by strowk** [comment]
Location is Munich. Though today it has downloaded fine.. I guess it was some kind of temporary network problem in aws.
