### ISSUE TITLE
strip-ansi utility has outdated code

### ISSUE THREAD

**Issue by myan9** [IBM/kui#3438]

**Comment by starpit** [comment]
details?

**Comment by myan9** [comment]
ansi-regex has new support 
https://github.com/chalk/ansi-regex/blob/2b56fb0c7a07108e5b54241e8faec160d393aedb/index.js#L3-L10

**Comment by starpit** [comment]
i was wondering if we had a concrete example that this fixes?

**Comment by myan9** [comment]
yes, my zsh will only work with the latest ansi-regex pattern. Otherwise, I will get the following characters unstripped when using the stripAnsi utility: ```"\u001b]7;file://mengtinmcomsMBP.home/Users/mengting.yan1ibm.com/Workspace/kui3/plugin-kubeui\u0007"```

**Comment by myan9** [comment]
> i was wondering if we had a concrete example that this fixes?

yes, my zsh will only work with the latest ansi-regex pattern. Otherwise, I will get the following characters unstripped when using the stripAnsi utility: "\u001b]7;file://mengtinmcomsMBP.home/Users/mengting.yan1ibm.com/Workspace/kui3/plugin-kubeui\u0007"

**Comment by starpit** [comment]
great, thanks!
