### ISSUE TITLE
Provide OpenShift compatibility to kui

### ISSUE THREAD

**Issue by honghuac** [IBM/kui#3441]
`oc` utility (the OpenShift command line utility) is a popular tool, for OpenShift users.

Provide compatibility in kui for OpenShift command line utility.

**Comment by starpit** [comment]
great idea. we will cover these in two issues:

- cover the "basic stuff", i.e. those `oc` commands that delegate to kubectl: https://github.com/kui-shell/plugin-kubeui/issues/199
- investigate how we can provide enhanced support for the openshift operations https://github.com/kui-shell/plugin-kubeui/issues/200

any ideas on the second? we will get the first done in short order, but will need some insight from the community on how the openshift-oriented commands could benefit from graphical enhancement!

close this one in favor of those two referenced issues
