### ISSUE TITLE
Transition to sourcing Carbon css from carbon-components npm package

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#3526]
Currently KUI is periodically manually copying over css styling from the Carbon CDN.  We can transition to installing `carbon-components` as a npm dependency and automate sourcing any css styling from there.

**Comment by starpit** [comment]
nice idea. kui actually currently has copy of carbon-components.min.css directly in the repo: https://github.com/IBM/kui/blob/master/packages/core/web/css/carbon-components.min.css

we could probably change this to using the npm source.
