### ISSUE TITLE
Error: unknown command "kui" for "kubectl"

### ISSUE THREAD

**Issue by bitsofinfo** [IBM/kui#3530]
I am on OS-X:

```
kubectl kui get pods
```

```
Error: unknown command "kui" for "kubectl"
```

**Comment by setevoy2** [comment]
The same here.
Are there any missing commands in the [Doc](https://github.com/IBM/kui/blob/master/docs/installation.md) for Kui installation and launch?

After downloading `Kui-linux-x64` and running the `Kui` executable - I'm trying to execute any of these:

![Screenshot_20200213_113723](https://user-images.githubusercontent.com/7965314/74421149-3bc25680-4e55-11ea-8093-a016c8f7e616.png)

**Comment by myan9** [comment]
@bitsofinfo  @setevoy2  You can just type `kubectl get pods` in Kui, just like how you usually perform cli execution in a plain terminal.

**Comment by bitsofinfo** [comment]
no kidding @myan9 , but your doc right on the main readme says this is possible, hence the ticket.... it clearly doesn't work

![image](https://user-images.githubusercontent.com/1743646/74545675-85b74500-4f06-11ea-8fea-06c1d5ef7951.png)

**Comment by setevoy2** [comment]
+1 to the previous comment, @myan9 
I ran the Kui mainly because of the `--ui` option to have a GUI window as on the screenshot above.

**Comment by bitsofinfo** [comment]
exactly

**Comment by starpit** [comment]
Thanks very much for the feedback. I will triage this either today or tomorrow!

**Comment by starpit** [comment]
i think we have this one covered now. the updated top-level README.md and the updated handling of kui as a kubectl plugin should cover this.
