### ISSUE TITLE
Context bar has strange flickering behavior

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#3537]
Seems to toggle on only while a command execution is in progress; after the command is complete the bar disappears.

![context-flicker](https://user-images.githubusercontent.com/26075187/73078820-039ca900-3e91-11ea-93c1-068e64f66751.gif)

Not sure if this is related:

<img width="424" alt="Screen Shot 2020-01-24 at 10 06 34 AM" src="https://user-images.githubusercontent.com/26075187/73078964-54140680-3e91-11ea-87b3-77caf4975c33.png">

**Comment by starpit** [comment]
i think we're good here, with https://github.com/kui-shell/plugin-kubeui/pull/289 and the associated core fixes
