### ISSUE TITLE
Hide context icons until requests are complete

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#3538]
<img width="482" alt="Screen Shot 2020-01-24 at 10 08 34 AM" src="https://user-images.githubusercontent.com/26075187/73079192-ca186d80-3e91-11ea-839c-e24f22b9ed9d.png">

^--- The two little icons with no text look strange while the connection is pending.

**Comment by starpit** [comment]
agreed

**Comment by starpit** [comment]
not quite!

**Comment by starpit** [comment]
associated fix: https://github.com/kui-shell/plugin-kubeui/pull/289
