### ISSUE TITLE
Command strings in REPL are truncated but element is also scrollable

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#3539]
<img width="1133" alt="Screen Shot 2020-01-24 at 10 15 12 AM" src="https://user-images.githubusercontent.com/26075187/73079649-97bb4000-3e92-11ea-9782-2dfa15770319.png">

^--- Can scroll horizontally but the text is already truncated with ellipsis

**Comment by starpit** [comment]
i have noticed this too. so weird.

**Comment by starpit** [comment]
i think removing the text-overflow:ellipsis in ui.css line 413 will fix this
