### ISSUE TITLE
KUI will send 3 /exec requests at start up which results in 3 websocket/user sessions

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#3543]
<img width="765" alt="Screen Shot 2020-01-24 at 1 35 36 PM" src="https://user-images.githubusercontent.com/26075187/73095130-ed521580-3eaf-11ea-8026-319244b989e5.png">
<img width="1062" alt="Screen Shot 2020-01-24 at 1 36 23 PM" src="https://user-images.githubusercontent.com/26075187/73095131-ed521580-3eaf-11ea-8878-0564607c8de3.png">
<img width="391" alt="Screen Shot 2020-01-24 at 1 42 22 PM" src="https://user-images.githubusercontent.com/26075187/73094871-7a489f00-3eaf-11ea-9ac3-f0a745d4291d.png">

Guessing that this is occurring due to context menu changes where the websocket connection is not complete so http requests are getting sent to `/exec`.  KUI should wait until the connection is established before sending these commands.

**Comment by starpit** [comment]
thanks, good catch!

**Comment by starpit** [comment]
there is a chance that this was fixed by https://github.com/IBM/kui/pull/3555. i'll keep this open until we can verify.

**Comment by starpit** [comment]
associated fix: associated fix: https://github.com/kui-shell/plugin-kubeui/pull/289
