### ISSUE TITLE
Strange transition from getting started sidecar to resource sidecar

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#3589]
1.  Open getting started
2.  Keep getting started sidecar open, run a command that will trigger the resource sidecar (`kubectl get pod __`)
3.  Observe getting started tabs flicker to the coming resource sidecar tabbing, then the whole sidecar changes.

![sidecar-transition](https://user-images.githubusercontent.com/26075187/73553360-d06d9300-4417-11ea-88c5-15916b4d1482.gif)

**Comment by starpit** [comment]
we update the bottom stripe, then fetch the content for the first tab, then update the Prese
ntation (e.g. from Slim to Normal). since the middle one is asynchronous, this introduces a
glitchy UI effect

**Comment by starpit** [comment]
regression: if mode list has no explicit defaultMode, incorrect view may be rendered.

core bug: premature return prior to sort
