### ISSUE TITLE
k8s crd sidecar launches to a non-existent and unnecessary tab view

### ISSUE THREAD

**Issue by showeimer** [IBM/kui#3592]
#### 3.  First view is some data with `NAME` and `CREATED AT`, with two tabs available in sidecar

<img width="701" alt="Screen Shot 2020-01-31 at 11 09 25 AM" src="https://user-images.githubusercontent.com/26075187/73554758-54287f00-441a-11ea-83ac-4358c91bc483.png">

#### 4.  Conditions tab:

<img width="477" alt="Screen Shot 2020-01-31 at 11 09 31 AM" src="https://user-images.githubusercontent.com/26075187/73554759-54287f00-441a-11ea-840a-609dfdb2e899.png">

#### 5.  YAML tab:

<img width="505" alt="Screen Shot 2020-01-31 at 11 09 38 AM" src="https://user-images.githubusercontent.com/26075187/73554760-54287f00-441a-11ea-9383-b5a98d14588a.png">

**Comment by starpit** [comment]
this is a bug in the kubeui plugin. some modes are too liberal with their filter, thus applying to crds when they shouldn't. probably an easy fix, but in that repo

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/plugin-kubeui/issues/318
