### ISSUE TITLE
Tab Completion has some bugs and usability issues

### ISSUE THREAD

**Issue by hanqiuzh** [IBM/kui#3605]
Tested on latest electron build on Desktop. Found the following issues:
1. Tab completion can only append to the end even if cursor is in middle of the input field
2. Tab completion works weird with `.` or number:
      - `.` will show at end of file name, and first char will be removed (e.g. `.git`-> `it.`). Also, weird for string start with number (e.g. `1.txt` -> `txt.1`
3. File-system completion is too aggressive. Shows folder contents for any commands (kubectl get ...)
4. Performance is slow: KUI's node-modules has 900+ folders, which freezes the window when I try to do tab completion. (I guess it's busy in generating all 900 divs) (Maybe can truncate the results to make it faster? as it's not easy for user to select from that number of items )
 

Screen shots:
1. cannot append to cursor
![Feb-03-2020 16-49-48](https://user-images.githubusercontent.com/31426239/73694017-4175aa80-46a5-11ea-891d-339ba5e0ec67.gif)

2. weird behavior on strings start with `.` or number:
<img width="1282" alt="Screen Shot 2020-02-03 at 3 19 44 PM" src="https://user-images.githubusercontent.com/31426239/73692502-6f0d2480-46a2-11ea-8248-422fd2d3158e.png">

<img width="600" alt="Screen Shot 2020-02-03 at 4 55 14 PM" src="https://user-images.githubusercontent.com/31426239/73694451-0b84f600-46a6-11ea-931e-1982f995fc06.png">

3. fs completion on `kubectl get`
<img width="1261" alt="Screen Shot 2020-02-03 at 3 25 00 PM" src="https://user-images.githubusercontent.com/31426239/73692562-8ea44d00-46a2-11ea-9e41-73bbdbda920d.png">

4. freeze when a lot of results returns:

![Feb-03-2020 16-48-27](https://user-images.githubusercontent.com/31426239/73693899-0a9f9480-46a5-11ea-8c7e-087cd73f565b.gif)

**Comment by starpit** [comment]
thanks! on it.

**Comment by starpit** [comment]
interesting, i think the period is coming from the html input element. are you on macOS? if so, i have yet to find a way to disable this on the HTML side.

**Comment by hanqiuzh** [comment]
Yes. I'm using MacOS, and this happens on both web version (Chrome) and electron version.

**Comment by starpit** [comment]
thanks. i see it, too. everything i've ready says this is coming from macos. we are disabling all of the "auto" stuff i know of (autocomplete, spellcheck, etc.). i don't see an option for disabling this on a given element. the only thing i've seen, so far, requires os-wide disabling of this feature.

**Comment by hanqiuzh** [comment]
Reopen this issue as only the first issue is fixed.

@starpit 
For the period problem (issue 2), I found the related code:
- https://github.com/IBM/kui/blob/master/plugins/plugin-core-support/web/css/tab-completion.css#L25
```
.tab-completion-option {
  direction: rtl;
}
```
- https://github.com/IBM/kui/blob/master/plugins/plugin-bash-like/fs/src/lib/tab-completion.ts#L83
```
const completion = lastIsDir ? match : match.substring(partial.length)
```
where partial is `.` for hidden files (e.g. `.bashrc`)
Do you know what're the use cases for these two lines?


For issue 3, do you think we should always run `fs` completions for all commands? as it will pollute results of other commands?

**Comment by starpit** [comment]
i think these are now resolved, with the new TabCompletion.tsx

**Comment by mark-nc** [comment]
@starpit Which versions is the new TabCompletion.tsx in (master, 7.x, 6.x)?
