### ISSUE TITLE
Documentation (even script comments) in webpack build a little off

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [IBM/kui#361]
I'm recording some problems I encountered building the webpack packaging after some of the latest changes.

1.  In `<...dist>/webpack/build.sh` the header comment says
```
# This script builds the webpack bundles. IT DOES NOT build the docker
# image. You can use ./build-docker.sh for that.
```
However, the `build.sh` script in fact invokes `build-docker.sh`.   The assertion that these scripts are disjoint is repeated in `<...dist>/webpack/README.md`.   IMO it would be nice if they WERE disjoint, so if you want to fix this by no longer having one script invoke the other instead of changing the doc, that's fine.

2.  The `README.md` in the `webpack` dir also has a broken link (text is `webpack.json`).

3.   The build customization process described in `kui/docs/dev/build-customization.md` is unclear (IMO) because in some places it talks about overriding or injecting, so the user is left feeling that the directory you specify in `KUI_BUILD_CONFIG` can be partial (and is merged with defaults).  My experience (experience, not exhaustive reading of the code) is that if you specify this directory it had better be total (start out filling it with defaults and then add or modify).   Only the `config.json` optional part is "injected."   I base this on the fact that when I put _only_ the `config.json` that I wanted in this dir, the injected option was recognized but the build did not pick up the default theme.

**Comment by joshuaauerbachwatson** [comment]
I forgot (4) in the initial comment.  There is still `kui/docs/dev/packaging.md`, which, in its section on "browser packaging", mentions the old way of doing a local test and does not mention docker.   Is this stale?   I did not try to test this way since the docker test is sufficient.   If the README in the webpack directory supercedes this, some cleanup is needed.

**Comment by starpit** [comment]
thanks! i think we should split this out into two issues: points 1, 2, and 4 cover docs and comments regarding the building and testing of a webpack client; the third covers build customization. i may split out 3

**Comment by starpit** [comment]
ok, split out the third into #374
