### ISSUE TITLE
Tab.tsx does not render "processing" state

### ISSUE THREAD

**Issue by starpit** [IBM/kui#3646]
maybe start with restoring the "*", but also maybe use a carbon InlineLoading?

**Comment by myan9** [comment]
#3656 restores the `*` of a processing tab. I experimented with the inlineLoading associated with the tab a bit, and somehow I preferred the original `*` to signify a processing tab. We've already showed a loading icon in the Repl Block when a command is still processing, so I kinda like the minimalism that `*` gives to us.
