### ISSUE TITLE
Incomplete Installation Documentation?

### ISSUE THREAD

**Issue by danchirillo** [IBM/kui#3658]
To use Kui, the only requirement called out in the [Kui Installation Guide](https://github.com/IBM/kui/blob/master/docs/installation.md) is the main executable file.  There **seems** to more to the story, though.  The [Kui Experience](https://github.com/IBM/kui#the-kui-experience) video shows running a `kui` command line tool along with `kubectl`, e.g., ```kubectl kui get pods```.

**Comment by starpit** [comment]
thanks for the issue! we agree. we will be improving the developer and user docs over the next few weeks!

**Comment by starpit** [comment]
i think we have this covered much better now, when considering the updated top-level README.md and the new Wiki pages. a related (and still open) issue covers known gaps in the Wiki: https://github.com/IBM/kui/issues/4273
