### ISSUE TITLE
<Translation Verification>some translated strings don't display in KUI Getting Start page

### ISSUE THREAD

**Issue by WalterFang** [IBM/kui#3675]
**Describe the bug**
Some strings in KUI getting start page are translated, but they display as English when change the locale to non-English.

**Steps to reproduce the behavior**

1. Open KUI
2. run help
3. Please refer to the attached screen capture.
my mail is bingfang@cn.ibm.com

**Expected behavior**
The strings should display translated languages.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version:1.0.12
- Operating system:Mac OS
![02 010 070](https://user-images.githubusercontent.com/8808972/75199916-54106a80-579f-11ea-837e-f90e18ca0c9e.jpg)

**Comment by myan9** [comment]
duplicate of #2669
