### ISSUE TITLE
css regression: clicking TopNavSidecar tabs will enlarge the selected tab

### ISSUE THREAD

**Issue by myan9** [IBM/kui#3714]
As I clicked through the TopNavSidecar Tabs, the selection block became larger.

![ezgif com-video-to-gif-14](https://user-images.githubusercontent.com/21212160/75376852-bd2ad780-589e-11ea-8c30-2170c3a55d34.gif)

We used to have fixed tab block with selection. 
![ezgif com-video-to-gif-13](https://user-images.githubusercontent.com/21212160/75376977-f19e9380-589e-11ea-96e2-3d41d3234948.gif)

**Comment by starpit** [comment]
also, tab switching steals focus from either the REPL or the editor content. this might be desirable from an accessibility perspective.... but not for all users, i would think.

in any case, this is i believe the underlying cause for the glitchy UI behavior observed in this issue

**Comment by starpit** [comment]
also, tab switching steals focus from either the REPL or the editor content. this might be desirable from an accessibility perspective.... but not for all users, i would think.

in any case, this is i believe the underlying cause for the glitchy UI behavior observed in this issue
