### ISSUE TITLE
add small left margin and make output for text commands consistent

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#3733]
I downloaded kui version 1.0.12 and used it as a mac app. I noticed that the output of `ls` differs in the left margin when you do `ls` vs `ls -l` as in the first screen shot.

When you use `vi` or `emacs` there is also no margin. This makes taking screen shots (when done manually) a little challenging because it's difficult not to capture the border or outside context. It also looks off compared to a normal terminal (I've reported this before https://github.com/IBM/kui/issues/1331).

<img width="1217" alt="Screen Shot 2020-02-28 at 9 42 13 AM" src="https://user-images.githubusercontent.com/4959922/75558054-2cbfd480-5a0f-11ea-88f4-832d52bdd0cf.png">
<img width="1217" alt="Screen Shot 2020-02-28 at 9 42 47 AM" src="https://user-images.githubusercontent.com/4959922/75558060-2df10180-5a0f-11ea-88f6-b1b93db39902.png">

**Comment by starpit** [comment]
nice finds, thanks!!!

**Comment by starpit** [comment]
btw, with the latest master, the screenshot feature is enhanced so that you can capture regions more flexibly. this is part of a 100% Reactification of the view componentry.

<img width="1282" alt="Screen Shot 2020-02-28 at 10 01 29 AM" src="https://user-images.githubusercontent.com/4741620/75559406-6265bd00-5a11-11ea-9289-983e46c51ec8.png">

**Comment by starpit** [comment]
also in master, as part of the Reactification, tables are now rendered using a react component  (carbon components tables, for now). as a result, tables now look a bit more tabley. this might address the table part of your issue?

<img width="807" alt="Screen Shot 2020-02-28 at 10 05 58 AM" src="https://user-images.githubusercontent.com/4741620/75559724-f172d500-5a11-11ea-85c6-c176f3a9d7b9.png">

**Comment by starpit** [comment]
the react table component also supports pagination for larger table results (it only paginates above some threshold). of note, i used the rubber-band screenshot capability to capture this:

![image](https://user-images.githubusercontent.com/4741620/75559807-1bc49280-5a12-11ea-88b1-00c8a127fc95.png)

**Comment by rabbah** [comment]
Tables look great! Thanks for the tips.

**Comment by starpit** [comment]
resolved in master i think
