### ISSUE TITLE
opening TopNavSidecar results in react Warning in console

### ISSUE THREAD

**Issue by starpit** [IBM/kui#3802]
open file.json
see this Warning (in red text) in the javascript console:

> Warning: React does not recognize the handleTabAnchorFocus prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase handletabanchorfocus instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by myan9** [comment]
I think `handleTabAnchorFocus` is an internal props (I can’t find it in carbon-componet-react/Tab module, their doc also doesn’t mention this prop). However, @type/carbon-component-react overtyped Tab’s props, so we have to tolerant this for now. See issue here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42701

**Comment by myan9** [comment]
fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/issues/42701#issuecomment-630958482
