### ISSUE TITLE
Unable to select pod name using cursor

### ISSUE THREAD

**Issue by rvennam** [IBM/kui#388]
![image](https://user-images.githubusercontent.com/5502967/52299539-a348ea80-2953-11e9-9fc8-c0c0e29f4976.png)

After doing a `kubectl apply` I'm unable to drag my cursor over the pod name to select it. Releasing the mouse click immediately triggers the sidecar. Can the side car opening be changes to double click? 

I'm seeing that this isn't a problem when doing `kubectl get pods`

**Comment by starpit** [comment]
wow thanks for finding this bug. it is a bug in the core table viewer, in the "watch" support. the watch handler was installing a row onclick handler, i'm not sure why. fixing!
