### ISSUE TITLE
old openwhisk host setting is sticky

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#41]
notice in this screen shot that i set a new host name but the shell is posting to a different hostname (see bottom of the screen grab).

<img width="1165" alt="screen shot 2018-12-01 at 9 40 11 am" src="https://user-images.githubusercontent.com/4959922/49329466-31b48080-f54d-11e8-8667-83cfe992722e.png">

**Comment by starpit** [comment]
closing as stale.
