### ISSUE TITLE
Unable to enter input for `ibmcloud login`

### ISSUE THREAD

**Issue by rvennam** [IBM/kui#414]
![image](https://user-images.githubusercontent.com/5502967/52488303-84ce3380-2b8d-11e9-804c-6f8999d5d8db.png)

**Comment by rvennam** [comment]
Related issue - when the spinner is stuck in this position, I'm unable to kill it. I tried all the using Cmd/Ctrl C inputs

**Comment by starpit** [comment]
thanks for the issue. indeed, the `bash-like` plugin does not yet support stdin communication. we should have this support soon.
