### ISSUE TITLE
table status grid layout seems buggy

### ISSUE THREAD

**Issue by myan9** [IBM/kui#4143]
The grid shouldn't have so much width between cells.
![image](https://user-images.githubusercontent.com/21212160/78158277-04ad0200-740f-11ea-934b-e38f8c45a2f8.png)

**Comment by starpit** [comment]
thanks. oddly the layout seems fine for me. i think changing `minmax(1em, auto)` to `1.375em` (which is the dimension of the grid cells) will fix this.

**Comment by starpit** [comment]
we should also take this opportunity to factor the Grid component out of PaginatedTable
