### ISSUE TITLE
Is this electron-only? Is plain browser supported?

### ISSUE THREAD

**Issue by abetkin** [IBM/kui#4172]
As far as I know the main usecase is kubectl, and kubernetes is server software. Isn't browser supported at all? If so, why?

**Comment by starpit** [comment]
hello, thanks for the question! indeed kui can be deployed to a hosted environment. you can develop in this mode by using `npm run watch:webpack` at the top-level. in this mode, the browser client can talk to a proxy (see packages/proxy) which in turn executes the native binaries such as `kubectl` or `oc` or `helm`.

there are also scripts that will build production webpack bundles that target a hosted environment. we are refining the docs here. i'll ping you when they are ready.

we are considering coding up an Operator that will manage this hosted environment.

**Comment by starpit** [comment]
hello! we now have a documentation page covering builds for a hosted application: https://github.com/IBM/kui/wiki/Building-for-Production#scripts-to-aid-in-building-a-hosted-kui
