### ISSUE TITLE
should wsk action invoke be blocking by default?

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#419]
invoke used to be a synchronous operation in the shell - but now is async matching the CLI... was this changed for parity with the CLI?

related: https://github.com/apache/incubator-openwhisk-cli/issues/406

**Comment by starpit** [comment]
this should still be the case; i see your desired behavior, and we do have tests for this. hmm...

**Comment by rabbah** [comment]
did you try in the webpacked version?

**Comment by rabbah** [comment]
I can't reproduce this after updating to master.

**Comment by rabbah** [comment]
I'm re-opening because while I can't reproduce it deterministically, I encounter this from time to time. Starting with a new shell in private browser, built off master, and webpacked, an invoke sends a request to the controller without `?blocking=true`. I even observed once that after one such instance the very next request has `?blocking=true` leaving me really puzzled.

**Comment by rabbah** [comment]
Thanks for tracking this down!
