### ISSUE TITLE
all invokes are asynchronous due to "typeerror"

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#42]
when i invoke a new action, it invokes async instead of sync - there's an error posted to the console:

<img width="1165" alt="screen shot 2018-12-01 at 9 45 13 am" src="https://user-images.githubusercontent.com/4959922/49329497-dcc53a00-f54d-11e8-907a-a6295f2e99cd.png">

**Comment by starpit** [comment]
verified, but this only seems to affect the webpack builds.
