### ISSUE TITLE
Default contexts and /.kube subfolders?

### ISSUE THREAD

**Issue by uhlhosting** [IBM/kui#4274]
Hi,

By default my config files generated by magnum/openstack for kubernetes are in a config file I export these with:

```
for CLUSTER in $(openstack coe cluster list -c name -f value); do
 mkdir -p ~/.kube/${CLUSTER}
 openstack coe cluster config ${CLUSTER} --dir ~/.kube/${CLUSTER} --output-certs --use-certificate --force
done
```

After doing do, I will get the subfolders and each their ssl and config files in. Now I know merging is possible into one file, yet would be great if kui could seek also in subfolders for config files. a rule in form`/.kube/*/config` cannot be so hard to be made or?

Now back to the context issue. 

Each config file has set default context. Thus making Kui at opening unable to render the remaining context, unless any other is explicitly set in place of default. The namespaces are not expandable under @ .

**Comment by starpit** [comment]
thanks for this detailed bug report. and sorry for the delay in responding. this seems like a possibility. to make sure i understand: is the issue when the Kui `contexts` command (this is the command that is executed when clicking on the icon with the kubernetes icon in the bottom status stripe) -- the table is not correct; or is the issue that Kui's kubectl commands do not operate properly?

i think the former?

**Comment by uhlhosting** [comment]
@starpit, the issue is when the config has default context for the cluster, and since i merge usually more configs into one, all who use default context will not have anything @ contexts either the option to select it. I can change between clusters, yet only those who have default namespace changed into kube-system for example will be working in kui's @namespace option. 

<img width="201" alt="image" src="https://user-images.githubusercontent.com/6324047/79424322-41a4f700-7fc0-11ea-8056-bb6141e90e91.png">

<img width="810" alt="image" src="https://user-images.githubusercontent.com/6324047/79424343-45d11480-7fc0-11ea-87bc-ba60fc628c99.png">

So I must always change the default context manually. from default into something else. Not sure if this was not fixed in last release.

**Comment by myan9** [comment]
Hi @uhlhosting! Thanks for the issue report! I'm not sure if I understood your issue correctly... Is your issue saying Kui won't render `@ namespace` at the bottom status stripe unless the default context defines namespace in the kube config files?

**Comment by uhlhosting** [comment]
@myan9 that is correct. If my namespace is just simple like generated by kubernetes, in that case namespace would be `default` thus not rendering it @ namespace in Kui.

**Comment by myan9** [comment]
Hi @uhlhosting! Thanks for clarifying the issue! We could enhance Kui by always rendering `@ default` for empty namespace config. However, I feel like maybe Kui shouldn't render the `@` if it can't find one. Just like the command `kubectl config get-contexts`, it shows empty spot for empty namespace config. Actually, you can still select namespace for your cluster with command `kubectl get ns`.  I have a PR to remove the empty `@`, please feel free to tell us your thoughts. Thanks!
