### ISSUE TITLE
Error from server (NotFound): pods "recommrecommendation-v2-6c5b86bbd8-xrz5h" not found

### ISSUE THREAD

**Issue by maltron** [IBM/kui#4281]
<img width="754" alt="Screen Shot 2020-04-13 at 10 11 33 PM" src="https://user-images.githubusercontent.com/5092469/79175576-76ecf180-7dd4-11ea-9a8f-a32f664d29d7.png">
I am trying to run Kui on Mac and I can't get past the basics. The message I am getting is 

~❯
kubectl delete pod recommrecommendation-v2-6c5b86bbd8-xrz5h
Error from server (NotFound): pods "recommrecommendation-v2-6c5b86bbd8-xrz5h" not found

I am not sure if there is any extra  configuration that I might be missing. 

Please advise 

**System**

- Kui version: Kui 8.4.2
- Operating system: MacOS Catalina 10.15.4

**Comment by starpit** [comment]
thanks for the bug report!

did you type out the command: "kubectl delete pod recommrecommendation-v2-6c5b86bbd8-xrz5h", or was that command executed as a result of clicking on some UI element in Kui?

thanks for the help clarifying this issue.

**Comment by maltron** [comment]
thanks @starpit for a quick response :)

Yes, I actually typed the command and look for some kind of configuration that I missed. I couldn't find anything that it would help me in that regard.

**Comment by starpit** [comment]
i think this might be a bug with tab completion. investigating!

**Comment by maltron** [comment]
@starpit You are correct. I start to pay attention and it seems tab completion is failing

**Comment by starpit** [comment]
PR in the pipeline. thanks again for identifying this issue. we should have a release rolled out in a few hours.

**Comment by starpit** [comment]
a fix has been released in build 8.4.3
