### ISSUE TITLE
How do I use it with aws-vault?

### ISSUE THREAD

**Issue by ctwise** [IBM/kui#4282]
I'd love to try this out but I can't find where I can run it with aws-vault.

**Comment by ctwise** [comment]
Never mind. It's trivial. ' aws-vault exec <context> -- C:\Program Files\Kui-win32-x64\kui.exe'

**Comment by starpit** [comment]
interesting. thanks for bringing this up. if you can think of any features we (all) can add to Kui that would assist with AWS generally, please open up feature request issues!

for example, are there any status stripe widgets that would help with keeping track of AWS context or auth state? https://github.com/IBM/kui/wiki#option-4b-status-stripe-widgets
