### ISSUE TITLE
wrong link to kui icon in webpack

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#432]
After webpacking, `themes/kui.css` file contains the following:

```
.application-icon {
    background-image: url('../../icons/svg/kui.svg');
}
/* body.not-electron:not(.webpack-local) .application-icon {
    background-image: url('../icons/svg/kui.svg');
} */
```

The path to `kui.svg` is wrong and should be `../icons/svg/kui.svg`. It's masked by serving the kui in the container from `/` and you can't bottom out of `/`.

Manually patching the url in the console will render the icon correctly.

![image 5](https://user-images.githubusercontent.com/4959922/52647010-e35b2080-2eb1-11e9-8a65-a6d483e88ee6.png)

**Comment by starpit** [comment]
the ../../ bits are slowly going away, and this is one of the few remaining vestiges. hopefully we can fix this by having the electron clients refer to html ancillaries in the same way as webpack does.
