### ISSUE TITLE
Confusion about the state changed shown in animation

### ISSUE THREAD

**Issue by maltron** [IBM/kui#4341]
I just love using Kui but I personally I am bit confusing related to the Pod animation. 

When I type: kubectl delete pod  customer-77dc47d7f8-qxdnf

It dynamically shows the pod chaging from Pending -> Offline

However, when I deploy a Deployment resource and type: kubectl get pods, all the Kui magic disappears. It does show some pods Running and some others "Containercreating" but never changes into Running. 

One  of the compelling reasons I like about Kui, it's getting instant feedback about the state of the containers and sometimes, I don't see this happening. I wonder if this is a bug, a configuration that I missed or the feature is not there (I remembering seeing older versions of Kui which shows the state changing during kubectl get pods).

I wonder if anyone cloud clairfy that

Thanks

**Comment by myan9** [comment]
Hi @maltron ! Thanks for the feedback!  Kui watches resource updates for a subset of kubectl commands: `create, apply, run and delete`, and will stop watching when the resources reach the final state. e.g. Kui will stop watching for `kubectl  create pod` command when the pod  is `running`. For `kubectl get` commands, Kui pretty-prints the table and allows you to drilldown to the resource details from the resource name. If you want to turn on Kui's watcher for `kubectl get` commands, you can use, e.g. `kubectl get pods -w` commands, which would watch for resource updates just as plain `kubectl` does. 

We have an issue to allow toggling watchability of Kui tables: https://github.com/IBM/kui/issues/1456, which would allow you to click a widget to turn on the watch mode from `kubectl get pods` command. This would be a nice feature.

**Comment by myan9** [comment]
oh I think you're also asking a feature request for a watcher table of command `k deploy deployments`. We'll add this to list, thanks!

**Comment by maltron** [comment]
@myan9  Thanks so much to get backing to me. Indeed, by using kubectl get pods -w, I see the magic happens. This is really amazing and brings a new experience to. Kubernetes. 

Regarding the "deployments", it would be swell if we could see the pods being creating on-the-go.

Also,  I alo enjoy the capability of  looking  at the YAML. I wonder  if you guys has plans to provide editing capabilities to the YAML .

**Comment by myan9** [comment]
Hi @maltron ! Good idea! we have an issue also talking about adding the edit capability of yaml, https://github.com/IBM/kui/issues/762, this is on our short list. Thanks!
