### ISSUE TITLE
Detail Window is still open 

### ISSUE THREAD

**Issue by maltron** [IBM/kui#4362]
I wonder if this a feature or a bug :)

Step #1: Open a Tab and do run some commands
Step #2: Open a Second tab, list some services and see everything in the details window (right side). 

...Then close the Details Window.
![Screen Recording 2020-04-24 at 2 49 59 PM 2020-04-24 15_05_56](https://user-images.githubusercontent.com/5092469/80243202-262f9100-863d-11ea-8b75-b87fc8254668.gif)

I've notice back on the first Tab, the details windows is still open.

**Comment by starpit** [comment]
hi @maltron thanks for this issue, keep them coming!

this is indeed a feature: Kui has a separate sidecar for every tab. we have thought about making the sidecar global. which would you prefer?

**Comment by maltron** [comment]
@starpit Thanks for getting back to me. I usually use the sidecar to investigate details of a particular resource in that particular tab. 

So my vote will be NOT making globally available. 

Of course, as an alternative, one could think of a checkbox that it would make globally available. (similar on what some Desktop Windows offers: Available on all workspaces).

**Comment by starpit** [comment]
ah, i see. this is actually a regression from the work to port the sidecar over to React componentry. we'll look into it! thanks again!

**Comment by starpit** [comment]
this should be fixed in [8.6.1](https://github.com/IBM/kui/releases/tag/v8.6.1)
