### ISSUE TITLE
add support for PatternFly components

### ISSUE THREAD

**Issue by myan9** [IBM/kui#4364]
We can add the following initial PatternFly Components supports, and allow users to choose from Carbon or PatternFly:

# Components without PatternFly impls

- [x]  [Breadcrumb](https://www.patternfly.org/v4/documentation/react/components/breadcrumb)
- [x] left nav in LeftNavSidecar e.g. via [Navigation](https://www.patternfly.org/v4/documentation/react/components/nav)
- [x] RadioTable
- [x] Alert
- [x] Markdown uses various Carbon elements
- [x] Confirm makes hard-coded use of Carbon Modal
- [x] TopTabStripe e.g. via [Tabs](https://www.patternfly.org/v4/documentation/react/components/tabs)
- [x] tabs in TopNavSidecar
- [x] Tables
- [x] Sidecar/Badge.tsx makes hard-coded use of Carbon's Tag
- [x] TabCompletion.tsx for some reason uses a Carbon Button
- [x] Search.tsx
- [x] Screenshot.tsx makes hard-coded use of Carbon's Button
- [x] plugin-iter8 uses a number of Carbon components

# Components with Carbon impls that need to be eliminated

- [x] DropDown
- [x] Popover
- [x] Tag
- [x] Icons
- [x] CodeSnippet
- [x] Breadcrumb
- [x] Button
- [x] Accordion
- [x] Loading
- [x] Navigation

# Styling

- [x] [Color Palette](https://www.patternfly.org/v4/design-guidelines/styles/colors); see plugin-patternfly4-themes
- [x] [Icons](https://www.patternfly.org/v4/design-guidelines/styles/icons); see plugin-client-common/src/components/spi/Icons

**Comment by starpit** [comment]
TopTabStripe covered by #6527

**Comment by starpit** [comment]
Markdown:
```
import {
  Link,
  StructuredListWrapper,
  StructuredListHead,
  StructuredListRow,
  StructuredListCell,
  StructuredListBody,
  OrderedList,
  UnorderedList,
  ListItem
} from 'carbon-components-react'
```

**Comment by starpit** [comment]
Markdown covered by #6563

**Comment by myan9** [comment]
It seems like we have to use the ref of search input to manage the focus. We want the search input to focus when user hits ctrl+f, and stay focused when electron found match and set match result state. With PatternFly’s search input (function component), we can’t access the refs and manage the focus by ourselves.

someone raised the issue to PF in 2020, but the fix hasn’t been merged yet. https://github.com/patternfly/patternfly-react/issues/5168
