### ISSUE TITLE
`kubectl edit` cannot edit all resources

### ISSUE THREAD

**Issue by hanqiuzh** [IBM/kui#4551]
**Describe the bug**
`kubectl edit RESOURCE` without the resource name doesn't work 

**Steps to reproduce the behavior**

1. Run `kubectl edit ns`

**Expected behavior**
Can still edit.

**Screenshots**
<img width="639" alt="Screen Shot 2020-05-13 at 9 25 03 AM" src="https://user-images.githubusercontent.com/31426239/81818148-a427df00-94fb-11ea-9b51-35a5cab0c251.png">
same issues for `oc`
<img width="564" alt="Screen Shot 2020-05-13 at 9 23 49 AM" src="https://user-images.githubusercontent.com/31426239/81818011-7773c780-94fb-11ea-8461-8f9e1e9663d2.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version: master branch 05/13/2020
- Operating system: mac OS

**Comment by starpit** [comment]
thanks for the bug report!
