### ISSUE TITLE
Allow easier rerunning of command from REPL/terminal view

### ISSUE THREAD

**Issue by chrisahl** [IBM/kui#4570]
This enhancement would allow the user to rerun a command from the REPL/Terminal view window.  This would save keystrokes for the user because they would not need to arrow up through the history of commands and then press enter.  They would simple click on a previously run command and have it run again.  So in the example below, click on either the `>` and/or `oc get nodes` and have it run again.

![image](https://user-images.githubusercontent.com/32707829/81951727-875eda80-95d3-11ea-8921-18a7b7b92e9d.png)

Or I guess you could use some icon like a circular arrow,  to indicate rerun, and place it to the left of the `>`.     Whatever items allow the rerun of the command, a tooltip needs to be associated with it so the user knows what action will happen if they click it.

**Comment by starpit** [comment]
hello, thanks for the feedback! this is a nice idea.

we are thinking about adding perhaps an overflow/dropdown menu to each Input/Output block. in this menu, we might have Screenshot, Refresh, ... options. thoughts? anything else you might want to add so such a menu?

**Comment by chrisahl** [comment]
Do you have a mock up or drawing/pic of where this dropdown would be?  I am looking to reduce number of clicks/keystrokes to rerun the cmd.  Would prefer a single click, especially if it is a cmd you are running every n seconds (aka watch) to see what is happening

**Comment by starpit** [comment]
got it, this is great feedback!
