### ISSUE TITLE
TabContent initializingSession needs to be a Kui property

### ISSUE THREAD

**Issue by starpit** [IBM/kui#4596]
right now TabContent.terminal() has a hard-coded handler for

```typescript
    if (this.state.sessionInit !== 'Done') {
      return <Loading description={strings('Please wait while we connect to your cloud')} />
```

this will allow clients to provide a splash screen for "While Loading"

**Comment by starpit** [comment]
also, we should allow the client to define an `onSessionInit`

```typescript
 public componentDidMount() {
    eventChannelUnsafe.once(`/tab/new/${this.props.uuid}`, () => {
      // onSessionInit
      this.setState({ sessionInit: 'Done' })

      if (this.props.onTabReady) {
        this.props.onTabReady(this.state.tab)
      }
    })
```

**Comment by starpit** [comment]
probably we can also add a hook for session reconnect?

```typescript
 private onOffline() {
    this.setState({
      sessionInit: 'InProgress'
    })

    initializeSession(this.state.tab).then(() => {
      // onSessionReconnect
      this.setState({
        sessionInit: 'Done'
      })
    })
  }
```

**Comment by hanqiuzh** [comment]
So in this design, client will be able to customize the loading page? That will be nice

And any design for error handling & showing error msgs when init failed? Or this will only be the loading page?

**Comment by starpit** [comment]
We will be adding `loading` and `reinit` properties to `<Kui/>`. We should also add error handling, thanks for the reminder!

**Comment by starpit** [comment]
for error handling, there will be a `<Kui/>` configuration property `loadingError`

these properties are defined in plugins/plugin-client-common/src/components/Client/KuiConfiguration.tsx
