### ISSUE TITLE
k get crd shows namespace in the table breadcrumb

### ISSUE THREAD

**Issue by starpit** [IBM/kui#4599]
crds are cluster scoped. is this knowable?

**Comment by myan9** [comment]
We could use `k api-resources --api-group=apiextensions.k8s.io --namespaced=true` to see if this resource is namespace-scoped or not

**Comment by starpit** [comment]
this also affects `kubectl top node` and `kubectl top pod`, which also incorrectly display the namespace in the breadcrumb. see #4737 for an example screenshot.

**Comment by starpit** [comment]
this has been worked around, for now, via some heuristics. see `isClusterScoped` in plugin-kubectl
