### ISSUE TITLE
grid is not accessible

### ISSUE THREAD

**Issue by starpit** [IBM/kui#4601]
we use red and green right against eachother

1) stop using red and green together?
2) use check and cross icon in addition, instead?

**Comment by starpit** [comment]
proposal: in the short term, we will amend the `title` attribute of grid cells to specify the resource name in addition its status; we will also investigate using a pattern fill for error cells.

beyond that, we might pursue a real tooltip, but that's beyond MVP.

**Comment by mark-nc** [comment]
@starpit Is there another issue open where we can pursue visual design input on colors and icons for this from our designer (@jackiwakin)?  She has a bunch of mock-ups ready with suggested icons, colors, etc. that seem pretty straight forward.
