### ISSUE TITLE
clean up kubectl events table

### ISSUE THREAD

**Issue by starpit** [IBM/kui#4604]
1) when sidecar is open, try to show Reason and Message only
2) maybe even when closed, as long as the user hasn't specified -o, --field-selector, etc. maybe we can make a better choice than kubectl's default

**Comment by myan9** [comment]
new issue found: When I type `k get events` and then open the sidecar, the events table looks broken with the visible columns. However, this issue doesn't exist if you click `show events` from sidecar and click `show as table` from the WatchPane.

**Comment by starpit** [comment]
minimal 8_7_x fixes:

1) Show Events should not specify -o wide
2) with sidecar open, only show Reason and Message

**Comment by starpit** [comment]
fixed in 8_7_x, but not master
