### ISSUE TITLE
the table in condition tab has row hover effect, but not interactive

### ISSUE THREAD

**Issue by myan9** [IBM/kui#4606]
This issue also affects table in LeftNavSidecar, e.g. kubectl -> option tab

**Comment by starpit** [comment]
before starting work on this one, we should consider this bug w.r.t. #4603

**Comment by showeimer** [comment]
Let's drop this issue; I forgot to remove from list after speaking with designers that his behavior although not interactive still helps with readability of tables.

**Comment by starpit** [comment]
ok. what do you think of the value of the Conditions tab? is it even worth keeping?

**Comment by showeimer** [comment]
Hmm I haven't found it useful; I would be okay with removing if others agree.

**Comment by starpit** [comment]
ok. removing.
