### ISSUE TITLE
kubectl logs mode should not say "No log data" so eagerly

### ISSUE THREAD

**Issue by starpit** [IBM/kui#4624]
we probably need to introduce a bit of hysteresis. if it takes a second or two to fetch the log data... we don't want to see "No log data" followed immediately by some log data?

**Comment by mark-nc** [comment]
Agreed that if we are waiting on the retrieval of log data it should not say "No log data", but likewise it should say something in case it takes longer than a second, just to let the user know it is not hung up.  Something like "Retrieving log data..." displayed initially and then replaced once the log data is available to be displayed, or an error displayed if there was an error returned from the request.

**Comment by starpit** [comment]
nice! right now there is a banal spinner while it's fetching. let's consider updating that as a separate design issue. this issue covers the plumbing necessary to make the hysteresis possible.

**Comment by mark-nc** [comment]
How will the spinner behave if there is an error?  Will it stay there forever?
