### ISSUE TITLE
Ctrl-W closes Kui

### ISSUE THREAD

**Issue by Xcess** [IBM/kui#4638]
I know Ctrl+W is used to close windows on all browsers and this is why it does this in Kui. But as there is a interactive bash shell inside, the user expects to remove the last argument from command line when pressing Ctrl+W as it does that is all major shells.
I find myself closing Kui every 30mins and I'm so frustrated by this.
Please remove this behaviour or add an option to override it.

Thanks!

**Comment by starpit** [comment]
hello, and thanks for the bug report. much appreciated.

to help clarify the issue, may i ask: are you running on linux or windows (i.e. not a mac); is this correct?

**Comment by Xcess** [comment]
You're welcome

I'm running on Linux
`1.4 Solus "Solus" 4.1 fortitude`

`5.6.13-153.current`

**Comment by starpit** [comment]
will be coming in the next minor release: 8.8.0. i'll ping this thread when it is out!

**Comment by starpit** [comment]
8.8.2 has been released
