### ISSUE TITLE
exec into pod

### ISSUE THREAD

**Issue by gorkemozlu** [IBM/kui#4639]
hi
It would be nice to have a exec button in the pod page, near to "delete" or "show node" buttons.

![image](https://user-images.githubusercontent.com/45913400/82320569-2e7cb100-99dc-11ea-87fa-1067abb79dd7.png)

**Comment by starpit** [comment]
excellent idea, thank you!

**Comment by starpit** [comment]
will be coming in the next minor release: 8.8.0. i'll ping this thread when it is out!

**Comment by starpit** [comment]
8.8.2 has been released
