### ISSUE TITLE
restore wsk-undeployed-action warning for preview

### ISSUE THREAD

**Issue by myan9** [IBM/kui#464]
For now, we added **undeployed-action warning** in fsm2graph.ts, and when the **preview** entity gets returned, sidecar replaces the warning  header with **entity.subtext**. We should restore the warning feature for **preview** like the screenshot below:

![image 1](https://user-images.githubusercontent.com/21212160/52877430-f24b0880-3127-11e9-877b-0f123b6639d7.png)

**Comment by starpit** [comment]
closing as unimportant for now
