### ISSUE TITLE
hard coded auth key leaking to new <action>?

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#468]
I'm not sure why this is hardcoded - it's not really guaranteed to be true for local deployment and leads to surprising results. 

https://github.com/IBM/kui/blob/0a411997976f46ff4be03ac27b49ebb27b42df4c/plugins/plugin-openwhisk/src/lib/cmds/auth.ts#L401

On `new x`, and then clicking deploy, the authentication header sent is this hard coded key even though `auth add ....` was done explicitly. The best I can figure so far is that maybe this key is somehow leaking threre.

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/oui/issues/58
