### ISSUE TITLE
Add a quickart for a custom CLI

### ISSUE THREAD

**Issue by pc-tradelab** [IBM/kui#4694]
Hello,

this project is really promising, however it is difficult to start developping a custom CLI: is it possible to improve the documentation , maybe with a quickstart that would show how to write a simple CLI using Kui from scratch to packaging ?

**Comment by myan9** [comment]
Hi @pc-tradelab , have you check out our [Developer Guide ](https://github.com/IBM/kui/wiki#approaches-for-enhancing-kui) ? It has tutorial for enhancing Kui by  custom CLI. Thanks!

**Comment by starpit** [comment]
thanks for the feedback. this is a good idea. we will put our heads together on it.

**Comment by myan9** [comment]
Hi @pc-tradelab , here's a list of resources that's related to your request:
- [How to write new commands](https://github.com/IBM/kui/wiki/1.-Commands)
- [Example of enhancing Kui with new commands](https://github.com/IBM/kui/tree/master/docs/example/AnimalApp/plugins/plugin-example/src/commands)
- [Build for Production](https://github.com/IBM/kui/wiki/4.-Building-for-Production)
