### ISSUE TITLE
activation list errors and does not paginate

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#474]
steps to reproduce: generate more than 10 activations and then run activation list and try to get the next page.

<img width="1422" alt="screen shot 2019-02-15 at 10 50 23 pm" src="https://user-images.githubusercontent.com/4959922/52894224-3106b000-3174-11e9-8930-7b0cebdbebe3.png">

**Comment by starpit** [comment]
@myan9 this is probably a webpack-only issue, as we have fairly extensively tests for this in electron mode.
