### ISSUE TITLE
kui shows a default namespace even when a different namespace is set in the context

### ISSUE THREAD

**Issue by andrewnazarov** [IBM/kui#4764]
**Describe the bug**
I'm setting my current namespace with `kubens`. This information is stored in the kube context. But after doing `kubectl get po` kui shows that the current namespace is **default** no matter what is in the kube context. Although all shown pods are from my namespace, not from default.

**Steps to reproduce the behavior**

1. Add a namespace to the current context whether via `kubens` or `kubectl config set-context --current --namespace=` 
2. Do `kubectl get po` in kui without specifying a namespace

**Expected behavior**
My namespace shown in breadcrumbs

**Screenshots**
<img width="645" alt="Screenshot 2020-05-29 at 11 05 02" src="https://user-images.githubusercontent.com/11255710/83236567-6209c900-a19c-11ea-9697-4325961e641c.png">

**System**

- Kui version: 8.7.6
- Operating system: macOS Mojave 10.14.5

**Comment by starpit** [comment]
thank you for reporting this bug. we'll get right on it.
