### ISSUE TITLE
Win10 - Namespace & Path Issue

### ISSUE THREAD

**Issue by Berndinox** [IBM/kui#4912]
**Describe the bug**
Can not set a NS  via context.

**Steps to reproduce the behavior**
![image](https://user-images.githubusercontent.com/1122698/84862917-519a8f00-b074-11ea-96be-2c6fa2b2dcdf.png)

**Expected behavior**
after selecting the NS, `kubectl get pods` should show up my pods
but i have to kubectl get pods -n=wp-bernd

**System**

- Kui version: 8.9.4
- Operating system: Windows 10

**EDIT**:
**Another Issue**

```
cd C:\Users
cd: no such file or directory: C:Users
```
Windows Path Style is wrong:
```
cd C:/Users
C:\Users

Users/ >> Prompt
```
Imoh you can not copy paste PATHS (e.g. usefull for local helm charts)

EDIT:
Another Another Issue:

Cant apply changes when editing YAML.

```
Error applying changes
ENOENT: no such file or directory, open 'C:\tmp\kui-f2a90308-a712-4fec-988e-66ace0a9f045'
```

Well i really like how the tool is set up, however it seems not to be usable on windows right now.

**Comment by Berndinox** [comment]
```
cd C:\Users
cd: no such file or directory: C:Users
```

_cd C:/Users
C:\Users

Users/ >> Prompt_

**Comment by starpit** [comment]
thanks for the bug report!

re: the first issue; what version of kubectl are you using?

re: the second issue; indeed, this seems to be a windows-specific issue. we will investigate. thanks!

**Comment by Berndinox** [comment]
v1.17.5

**Comment by starpit** [comment]
thanks. can you verify whether this command works on its own (just from your normal terminal, not kui):

```bash
kubectl config view --minify --output 'jsonpath={..namespace}'
```

**Comment by Berndinox** [comment]
```
PS C:\Users\Bernd> kubectl config view --minify --output 'jsonpath={..namespace}'
wp-bernd
PS C:\Users\Bernd> kubectl get pods
NAME                                  READY   STATUS    RESTARTS   AGE
wp-bernd-wordpress-7c95bdf785-65flb   2/2     Running   0          15h
wp-bernd-wordpress-7c95bdf785-dzg4j   2/2     Running   0          15h
PS C:\Users\Bernd>
```

**Comment by starpit** [comment]
this is very helpful, thank you. we were indeed able to replicate the jsonpath error on windows, even with the latest Kui 8.10.0.

Works: launched from git bash
Does not work: launched from powershell

if git bash is an option for you, that may help you work around the bug until we can get a fix in place for the powershell scenario.

**Comment by Berndinox** [comment]
thanks for looking into!
Yeah i'll use GitBash meanwhile!

**Comment by Berndinox** [comment]
sorry to nerve again but another thing i found is:

The path used for storing the temp file of the current edit ist "C:\tmp"
This is non optimal because a default-user (non-admin) may not be able to create this folder.
You should consider: %localappdata%\.kui

After creating the folder C:\tmp i can see the files create within.

**Comment by starpit** [comment]
gotcha. thanks!

**Comment by starpit** [comment]
to confirm: did you see the c:\tmp after editing a kubernetes resource?

**Comment by Berndinox** [comment]
nope, i had to manually create it.

**Comment by starpit** [comment]
thanks! we should have a few fixes for you shortly

**Comment by starpit** [comment]
8.10.1 has been released with a few fixes

**Comment by Berndinox** [comment]
Gonna try it out asap and give you feedbackl - thanks for your effort
