### ISSUE TITLE
hard-wired use of c:\tmp on windows

### ISSUE THREAD

**Issue by starpit** [IBM/kui#4928]
nope, i had to manually create it. `"mkdir C:\tmp"`
After creating that folder the temp files started to appear.

![image](https://user-images.githubusercontent.com/1122698/84924421-c697b400-b0c8-11ea-950f-12bd85db3324.png)

may a cleanup-job would make sense aswell :)

_Originally posted by @Berndinox in https://github.com/IBM/kui/issues/4912#issuecomment-645480609_

**Comment by starpit** [comment]
so far, the only place i can see this coming from is kubectl edit.ts

**Comment by Berndinox** [comment]
Hej there,
looks like some slashes are missed:

```
Error applying changes
error: the path "C:Users\\usernameAppData\\LocalTemp\\kui-52880Ao7KayOHU8q" does not exist
```

should be:
`C:\\Users\\username\\AppData\\LocalTemp\\kui-52880Ao7KayOHU8q`
