### ISSUE TITLE
"OC project" does not change namespace in footer bar

### ISSUE THREAD

**Issue by subbarao-meduri** [IBM/kui#4953]
**Describe the bug**

**Steps to reproduce the behavior**

1. While running against OCP, from console prompt, run 
```
oc project <valid-project-name>
```
2. The default `namespace` is changed to match with the project set by command. 
3. The `namespace` value in footer did not change, remained as older value.

**Expected behavior**
The `namespace` value should change to the corresponding project namespace

**Screenshots**
![image](https://user-images.githubusercontent.com/5341831/85320836-b5b4bd00-b491-11ea-83c7-8a364a1ba267.png)

The `namespace` in footer changes correctly, if for example, I change namespace in current context via
```
kubectl config set-context --current --namespace=<valid-namespace>
```
Expecting the same behavior with `oc` commands as well.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version: 8.10.0
- Operating system: Chrome Browser

**Comment by starpit** [comment]
thanks for the bug report! so far, it seems that this a problem in browser clients only

**Comment by starpit** [comment]
We have a test gap: certain `logs` tests were only being run against `kubectl`. In fixing this, we ran into this latent `oc` bug: https://github.com/openshift/oc/issues/365

So for now, the PR addressing this Kui issue will have one test disabled, until that `oc` bug is fixed. For future reference, look in logs-multi.ts
