### ISSUE TITLE
Hard to read deletion warning message confirmation button text `Yes, I am sure`

### ISSUE THREAD

**Issue by chrisahl** [IBM/kui#4995]
**Describe the bug**
I find it hard to read the warning message confirmation button text `Yes , I am sure`, black text on red background and consider this a usability issue.

**Steps to reproduce the behavior**

1. From terminal, create a namespace
2. In KUI, list namespaces
3. In KUI, select a namespace
4. Press the delete/trash can icon to delete the namespace.  A warning box is displayed.  I find it very hard to read the black text on the red background.    Is this color scheme based on the Red Hat guidelines?

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/32707829/85722135-014cae00-b6c0-11ea-8c78-9b46c1354c1b.png)

**System**

- Kui version: 8.10.3 (ACM)

**Comment by chrisahl** [comment]
Comment from Jacki:
 the text should be white on red for the button [(Carbon component)](https://www.carbondesignsystem.com/components/modal/usage/#danger-modal)

**Comment by starpit** [comment]
nice catch, thanks!

**Comment by chrisahl** [comment]
Fix verified in 8.10.4
