### ISSUE TITLE
specify those tests that need local access

### ISSUE THREAD

**Issue by myan9** [IBM/kui#508]

**Comment by starpit** [comment]
isn't this closed by #716?

**Comment by myan9** [comment]
> isn't this closed by #716?

#716 only contains changes in mocha layer 1 (since we only test webpack in layer 1 for now). I have other test changes (e.g. OpenWhisk, Composer) in local and haven't push them to master. Will push them with webpack test enabled in other layers.

**Comment by starpit** [comment]
still, we should be specific about things. we already added (via that PR) support for this (localDescribe) to the core test rig. we can have separate issues for webpack-enabling various layers?

**Comment by starpit** [comment]
this should now be mostly addressed
