### ISSUE TITLE
link resource disappear

### ISSUE THREAD

**Issue by yuecchen** [IBM/kui#5100]
The link of the following section of wiki, didn't contain any resource.

![image](https://user-images.githubusercontent.com/24837518/87000133-e2cdd300-c1e6-11ea-8d98-134c2fd41ccd.png)
https://github.com/IBM/kui/blob/master/plugins/plugin-client-common/src/components/Popup.tsx

![image](https://user-images.githubusercontent.com/24837518/87000276-422be300-c1e7-11ea-824e-916cc4c709b3.png)

This is important to us, because we need to develop features based on the input bar.

**Comment by starpit** [comment]
thank you!

**Comment by myan9** [comment]
Hi! Thanks for reporting this issue! I fixed the link pointing to the source file of Kui's Popup mode. If you're looking for configuring your client to use Kui's bottom input, you can add `bottomInput=true` or `bottomInput=[Your Custom Input Component]` to your client's index.tsx, as documented in : https://github.com/IBM/kui/wiki/5.-How-to-Customize-Your-Client#client-properties. Example of using a custom bottom input is hosted in Kui's plugin-client-alternate: https://github.com/IBM/kui/blob/master/plugins/plugin-client-alternate/src/index.tsx. Thank you!
