### ISSUE TITLE
Current namespace/project not shown when switching between existing tabs

### ISSUE THREAD

**Issue by chrisahl** [IBM/kui#5101]
**Describe the bug**
Switching between tabs does not get the namespace shown on the bottom of the page to update.  The displayed namespace is incorrect.

**Steps to reproduce the behavior**

1. Open tab 1, run command `oc project open-cluster-management`
2. current namespace/project shown at bottom changes from default to  open-cluster-management
3. Open tab 2, run command `oc project hive`
4. current namespace/project shown at bottom changes from default to hive
5. switch to tab 1, the current namespace/project remains hive, even though it is actually open-cluster-management

**Expected behavior**
Correct namespace for the tab should be shown

**Screenshots**
In the screenshot below, I was in tab 1 and ran `oc get pods` then switched to `tab 2` and ran `oc get pods`.  tab 2 namespace is hive and pods are displayed for hive but namespace shown at bottom is incorrect.

![image](https://user-images.githubusercontent.com/32707829/87047069-f9186680-c1c7-11ea-81b1-d33bca8d041e.png)

**System**

- Kui version: 8.10.11
- Operating system: ACM/OCM

**Comment by starpit** [comment]
thanks. the bug here is that we are wiring to /tab/switch/request (i.e. the *initiation* of a tab switch) rather than /tab/switch/complete. thanks!
