### ISSUE TITLE
Display a total of the number of entries

### ISSUE THREAD

**Issue by chrisahl** [IBM/kui#5137]
Many times when I run a query, I want to know how many entries are returned.  For example, `kubectl get pods` or `kubectl get namespaces`.  Right now the user has to manually count.   Would be nice if a total was listed,  at the bottom of the list.  Possibly in the row that shows the list/grid buttons?   Or somewhere around there... 

![image](https://user-images.githubusercontent.com/32707829/87575512-0b017a00-c69e-11ea-9f4e-bd19bca299af.png)

Build: v8.10.12

**Comment by starpit** [comment]
this is a great idea! i think your client disables the table header, but that is another option for placement of the row count, e.g.

![image](https://user-images.githubusercontent.com/4741620/87576603-a0e9d480-c69f-11ea-8600-cd8b32408ced.png)

**Comment by chrisahl** [comment]
Yes, we do not have the table header so row count would need to appear somewhere else for ACM

![image](https://user-images.githubusercontent.com/32707829/87582812-f5de1880-c6a8-11ea-9947-f1c4b924f843.png)

**Comment by starpit** [comment]
that makes sense, thanks for the feedback.

we will start with adding the capability to display row count (to start with, this will be placed in the header, since there are views, e.g. the RadioTables that result from `kubectl get ns`) that have no place for a footer. then, we can treat as a separate UX issue the topic of where to put the row count.

**Comment by chrisahl** [comment]
@starpit Any chance you can paste a screenshot of this new function in action?

**Comment by starpit** [comment]
sure thing. this is the namespace RadioTable in master.

![image](https://user-images.githubusercontent.com/4741620/87681997-52930f00-c74d-11ea-9214-6dab92ba490f.png)

**Comment by starpit** [comment]
and a `kubectl get pods -w` in master

![image](https://user-images.githubusercontent.com/4741620/87682391-c59c8580-c74d-11ea-9001-2bfeab17456f.png)
