### ISSUE TITLE
Closing a tab is having unexpected behaviour

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [IBM/kui#5220]
**Describe the bug**
When I am having 2 tabs, closing the tab on the left takes me to that tab itself. This case happens for multiple tabs too so one can lose context while closing a different tab

**Steps to reproduce the behavior**

1. Open 2 tabs
2. Perform different operations on the 2 tabs
3. Select the right hand tab
4. Close the left hand tab
5. See that you are now looking at the tab you just closed and the tab that was opened is gone.

**Expected behavior**
Closing a tab closes that particular tab and does not shift the tab names

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Kui version:8.10.13
- Operating system:Win10 1909

**Comment by starpit** [comment]
thanks! we'll check it out

**Comment by starpit** [comment]
thanks again for the bug report. the fix has been merged, and will be released in 8.11.1 shortly. i'll ping this thread when the patch has been released.

**Comment by starpit** [comment]
8.11.1 has been released!
