### ISSUE TITLE
kubectl contexts  table has blank rows when in splits

### ISSUE THREAD

**Issue by starpit** [IBM/kui#5230]

**Comment by SayakMukhopadhyay** [comment]
Moreover, 
* whatever context I select gets moved to the bottom of the table.
* the columns of the context table are way too narrow.
* The selected context is always a single height row unlike the unselected rows which wrap their contents
![image](https://user-images.githubusercontent.com/13748882/88173791-cbf49b00-cc40-11ea-8394-7a0a2a3ea003.png)

**Comment by starpit** [comment]
hi thanks! the narrow width and blank rows (when presented in a split) will be fixed by #5238 

re: the selected row being presented at the bottom. this was an intentional design choice, though one we can easily change if it does not work out!

the thinking was this: if i have a large number of namespaces (try `k get ns` or click on the namespace widget at the bottom, which also executes that command). in my case, i have a large number of namespaces. as we switched namespaces using Kui, it would be very difficult to keep track of what was actually selected -- because the selected row would be just one of perhaps several dozen, and so would almost certainly be off-screen.

this issue is less of a concern for contexts, as it is probably the case that most users have no more than a handful of those.

thoughts?

**Comment by SayakMukhopadhyay** [comment]
> hi, and thanks! the narrow width and blank rows (when presented in a split) will be fixed by #5238

Awesome!
> re: the selected row being presented at the bottom. this was an intentional design choice, though one we can easily change if it does not work out!

Well, I can certainly understand the requirement. It was a bit jarring from my experience. Would it be possible to make this an option so that people from both worlds can take advantage of it?

**Comment by starpit** [comment]
an example of namespace selection UX:

![ezgif com-optimize](https://user-images.githubusercontent.com/4741620/88175408-d3418780-cbf3-11ea-99e4-a5fed9b5ad65.gif)

**Comment by starpit** [comment]
as an alternative design, we could keep the selected row in-body, but show the selection (also) in the Breadcrumbs at the top, e.g.

Namespaces / 84 rows / selected is default

**Comment by SayakMukhopadhyay** [comment]
Haha, I was pretty much typing the exact same thing. yeah, I would suggest, keep the selected row in the body along with the tick mark and also have the darker coloured footer

**Comment by starpit** [comment]
nice idea!

**Comment by starpit** [comment]
we'll capture the UX work in a separate issue

**Comment by starpit** [comment]
The fix has been merged. The bug came about from a one-liner, where the Name column was hidden. This was a buggy attempt to improve things, but also very easy to back out. The fix will be released shortly, as part of 8.11.2.
