### ISSUE TITLE
UX: RadioTable should show selected row in the table body

### ISSUE THREAD

**Issue by starpit** [IBM/kui#5239]
See #5230 comments for a discussion on this issue. Right now, we show the selected row in the footer and *not* in the body. The options are:

1) show in footer *and* body (first choice, i think?)
2) show in breadcrumb header *and* body
3) show only in body (a normal radio table)
4) show only in footer (this is the behavior in master as of this writing)

The proposal is to try out option 1.

**Comment by SayakMukhopadhyay** [comment]
I think putting it into the breadcrumb header might become problematic for long context names
