### ISSUE TITLE
 UI templates for KUI (Sketch, Figma, Adobe XD)

### ISSUE THREAD

**Issue by danielone** [IBM/kui#5246]
It would great to have UI templates available (any format like Sketch, Figma, Adobe XD) so designers can mockup interactions with KUI!

- [x] TopNavSidecar
- [x] LeftNavSidecar
- [x] Scrollback
- [x] MiniSplit
- [ ] TabContent
- [x] TopTabStripe
- [x] StatusStripe
- [ ] Table (Card-wrapped Table with a Table/Grid choice)

Design docs are work in progress. See the current state here: https://github.com/IBM/kui/tree/master/design

**Comment by starpit** [comment]
Hello, thanks for the feedback! Agreed. We have some earlier designs in prototype form. We'll size up the updates and keep this issue apprised of the findings.

**Comment by danielone** [comment]
This would be great and very useful. Sketch and/or Figma would be my vote

**Comment by starpit** [comment]
we should have something rough in place by tomorrow! we'll commit it to the repo and ping this thread

**Comment by danielone** [comment]
Wow amazing thank you !!!

Best,
Daniel

**Comment by myan9** [comment]
Hi @danielone ! We have uploaded an initial UI template for sketch(https://github.com/IBM/kui/pull/5252). The template is still very rough and only has TopNavSidecar view. We will continue working on this and committing to the repo for the next couple of days. 

The TODO list for us is: 
1. enrich the template with more kui views
2. enhance the template by building kui sketch components

Which one would help you most? Thanks!

**Comment by starpit** [comment]
i have merged that initial PR. thanks @myan9 !

**Comment by danielone** [comment]
Thanks @myan9 !! TopNavSideCar seems most useful at this moment but Left as well. 
What would be valuable is also is an associated CLI to the left of it (light and dark mode) with some sample respective commands and confirmation/error messages. similar to your great animated gifs in the docs!
https://github.com/IBM/kui/wiki

**Comment by starpit** [comment]
we have merged in the LeftNavSidecar component.

**Comment by starpit** [comment]
we have pretty good coverage now. i will close this initial umbrella issue, and we can treat subsequent work on a more line-item basis.
