### ISSUE TITLE
openwhisk command usage bugs

### ISSUE THREAD

**Issue by myan9** [IBM/kui#54]
This command is wrong with insufficient arguments, but the error message is weird. We should provide clearer usage helper message.

![screen shot 2018-12-04 at 2 16 26 pm](https://user-images.githubusercontent.com/21212160/49467290-202edb00-f7d0-11e8-8703-7dcc9e984a28.png)

**Comment by myan9** [comment]
There's another usage issue here:
`This command requires 1 parameter, but you provided none`
should be:
`This command requires 2 parameters, but you provided none`


![screen shot 2018-12-05 at 11 58 28 am](https://user-images.githubusercontent.com/21212160/49529941-2337d300-f885-11e8-9c7b-3ac4ee665b02.png)

**Comment by myan9** [comment]
For now, not every clickable field in the usage model redirects us to a correct command. We should make sure that either the entity is not clickable or users can click the entity to get some correct command.

![screen shot 2018-12-05 12 10 17 pm](https://user-images.githubusercontent.com/21212160/49530813-fedcf600-f886-11e8-9069-7f9cf850b81e.png)

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/oui/issues/60
