### ISSUE TITLE
Problems using tutorials plugin

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [IBM/kui#557]
These are some problems I've encountered attempting to use the tutorials plugin in an external custom client.  Not all problems are specific to that use case.

- [ ]  After an `npm install` of kui, if you start a shell with `bin/kui shell`, the tutorials don't work because the samples directory was not copied to the build.  This problem can be manually corrected by doing what I think should have been done by the `npm install`
- [x]  If you run the webpack build of kui, the above problem doesn't happen but the tutorials plugin can appear broken because the `list` subcommand is not browser-friendly (attempts to use `fs`).   In fact, only listing is affected, but this is not a small issue (e.g., `usage` is broken as a result).
- [ ]  The plugin is too monolithic for use in an external client.  If I include it using `npm install`, I can't add tutorials to it (well, I can, by copying them deep into the plugin under `node_modules`, but, really ...).   I don't think I should need to clone and own it in order to extend it.
- [ ]  In creating new tutorial, I am hampered by the lack of documentation of the `tutorial.json` schema.  I am imitating bits and pieces of the existing tutorials but not always getting the expected results.

**Comment by starpit** [comment]
status update: 2 should be addressed by #1157

**Comment by starpit** [comment]
we have deprecated this plugin for now.
