### ISSUE TITLE
Unable to set PATH for installing cloud specific CLIs in the kui shell 

### ISSUE THREAD

**Issue by MeghanaSrinath** [IBM/kui#5659]
We are trying to build a production version of Kui by following the steps [here](https://github.com/IBM/kui/wiki/4.-Building-for-Production).
We have modified the [Dockerfile](https://github.com/IBM/kui/blob/master/packages/proxy/build.sh) to install the Gcloud-CLI (for GCP) and have set the `PATH` to the downloaded gcloud binary. Below are the extra lines of code that is added:
```
RUN mkdir /home/ubuntu
ENV HOME /home/ubuntu
#gcloud installation
RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
RUN mkdir -p /usr/local/gcloud \
  && tar -C /usr/local/gcloud -xvf /tmp/google-cloud-sdk.tar.gz \
  && /usr/local/gcloud/google-cloud-sdk/install.sh
ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin
```
After building the docker image and bringing up the container, Kui comes up in the browser. But on trying to use any gcloud commands, we are getting the error as `"bash:gcloud:command not found"`
On doing `echo "$PATH"`, we can see that the `PATH `env variable is only having `/root/.krew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin` and is not including the gcloud binary path that we have set above.

However, the `HOME` env variable is correctly set. 
And on running the command- `export PATH=/root/.krew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/ubuntu/google-cloud-sdk/bin` in the Kui shell, gcloud commands are working. But this is not persisting on opening a new terminal. 

Is there a reason why the `PATH` env variable is not getting set and is there a way to set these env variables across different sessions in Kui?

**Comment by starpit** [comment]
Hello, and thanks for the bug report.

First, a bit of background on the proxy architecture. We designed it to support multitenancy. To this end, the architecture has:

```
------------------------          --------------------------
| Express app           |   <==>  | one Kui headless       |
| with one /exec route  |   <==>  | subprocess per tenant  |
------------------------          --------------------------
```

In packages/proxy/app/routes/exec.js, you should see a call to `spawn`. This is where that tenant subprocess is spawned. You should also see the call to `allocateUser()`, and observe, with CAUTION, that in the open source repo, the implementation of `allocateUser()` is essentially a stub -- i.e. the tenant subprocess will run with the same uid and gid as the express app, as written in the open source code here.

Also notice how the `options` passed to the `spawn()` do not contain a pass-through of the PATH of the express app.

So: to fix you problem in short order, though perhaps not in the way you will need for a hardened production app, you can  update the options to pass through PATH to the tenant subprocesses; we chose not to do this in order to more fully isolate the tenant processes.

**Comment by starpit** [comment]
A bit more background on the architecture, for good measure: the browser client establishes a session by talking to the /exec endpoint of the express app. This sets up a websocket stream across which all subsequent communication flows. All Kui command executions in the browser client will then talk to the tenant subprocess over this websocket channel, rather than through the express app's exposed endpoints.

From a security perspective, you should also make sure that when you are serving up the index.html client, to rewrite the `kuiDefaultNonce` string to have a nonce for that request.

**Comment by MeghanaSrinath** [comment]
Thanks @starpit for the prompt response and the explanation. We will try this approach and update on this.

**Comment by MeghanaSrinath** [comment]
We have done the changes in the [exec.js](https://github.com/IBM/kui/blob/master/packages/proxy/app/routes/exec.js) file to include the `PATH `environment variable that we pass in the Dockerfile.
Below is the part of the file that is changed.

After the docker container is brought up and the Kui terminal is opened in the browser, on querying` echo $PATH` at `/` location, we can see the `PATH `that we have passed in the Dockerfile, i.e, `PATH=root/.krew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/google-cloud-sdk/bin:/root/bin:/usr/local/bin`

However, on moving to a different directory in the same session , say` /root` or `/home` and querying `echo $PATH`, the `PATH `is getting changed to `/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:.`

But on refreshing the browser, we can get back the originally set `PATH `, but it again gets changed on moving to a different directory. Due to this issue, the CLIs are not able to fetch the binaries from the correct paths.
Can you please let us know if there anything else that needs to be changed.


```async function allocateUser() {
  debug('allocateUser')
  const uid = undefined
  const gid = undefined

  // inherit HOME if we haven't otherwise decided to use a specific
  // uid/gid for this tenant
  const HOME = uid === undefined && process.env.HOME

  return { uid, gid, HOME }
}

/** thin wrapper on child_process.exec */
function main(cmdline, execOptions, server, port, hostname, existingSession, locale) {
  // eslint-disable-next-line no-async-promise-executor
  return new Promise(async (resolve, reject) => {
    const { uid, gid, HOME } = existingSession || (await allocateUser())

    const options = {
      uid,
      gid,
      cwd: execOptions.cwd || '/',
      env: Object.assign(execOptions.env || {}, {
        TRAVIS_HOME: process.env.TRAVIS_HOME,
        HOME,
        LOCALE: locale,
        DEBUG: process.env.DEBUG,
        PATH,
        DEVMODE: true,
        TRAVIS_JOB_ID: process.env.TRAVIS_JOB_ID,
        KUBECONFIG: process.env.KUBECONFIG,
        KUI_HEADLESS: true,
        KUI_REPL_MODE: 'stdout',
        KUI_EXEC_OPTIONS: JSON.stringify(execOptions)
      })
    }

    const wsOpen = cmdline === 'bash websocket open'
    if (wsOpen) {
      // N is the random identifier for this connection
      const N = uuid()

      const session = existingSession || {
        uid,
        gid,
        token: uuid() // use a different uuid for the session cookie
      }
      const sessionToken = Buffer.from(JSON.stringify(session)).toString('base64')
      const cookie = { key: sessionKey, session }

      const { wss } = await wssMain(N, server, port, cookie)

      debug('spawning subprocess')
      console.log("testing setting of the PATH ENV", mainPath) //added newly to debug
      const child = spawn(process.argv[0], [mainPath, 'bash', 'websocket', 'stdio'], options)

      child.on('error', err => {
        console.error('error spawning subprocess', err)
        reject(err)

**Comment by MeghanaSrinath** [comment]
@starpit , would you be able to help us out on this?

**Comment by starpit** [comment]
hey! sorry for the delay. looking...

**Comment by starpit** [comment]
hmm, this might be an unintentional bug in plugin-bash-like/src/pty/server.ts. could you try making this change to verify the fix?

```patch
diff --git a/plugins/plugin-bash-like/src/pty/server.ts b/plugins/plugin-bash-like/src/pty/server.ts
index 23e661ab7..575333204 100755
--- a/plugins/plugin-bash-like/src/pty/server.ts
+++ b/plugins/plugin-bash-like/src/pty/server.ts
@@ -329,7 +329,7 @@ export const onConnection = (exitNow: ExitHandler, uid?: number, gid?: number) =
           // eslint-disable-next-line no-async-promise-executor
           shells[msg.uuid] = new Promise(async (resolve, reject) => {
             try {
-              const env = Object.assign({}, msg.env || process.env, { KUI: 'true' })
+              const env = Object.assign({}, process.env, msg.env, { KUI: 'true' })
               if (process.env.DEBUG && (!msg.env || !msg.env.DEBUG)) {
                 // don't pass DEBUG unless the user asked for it!
                 delete env.DEBUG
```

**Comment by starpit** [comment]
PR: https://github.com/IBM/kui/pull/5798

**Comment by MeghanaSrinath** [comment]
@starpit , We still have the same issue even after making the change. Is there any other change required in other files apart from 
[server.ts](https://github.com/IBM/kui/blob/master/plugins/plugin-bash-like/src/pty/server.ts) ?

![image](https://user-images.githubusercontent.com/36357795/94566315-d27a4100-0287-11eb-801d-ac6c24d39c53.png)


![image](https://user-images.githubusercontent.com/36357795/94566395-e7ef6b00-0287-11eb-8a16-d83fe7b246dc.png)

**Comment by MeghanaSrinath** [comment]
Thanks for the quick fix @starpit :) Its working now and the `PATH `is getting persisted :)

**Comment by starpit** [comment]
awesome. let us know how it's going!
