### ISSUE TITLE
Proxy build fails on Ubuntu

### ISSUE THREAD

**Issue by amitsadaphule** [IBM/kui#5723]
**System**
OS: Ubuntu
OS version: 16.04
Platform: x86
Kui version: v8.12.2/master
node version: v12.16.1
npm version: 6.13.4

**Describe the bug**
After building KUI on Ubuntu 16.04, I tried to create proxy docker image using the steps from https://github.com/IBM/kui/tree/master/packages/proxy#building-the-proxy. But I got the following error:
```
amit@amit-vm:~/work/kui/packages/proxy$ ./build.sh
staging directory: /home/amit/work/kui/packages/proxy/kui-proxy-tmp/kui
staging directory /home/amit/work/kui/packages/proxy/kui-proxy-tmp
no prescan override
tar copy to /home/amit/work/kui/packages/proxy/kui-proxy-tmp from /home/amit/work/kui/packages/proxy
nothing to do
/home/amit/work/kui/node_modules/.bin//kui-build-headless: line 147: cd: /home/amit/work/kui/packages/proxy/node_modules/@kui-shell/client: No such file or directory
Building headless dist to /home/amit/work/kui/packages/proxy/kui-proxy-tmp/kui
cp: cannot stat '/home/amit/work/kui/packages/proxy/kui-proxy-tmp/kui/node_modules/@kui-shell/builder/dist/bin/kui.cmd': No such file or directory
cp: cannot stat 'kui/node_modules/@kui-shell/core/bin/*': No such file or directory
removed 1 package in 0.281s
mv: cannot move 'kui/prescan.json' to 'kui/node_modules/@kui-shell/prescan.json': No such file or directory
find: ‘kui/node_modules/@kui-shell/!(test)’: No such file or directory
find: ‘kui/node_modules/@kui-shell/!(test)’: No such file or directory
Cleanup
cp: cannot stat '/home/amit/work/kui/packages/proxy/node_modules/@kui-shell/builder/../proxy/package.json': No such file or directory
```

**Steps to reproduce the behavior**
```
git clone https://github.com/IBM/kui.git
cd kui
npm ci
npm run watch
export PATH=~/work/kui/node_modules/.bin/:$PATH
cd packages/proxy
export KUBE_VERSION=v1.19.0
npm install
./build.sh
```

**Expected behavior**
A docker image named kui-proxy should be created.

Please help me resolve this. Thanks in advance!

**Comment by amitsadaphule** [comment]
@myan9 @starpit any pointers? Am I missing something obvious?

**Comment by starpit** [comment]
Hello. We'll check this out and get back to you shortly!

**Comment by starpit** [comment]
Hi @amitsadaphule !

If your target is to serve up Kui via a combination nginx/kuiproxy docker image, you may use, from the top-level:

```bash
git clone https://github.com/IBM/kui.git
cd kui
npm ci
npx kui-build-webpack
npx kui-build-docker-with-proxy
```

When that is done, you should have a docker image `kuishell/kui`. To run this, try:

```bash
docker run --rm -p 9080:80 -e DEBUG=* kuishell/kui 
```

Then hit, on your host: `http://localhost:9080`. The `-e DEBUG=*` flag to docker run is not necessary, and will emit lots of debug output, but you can use it to see the kuiproxy messages; this will help confirm that things are flowing.

It looks like there may be a missing image or two in the image, but it seems to be functional. If you want to test out Kubernetes access, you will need to work out injecting your KUBECONFIG into the container. In build-docker.sh, there is some stub logic in the `function kubeconfig { ... }`. It copies in your ~/.kube, but doesn't know how to copy in anything beyond that, at the moment.

I have a PR open to simplify this slightly: https://github.com/IBM/kui/pull/5729

With that PR, you won't need to bother with the explicit building of the webpack bundles, i.e. the `npx kui-build-webpack` step from above. This also then will let you rebuild the docker image without having to do a full webpack bundle rebuild every time. That PR also introduces more strict warnings about injecting your KUBECONFIG into the container.

We will look into why the "connected to your cloud" image is missing.

**Comment by starpit** [comment]
Some more architectural detail: the `npx kui-build-proxy-with-docker` will build a single docker image that serves up the static content (i.e. the index.html and the webpack bundles) via nginx; this nginx will in turn reverse proxy to a headless kui that is also running inside the same image.

**Comment by amitsadaphule** [comment]
Thanks @starpit for helping out and for the detailed info! I'll try this out.

**Comment by amitsadaphule** [comment]
OK, I was able to create and run the image with the steps which you've mentioned. I'll try to test out Kubernetes access too. Thanks a lot!

**Comment by starpit** [comment]
wow, great news. let us know how it goes!

**Comment by amitsadaphule** [comment]
Mounting local _~/.kube_ directory inside the container makes kubectl commands work. Command used:
```
docker run --rm -v /root/.kube:/root/.kube -p 9080:80 -e DEBUG=* kuishell/kui
```
Closing the issue.

**Comment by starpit** [comment]
thanks very much for the sharing the additional information. much appreciated!
