### ISSUE TITLE
Unable to run Kui as a restricted bash with a non-root user

### ISSUE THREAD

**Issue by MeghanaSrinath** [IBM/kui#5813]
Currently, the Kui terminal is running with a single user. We are having a scenario where in we are trying bring up Kui as a restricted bash with multiple non-root users.

In the [Dockerfile](https://github.com/IBM/kui/blob/master/packages/proxy/Dockerfile), we have created 2 new non-root users- `developer` and `admin` and have assigned UIDs to them. Below lines of code are added:

```
RUN adduser admin --shell /bin/bash --home /home/admin -D -G users_group -u 1000
RUN adduser developer --shell /bin/bash --home /home/developer -D -G users_group -u 1001
```
On running the docker container with the command `docker run --name kui $DEBUG --rm -p 9080:80 kuishell/kui`
we can see that `/home/admin` folder is created for `admin` user and `/home/developer` folder is created for the `developer` user in kui.  Any user can navigate between any of these folders.

However on executing `su admin`, the shell changes to restricted bash of the `admin` user. `Admin` would not have access to other folders and same holds good for the `developer`. All the rules of a restricted bash apply.

Now, `admin` or the `developer` can logout of their restricted shell on `exit` command and the control comes back to the main bash shell. In this case, `admin` or the `developer` can still access each others' folders on `exit`. We are trying to avoid this.

We then tried running Kui as `admin` user by specifying `USER admin` in the dockerfile, just before the `CMD`. 
```
RUN adduser admin --shell /bin/rbash --home /home/admin -D -G users_group -u 1000
USER admin
CMD [ "/usr/share/nginx/html/start-proxy-and-nginx.sh" ]
```
On building the dockerfile and running it, we got the below error
```
#docker run --name kui $DEBUG --rm -p 9080:80 kuishell/kui
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
2020/09/30 07:59:14 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:3
```
On removing `USER admin` from the dockerfile and trying to run the command `docker run --name kui --user admin $DEBUG --rm -p 9080:80 kuishell/kui`, we get the below error:
```
2020/09/30 08:50:33 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:3
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:3
2020/09/30 08:50:33 [emerg] 1#1: mkdir() "/var/tmp/nginx/client_body" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/tmp/nginx/client_body" failed (13: Permission denied)

```
We are thinking this is because in `/etc/nginx/nginx.conf` , the user is specified as `nginx`.
Is there a way in which we can achieve our scenario? We are trying to see if we can bring up Kui as restricted bash with non-root users. Please let us know your thoughts on this.

**Comment by MeghanaSrinath** [comment]
@starpit , would you be able to look into this?

**Comment by starpit** [comment]
Hi, and sorry for the delay! We've been working on the 9_0_x release. We should be done with this by tomorrow, and will be able to help then!

**Comment by starpit** [comment]
Hello, we have released 9.0.0!

Let me see if I can echo your requirements? Would your needs be met if every Kui session is isolated as a POSIX user with restricted bash in a multitenant Kui proxy?

**Comment by MeghanaSrinath** [comment]
Sorry for the delay in response @starpit ! And congratulations on the new release! Will try the latest version in our setup.
As for the requirement, we are basically looking at running the kui terminal as a non-root user. So if build the docker image and then we want the pod containing the kui docker image to run as a particular user, kui should accept the `runAsUser `and `runAsNonRoot `values in the deployment yaml file. 
And if we are bringing up multiple kui pods in the same cluster, each pod should be able to accept a different userID to run as a non root user. Right now, even the docker build is not accepting new users. We can probably have the existing shell terminal instead of a restricted bash. Is this possible?

And also, is there any other feature that is possible to be implemented where different users can login to the same kui terminal, but they can get their own isolated environment to work as such?

**Comment by starpit** [comment]
Hi @MeghanaSrinath 

The proxy is structured as follows:

```
Client <-> Nginx <- reverse proxy -> proxy.js express app <-> Kui headless process ("tenant process")
```

The proxy.js express app will launch a new tenant process for every session initilalization request from the Client; this is done via the `/exec` endpoint on the proxy.js app.

The `allocateUser()` function in proxy.js is a stub (at least in the open source code). This is because the policy for creating a tenant is largely dependent on your integration needs. For example, you may need to talk to a backend in order to set up a session with your cloud provider, so that the end user will be "good to go" with your cloud, once Kui has finished initializing the Kui session.

In this sense, the proxy architecture is implicitly multi-tenant.

**Comment by MeghanaSrinath** [comment]
Thanks for the explanation provided. It helps in understanding the flow!
So we understand that for every session, a new process is launched. But all these sessions and the kui terminal run as `root `user. Currently, if we specify a non-root user in the [Dockerfile ](https://github.com/IBM/kui/blob/master/packages/proxy/Dockerfile)and try to run as this` non-root` user, we get the error as stated above
```
nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
2020/09/30 07:59:14 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:3
```
We are basically now trying to avoid running any container as `root`. Can this be achieved?

**Comment by starpit** [comment]
One possibility is to have a exec.js where `allocateUser()` creates a new UNIX user, and then returns the gid and uid of that new user.

Then, when the Kui subprocess is launched, it will be spawned with that uid and gid, thus limiting its exposure.

A second layer you can add is to have the new users created so that their bash is `rbash` (i.e. restircted bash). You can then establish your rbash policies to scope what a tenant is allowed to see.

**Comment by MeghanaSrinath** [comment]
Thank you, We will try this method and see if we can get the desired results.

**Comment by starpit** [comment]
great! let us know how it goes!

**Comment by MeghanaSrinath** [comment]
We are able to create users with a UID in the [Dockerfile ](https://github.com/IBM/kui/blob/master/packages/proxy/Dockerfile)and able to pass this UID in the `allocateUser()`. So the container is running as the specified user. Thanks for the help @starpit
