### ISSUE TITLE
composer is flaky in webpack

### ISSUE THREAD

**Issue by myan9** [IBM/kui#584]
- [x] `preview @demos/if.js` fails because of a readFile for webpack bug with imports
- [x] `preview -c @demos/if.js` fails for that bug, and a few other similar bugs
- [ ] app deployment doesn't work in webpack
`Composer client` (in `openwhisk-composer libararay`) is implemented to grab credentials from local `wskprops`, so in Webpack mode, we need to pass the `api_host` and `api_key` in `options` (in `apache-composer/lib/controller/client`) based on `window.localStorage` or `process.env.__OW_API_KEY ` or `process.env.__OW_API_HOST`

- [ ] clicking Deploy in `compose foo.js` fails because the composition persister uses `tmp.file`

**Comment by starpit** [comment]
#1167 covers the first two

**Comment by starpit** [comment]
moving to https://github.com/kui-shell/oui/issues/56
