### ISSUE TITLE
wsk -i does not work

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#599]
to use kui with a self-signed host, you need to start it with IGNORE_CERTS=true (although there is some magic that saves you from that for some hosts).

if you neglect to do that, `wsk -i` does not work and reports: 'Unsupported optional parameter i`.

i'd think `wsk -i` should work... but also, this may be more convenient: it would be helpful to `host set <...> -i` where the `-i` property here will allow you to eschew it on every `wsk` command.

**Comment by starpit** [comment]
moving here https://github.com/kui-shell/oui/issues/55
