### ISSUE TITLE
Windows PathStyle 

### ISSUE THREAD

**Issue by Berndinox** [IBM/kui#6006]
**Describe the bug**
`error: the path "C:UsersBerndAppDataLocalTempkui--3412-2iBvUQxGfLcs" does not exist`

**We miss "\"**

The issue was already tracked with: https://github.com/IBM/kui/issues/4928
Pops up now again

**Steps to reproduce the behavior**

1. Install on Windows
2. Edit any YAML

**Expected behavior**
i can edit YAML Files

**System**
- Kui version: 9.0.4
- Operating system: Windows 10 latest

**Comment by starpit** [comment]
Thanks for the bug report! We'll check it out. 

Can you confirm: did you launch Kui from PowerShell? (versus e.g. git bash)? Or by double click?

**Comment by Berndinox** [comment]
I think through double Click. But i will Double Check

**Comment by starpit** [comment]
Hello there. We can confirm that `edit` followed by clicking the Save button results in the documented issue. Have you found any other situations that exhibit the same bug? thanks!
