### ISSUE TITLE
Add Linux/ARM64 support to Kui

### ISSUE THREAD

**Issue by odidev** [IBM/kui#6015]
Hi Team,

I am interested in adding Linux/ARM64 jobs to Travis-CI. 
I have checked that Kui does not contain ARM64 support. Binaries are available for Linux/AMD64, Windows and Darwin only.
After some analysis, I have found that the source code downloads some binaries for AMD64, like minio, kubectl, kubernetes-helm, odo; which are available for Linux/ARM64. For adding ARM64 support to Kui in my forked repo, I have replaced them all for Linux/ARM64.
 

- For ARM64 Travis-CI jobs index 1 and 2, ‘oc’ binary gets downloaded via microk8s.sh file, which is not available for ARM64. However, source code to openshift/oc supports ARM64, and I have raised a ticket in ‘openshift/oc’ for providing the ARM64 ‘oc’ binary.

 

- ARM64 Jobs 3-6 are failing to start chrome, and gives the following error:

~~~
Error: unknown error: Chrome failed to start: exited abnormally
(chrome not reachable)
(The process started from chrome location /home/travis/build/odidev/kui/node_modules/spectron/lib/launcher.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
(Driver info: chromedriver=78.0.3905.1 (adc3a81bb97a90bf5417e850ea9d612cdbfcdef4-refs/heads/master@{#703739}),platform=Linux 5.3.0-40-generic aarch64)
~~~

Here are the chrome errored logs <https://travis-ci.com/github/odidev/kui/jobs/401284543#L14701>

Please find my ARM64 errored Travis-CI jobs here: <https://travis-ci.com/github/odidev/kui/builds/190648234> 

I have checked that binaries for ‘electron’ and ‘chromedriver’ are available for ARM64. As can be seen from the travis logs, ChromeDriver is getting installed via “npm ci” command, and is available for AArch64 as well. I have verified this by executing “npm ci” on a local ARM64 machine, and checked the chromedriver binary inside ‘kui/node_modules/electron-chromedriver/bin’ folder with the “file chromedriver” command. Also, ‘electron’ is available for ARM64, and electron-arm64.zip is getting downloaded during “npm ci”.

For the fix, I have changed the ‘dist’ to ‘bionic’ in .travis.yml, changed the go version from ‘stable’ to ‘1.15’ here <https://github.com/odidev/kui/blob/master/tools/travis/ibmcloud-plugin-build-install.sh#L6>, and installed Chromium-browser version 78 for ARM64 ubuntu:bionic via .travis.yml file, from here <https://launchpad.net/ubuntu/bionic/arm64/chromium-browser/78.0.3904.97-0ubuntu0.18.04.1>, and successfully installed it on Travis. Please find my Travis.yml here <https://github.com/odidev/kui/blob/master/.travis.yml#L42> where steps for chromium-browser installation are added in the ‘install’ clause. However, this has not solved the problem.
Also, I have included the “--headless” flag to chrome arguments here <https://github.com/odidev/kui/blob/master/packages/test/src/api/common.ts#L162>, but again no luck.

If you are interested in this activity, I am ready to contribute. It would be really helpful if Linux/ARM64 support is added to Kui. Can you please provide me with some pointers for the above issues?

**Comment by starpit** [comment]
Wow, this is a great analysis, thank you! We will digest it and get back to you.

**Comment by starpit** [comment]
in terms of getting the client going (we haven't tried travis, yet), it seems like only a few small changes are needed:

<img width="1023" alt="Screen Shot 2020-10-22 at 12 46 39 PM" src="https://user-images.githubusercontent.com/4741620/96904199-c5a2d480-1464-11eb-9707-5e1a5ce5eed3.png">

**Comment by starpit** [comment]
I don't yet understand why chromedriver fails to start on arm64. From the chromedriver logs:

```
[1603402349.835][INFO]: Launching chrome: /home/ubuntu/kui/node_modules/spectron/lib/launcher.js --disable-bac\
kground-networking --disable-client-side-phishing-detection --disable-default-apps --disable-hang-monitor --di\
sable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=Sha\
dowDOMV0 --enable-logging --force-fieldtrials --ignore-certificate-errors --load-extension=/tmp/.org.chromium.\
Chromium.7mnNVA/internal --log-level=0 --no-first-run --password-store=basic --remote-debugging-port=0 --spect\
ron-arg0=../../node_modules/@kui-shell/core/dist/main/main.js --spectron-path=/home/ubuntu/kui/node_modules/el\
ectron/dist/electron --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.u4d\
NgD --verbose data:,
_stream_readable.js:684
    dest.end();
         ^

TypeError: dest.end is not a function
    at Socket.onend (_stream_readable.js:684:10)
    at Object.onceWrapper (events.js:420:28)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

And, when I issue that launcher.js command line by hand, it does not error out.

**Comment by starpit** [comment]
I have opened an issue with spectron, to see if they have any ideas. https://github.com/electron-userland/spectron/issues/745

**Comment by starpit** [comment]
I may merge in the experimental support for arm, so that at least we can start prototyping around it. And open a separate bug to track the spectron/chromedriver issue on arm.

**Comment by starpit** [comment]
The merged PR does the following to help with prototyping arm64 support:

1) a new `npm run build:electron:linux:arm64` script target in the top-level package.json to build an electron client
2) prebuilt node-pty binaries for linux-arm64, so that pty commands will work from electron clients

Pending work is figuring out the test situation. #6060

We will probably release experimental arm64 builds as part of the upcoming 9.1.0 release.
