### ISSUE TITLE
custom repl-prompt is misaligned with repl-output

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6046]
For clients that instantiate the Kui component with a custom prompt, e.g. 
```jsx
<Kui prompt=">" />
```

the prompt is misaligned, both vertically w.r.t. the Input, and also horizontally w.r.t. the rendered Output

![Screen Shot 2020-10-21 at 1 58 08 PM](https://user-images.githubusercontent.com/21212160/96772274-e6a9ed80-13b0-11eb-8b72-8ed6ca721c08.png)

**Comment by starpit** [comment]
Desired:

<img width="989" alt="Screen Shot 2020-10-21 at 3 24 42 PM" src="https://user-images.githubusercontent.com/4741620/96772733-91baa700-13b1-11eb-842e-8529782ab0dd.png">
