### ISSUE TITLE
removing previous blocks will cause errant rendering to edit command result

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6093]
I think edit command doesn't save the changed content back to the model, so when blocks re-rendering happens, changes made in the editor will disappear.

1. type some random commands, like `ls`
2. edit foo.yaml -> make some changes -> hit save
3. remove the first repl block ->  see the change made to foo.yaml disappear

**Comment by starpit** [comment]
the fact that removing a block causes such deep re-rendering is just a symptom of the bigger problem, i.e. that doing anything to some other block should cause re-rendering of the output of  any other block; at most, i would expect only the In[n], i.e. the block sequence number, to be re-rendered
