### ISSUE TITLE
don't show inline DiffEditor when there's no pending changes detected 

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6184]
Currently DiffEditor is used to detect if there's any difference between dry run result and deployed resources. When there's no changes, it still show two vertical line numbers. 

![Screen Shot 2020-11-19 at 11 56 35 AM](https://user-images.githubusercontent.com/21212160/99698006-47831f00-2a5e-11eb-9d0f-93e5bc9fb66d.png)

**Comment by starpit** [comment]
closing in favor of the latest work, which has removed the diff capability in favor of a better way of approaching diffs.
