### ISSUE TITLE
The label categorization in the `get -f` tree isn't always correct

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6185]
The following redis service has three labels: `app: redis`, `role: master`, and `tier:backend`, but the TreeNav showed only part of the labels, which is very confusing. And the fact that the labels are three distinctive children of `All Resources` makes me feel that there are three distinctive resources, but it's not true. We need more heuristics to describe an application structure. But for now, let's improve the label first.

![Screen Shot 2020-11-19 at 3 39 35 PM](https://user-images.githubusercontent.com/21212160/99721561-6f35af80-2a7d-11eb-8f2b-a3baf84bd332.png)
![Screen Shot 2020-11-19 at 3 48 15 PM](https://user-images.githubusercontent.com/21212160/99722426-a5bffa00-2a7e-11eb-92de-afb0eda1c545.png)

**Comment by starpit** [comment]
i thought we were only looking at the `app` label?
