### ISSUE TITLE
the order of app list result is different in Electron and Headless

### ISSUE THREAD

**Issue by myan9** [IBM/kui#62]
It seems like in Electron mode, app list gets sorted by alphabetic order, but in Headless mode, app list is in correct time order. The weird thing is that the code of app list command handler didn't differentiate Headless and Electron. I set `debug('apps', apps)` after `let apps = actions.filter(astUtil.isAnApp)`, and the order of resulted apps is different in Electron and Headless.

Code Reference:
https://github.com/IBM/kui/blob/master/app/plugins/modules/apache-composer/src/lib/controller/commands.ts#L180-#L194

app list in Electron:
![screen shot 2018-12-06 at 10 46 43 am](https://user-images.githubusercontent.com/21212160/49595026-22ff0c80-f945-11e8-9ce2-ab713ba9c2c5.png)

app list in Headless:
![screen shot 2018-12-06 at 10 53 22 am](https://user-images.githubusercontent.com/21212160/49595041-2b574780-f945-11e8-9427-cc8705028602.png)

**Comment by myan9** [comment]
Same Error in ibm-functions/Shell
![screen shot 2018-12-06 at 11 00 50 am](https://user-images.githubusercontent.com/21212160/49595559-3e1e4c00-f946-11e8-97d3-f63674c3b612.png)

**Comment by starpit** [comment]
you need to add a `noSort: true` property to the entities if you want natural ordering
