### ISSUE TITLE
@patternfly/react-core breaks the indentation of TreeView

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6224]
@patternfly/react-core has floating dependency on @patternfly/react-styles, which bumps the version to ^4.7.5 every time we generated new package-lock.json. As mentioned in https://github.com/patternfly/patternfly-react/issues/5165, the identation of TreeView is kinda broken. To fix this issue quickly for 9.2.0 release, I'll pin the version of @patternfly/react-styles to a version that works.

**Comment by starpit** [comment]
As of 2012.14, `@patternfly/react-core` now specifies
```json
    "@patternfly/react-styles": "^4.7.16"
```

which means that patternfly's react-core will now use the buggy 4.7.16, despite our attempt to override with 4.7.12

**Comment by myan9** [comment]
PatternFly 2012.14 breaks the indentation of TreeView again. We fixed this issue by pinning `@patternfly/react-styles` to 4.7.12 previously, but `@patternfly/react-core` now has`"@patternfly/react-styles": "^4.7.16"`, which resulted in two copies of @patternfly/react-styles in our node_modules. Thus, we decided to  override the treeview css rules instead.
