### ISSUE TITLE
Another Windows Path Issue

### ISSUE THREAD

**Issue by Berndinox** [IBM/kui#6353]
![image](https://user-images.githubusercontent.com/1122698/101476786-8f56e100-394e-11eb-81f1-860afafcd1c8.png)

Path should be `C:\users` and not` C:\\users`

**System**

- Kui version: 9.2.8
- Operating system: Windows 10

**Comment by starpit** [comment]
Thanks again for the vigilance on windows. And sorry for the huge delay. A fix is targeted for the soon-to-be-released 10.0.0!
