### ISSUE TITLE
Add OWNERS and SECURITY_CONTACTS files to Kui repo

### ISSUE THREAD

**Issue by paulcastro** [IBM/kui#6400]
We should add owners and security contacts files to conform to SIG CLI subproject practices

**Comment by starpit** [comment]
we have this: https://github.com/IBM/kui/blob/master/.github/CODEOWNERS

**Comment by starpit** [comment]
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners

does kubernetes use a different convention?

**Comment by paulcastro** [comment]
@starpit  I'll submit PR and let me know what you think?
