### ISSUE TITLE
monaco editor captures scrolls even when there's nothing to scroll

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6480]
Monaco editor captures scrolls even when there's nothing to scroll. This becomes more annoying when editor is shown in splits, where there's only a limited space for user to place the cursor and force a page scroll. If monaco doesn't allow us to control the scroll, we should consider to use alternative editors, e.g. ACE.

**Comment by aderepas** [comment]
You can just do:

```js
monaco.editor.create(editor {
            scrollbar: {
                alwaysConsumeMouseWheel: false
});
```
Should work :)

**Comment by starpit** [comment]
thanks! indeed, i think that is what @myan9 did here: https://github.com/kubernetes-sigs/kui/pull/6483/files#diff-5be1d3e9ad43d9e184da187977dea795218fa30c1a7cd3a1afc239db5630d588R37
