### ISSUE TITLE
use Dropdown for RadioTable impl

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6539]
PatternFly doesn't have RadioTable component, so we'll keep the Kui RadioTable model and use Dropdown for its impl for now.

**Comment by starpit** [comment]
In addition to cleaning things up internally, i think this might actually be of benefit to the UX. For example, here is the output of `git branch` with this suggestion:

<img width="184" alt="git branch with dropdown" src="https://user-images.githubusercontent.com/4741620/104342425-d0e82800-54c8-11eb-8a39-bf1c5b82759c.png">

I think it is nice that the output of `git branch` shows me just my branch, but also gives me an opportunity to change it. What we have now, the current selection is hidden in a potentially very long list of branches, i.e. currently we show a table of *all* branches as the initial UI response for`:

<img width="583" alt="git branch old radiotable" src="https://user-images.githubusercontent.com/4741620/104344923-be232280-54cb-11eb-964f-3ff5aa1370e9.png">
git branch`
