### ISSUE TITLE
reloading browser when streaming events may cause websocket channel to crash

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6608]
We caught this failure in tests. When events are streaming, sometimes browser reloads when we are retransmitting the messages from kui proxy to the browser, so websocket fails at sending the data, throw uncaught errors and crashes.

**Comment by starpit** [comment]
i wonder if we should add try/catch around all of the `this.ws.*` operations?

**Comment by starpit** [comment]
i think we're still missing a few cases
