### ISSUE TITLE
version numbers damaged on macOS

### ISSUE THREAD

**Issue by core-code** [IBM/kui#6725]
i've downloaded version 9.3.11 but it claims to be version 9.3

the *CFBundleShortVersionString* and * CFBundleVersion* entries in your *Info.plist* file are broken

<img width="593" alt="Screenshot 2021-01-25 at 20 50 18" src="https://user-images.githubusercontent.com/1261954/105758054-21429980-5f4f-11eb-90be-719f1077ad83.png">

**Comment by starpit** [comment]
Thanks for the bug report! It looks like the fix that we anticipated would resolve this issue https://github.com/IBM/kui/pull/6508 actually did not.

**Comment by starpit** [comment]
🤦 it looks like the fix was fine, but our build machine does not have `jq`, and packages/builder/dist/electron/build.sh currently has a dependence on jq for determining the build version.

**Comment by starpit** [comment]
9.3.12 is out, with the fix. Thanks again for the bug report, good catch!

**Comment by core-code** [comment]
thanks for the quick turnaround, i can confirm this is resolved
