### ISSUE TITLE
event watcher doesn't render well in minisplit

### ISSUE THREAD

**Issue by starpit** [IBM/kui#6772]
In the upper left is an event watcher. Note the whitespace above the event section (dark background). In the lower portion is the same command, but observe here that there is no whitespace above the events.

Maybe this is a separate issue, but in the upper left you can observe that `k get events` without the watch renders differently... and also poorly in a minisplit.

<img width="837" alt="Screen Shot 2021-01-27 at 8 24 18 AM" src="https://user-images.githubusercontent.com/4741620/105997038-1f74f500-6079-11eb-82e3-fdf815d6bfab.png">

**Comment by myan9** [comment]
Drilling down a event grid issues a wrong command: e.g. `kubectl get Event 3m40s -o yaml -n default`
![Screen Shot 2021-01-27 at 10 13 23 AM](https://user-images.githubusercontent.com/21212160/106011268-4c7cd400-6088-11eb-8130-91bfb8a4c975.png)

**Comment by myan9** [comment]
The Reason cells of a plain events table are not aligned with the header. This issue only happens to the lower Terminal with 2 minisplits. The other splits cases are good.
![Screen Shot 2021-01-27 at 10 16 43 AM](https://user-images.githubusercontent.com/21212160/106011753-c319d180-6088-11eb-9564-694bc32b52d7.png)
