### ISSUE TITLE
remove sidecar events mode

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6847]
We should replace the Sidecar Events Mode with a toolbar button to show the events table in REPL.

**Comment by starpit** [comment]
1) Allows for easy reuse of a single events view, both watchable and static, and reduces arbitrary variance in the way events are presented
2) Allows for simultaneous viewing sidecar content and events
3) Allows the user to place the event watcher wherever they want, and with minimal decoration, as opposed to having it be in a sidecar
