### ISSUE TITLE
table in some width-constrained blocks are auto-gridified but in others are presented as list

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6915]
The minisplits in lower left and upper right should all auto-gridify table with multiple rows

![Screen Shot 2021-02-01 at 2 42 55 PM](https://user-images.githubusercontent.com/21212160/106509571-c69fc500-649b-11eb-9eea-d71e316009d8.png)

**Comment by starpit** [comment]
This is because six- and seven-split layouts have two splits of the same size, one mini one plain. We should probably be consistent, in that a split is either mini or plain based on its size.
