### ISSUE TITLE
Context and namespace widgets: use Select rather than Dropdown? Support tab pinning?

### ISSUE THREAD

**Issue by starpit** [IBM/kui#6920]
A few UX issues with our current use of a Dropdown UI for the CurrentContext and CurrentNamespace status stripe widgets.

1) If i have a large number of namespaces or contexts, the dropdowns become unwiedly. The PatternFly Select widget supports favoriting and typeahead find. https://www.patternfly.org/v4/components/select#favorites
Maybe a Popover with some descriptive text and a Select?

2) A Popover widget could help with pinning context or namespace to Kui tab. e.g. a Pin icon in the upper right of the Popover. Then the widgets could listen to tab switch events and auto-adjust the context or namespace, based on the user's choice of Pinning. One bit of complexity here: pinning a namespace implies pinning a context, but the reverse is not true.

**Comment by mark-nc** [comment]
Following this discussion....

We have noticed that customer use cases for Red Hat Openshift Container Platform (OCP) often result in lots of namespaces, especially in large organizations.  And customers in larger organizations are growing the number of clusters they manage.
