### ISSUE TITLE
Commentary Markdown doesn't show numbers in a list

### ISSUE THREAD

**Issue by myan9** [IBM/kui#6947]
As shown in the Commentary screenshot , if texts contain 1.2.3., our Markdown Renderer doesn't seem to render the number.
![Screen Shot 2021-02-03 at 3 26 27 PM](https://user-images.githubusercontent.com/21212160/106805046-30eb6d80-6634-11eb-8430-3f6af4474a89.png)

**Comment by starpit** [comment]
bug in my fix for this bug :(

```
  /** This group of rules override default user-agent stylings */
  ol,
  ul {
    &:not(.pf-c-list) {
      margin: 0;
      padding-inline-start: 0;
      & > li {
        list-style-type: none;
      }
    }
  }
```

missing `>` there in the `& > li`
