### ISSUE TITLE
When my openshift credentials expire, Kui gives a poor error message

### ISSUE THREAD

**Issue by starpit** [IBM/kui#6956]
> Error from server (Unauthorized): Unauthorized

**Comment by myan9** [comment]
Fixed by https://github.com/IBM/kui/pull/6957

![Screen Shot 2021-02-05 at 2 50 44 PM](https://user-images.githubusercontent.com/21212160/107081985-8739e700-67c1-11eb-9907-b820bd34f5ff.png)
