### ISSUE TITLE
allow clients to define a default kubectl CLI

### ISSUE THREAD

**Issue by starpit** [IBM/kui#7051]
Right now, we have some widgets that hard-wire use of `kubectl`.  This may go beyond the widgets, now that I think about it.

It would be nice to have this default definition in the hands of the Kui client author.

**Comment by starpit** [comment]
maybe wherever we invoke kubectl on our own, we can invoke _default_kubectl ..., and then define a wrapper command that delegates this to the client’s default kubectl? 🤔

**Comment by starpit** [comment]
or just import { kubectl } from '@kui-shell/plugin-kubectl' and then have a single place that determines whether the client defined something… that’s probably simpler
${kubectl} get pods

**Comment by myan9** [comment]
PR https://github.com/IBM/kui/pull/7090 ported status stripe widgets to use client defined kubectl cli. The Remaining invokes of `kubectl` are: watch, table onclick handler, breadcrumbs and sidecar buttons
