### ISSUE TITLE
consider using kui for KUBE_EDITOR and GIT_EDITOR

### ISSUE THREAD

**Issue by starpit** [IBM/kui#762]
we could offer the editor plugin as an EDITOR; this might allow e.g. `kubectl edit` and `git commit` to work in a way that leverages the monaco editor in a fairly transparent fashion

**Comment by starpit** [comment]
closing as "way out"

**Comment by myan9** [comment]
This should be more doable now with react. The biggest issue to work through is whether we should reimplement `k edit` entirely, assuming certain aspects of its semantics? e.g. do a get -o yaml, then save does an apply? It seems like a good task for a new contributor.

**Comment by starpit** [comment]
should we also consider adding an Edit toolbar button to the `kubectl get` sidecar response?
