### ISSUE TITLE
in browser+proxy mode, `command not found` are showed when click `conditions`

### ISSUE THREAD

**Issue by Xiaohua-Shen** [IBM/kui#844]
<img width="1662" alt="屏幕快照 2019-03-15 上午9 21 26" src="https://user-images.githubusercontent.com/19463092/54401747-eee57580-4703-11e9-99c6-943adf3e6fbb.png">

and proxy related log as this:
<img width="247" alt="屏幕快照 2019-03-15 上午9 04 35" src="https://user-images.githubusercontent.com/19463092/54401198-b2187f00-4701-11e9-99df-fc90b1ad8597.png">
and If I key in after the prompt, no any response.

**Comment by myan9** [comment]
Thanks for reporting the issue!  🔆 
I noticed that you're using an ancient version of Kui. Please try our latest release and see if your problem got solved.

**Comment by starpit** [comment]
i think this should be fixed by #908 and the publish documented by PR #909
