### ISSUE TITLE
pasting clipboard into editor loses focus

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#847]
if you're editing an action and paste some code into the editor, the focus is lost and is captured by the command prompt.

**Comment by starpit** [comment]
https://github.com/IBM/kui/blob/master/plugins/plugin-core-support/src/lib/repl-focus.ts#L97-L99

the repl-focus module grabs focus to the repl on any paste. this is probably a very old bug. note in that module the more recent focus grabbers pay closer attention to whether there is currently a focus, etc.
