### ISSUE TITLE
kubectl commands stuct in no-proxy webpack

### ISSUE THREAD

**Issue by myan9** [IBM/kui#852]
![Screen Shot 2019-03-15 at 10 37 24 AM](https://user-images.githubusercontent.com/21212160/54439112-88b22000-470e-11e9-9213-79e487a632a3.png)
![Screen Shot 2019-03-15 at 10 37 28 AM](https://user-images.githubusercontent.com/21212160/54439118-8c45a700-470e-11e9-90a9-c8634ae6aebd.png)

First, fix the pending promise. Then, we should throw the auth error and guide users to use proxy in kubectl case.

This issue only happened when I built webpack by `KUI_USE_PROXY=false npm run build:webpack`. Without `KUI_USE_PROXY=false`, I got `failed to fetch` as expected.

**Comment by starpit** [comment]
isn't this #293 ?

**Comment by myan9** [comment]
Close: Duplicate of #293

**Comment by myan9** [comment]
Duplicate of #293
