### ISSUE TITLE
some command results "fade in"

### ISSUE THREAD

**Issue by rabbah** [IBM/kui#950]
type "wsk li" then enter and you get an error message that fades in.
type "wsk xyz" and the response error message appears "instantly".
i'm not sure which is the intended behavior - always fade in or not... a lot more commands do not fade in and i think is preferable from a user experience, wdyt?

![xyz](https://user-images.githubusercontent.com/4959922/54693569-4406fa00-4afd-11e9-9c33-7f4ab7a29844.gif)

**Comment by starpit** [comment]
interesting find, thanks! the distinction here is between error results that provide a usage model and those that don't. i think the UI for usage-decorated errors is fade-in. this can be easily disabled! i'll do that.
