### ISSUE TITLE
"kubectl get" summary tab not working for some types

### ISSUE THREAD

**Issue by esnible** [IBM/kui#988]
To reproduce,

Install Istio; install Istio Bookinfo sample

`kubectl get gw,vs,dr,se,policy,sidecar`
click on one of the returned items.

There will be a 'Kind' and 'Annotation' but nothing like the Spec.  Nothing like the `kubectl describe` output.

(Possibly related to https://github.com/istio/istio/issues/10872 )?

This may not be a problem with Istio CRDs, I see the same thing for `kubectl get crd certificates.certmanager.k8s.io`

**Comment by starpit** [comment]
we will be updating the summary tab in a way that does not try to replicate describe. PR in flight
