### ISSUE TITLE
status inconsistencies

### ISSUE THREAD

**Issue by esnible** [IBM/kui#989]
When I `kubectl get pods` the status of my pods are all "Running".
When I `kubectl get pod <pod>` the status is stuck at blinking "Pending" for a few seconds, then blinking "Initialized".

When I do `kubectl get <istio-type>` there are no status fields (which is expected), but when I click on one the summary begins at "Pending" and then becomes "Online" after about six seconds.

**Comment by starpit** [comment]
this should be resolved now with #2652
